### ISSUE TITLE
Let me use it

### ISSUE THREAD

**Issue by xowe1** [THUDM/CogVideo#1]
Please

**Comment by woctezuma** [comment]
- #2

**Comment by PWhiddy** [comment]
Hi, first of all congratulations on the results and thanks for sharing this very cool work!

Regarding this line in the paper:
> We present CogVideo, which is the largest and the first open-source pretrained transformer for text-to-video generation in the general domain

I think it’s inappropriate to claim to be “first to open source” before this has been accomplished.

**Comment by wenyihong** [comment]
The code, demo and model have been released. Have fun!
