### ISSUE TITLE
[Finetune] VAE encode cost much GPU memory (30-40GB for encode_first_stage) (total up to max 70GB)

### ISSUE THREAD

**Issue by NickPan7779** [THUDM/CogVideo#105]
### System Info / 系統信息

py3.9
A800 cuda12.1

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

 During a training step (in shared_step), before `encode_first_stage`, GPU memory cost 30GB. Then during encoding in  `encode_first_stage`, GPU memory cost up to max 70GB. After `encode_first_stage`,  the GPU memory cost will fall back to 30-40GB.The input video x shape is [1, 49, 3, 480, 720]. The situation of  GPU memory cost will lead OOM in NPU device during `encode_first_stage`.  So is the input x (video) too large? Or any other suggestion? VAE encoding cache?
Thanks all of you.

### Expected behavior / 期待表现

Run finetune within 60GB successfully.

**Comment by tengjiayan20** [comment]
"GPU memory cost up to max 70GB."
How did you get this conclusion? Did you meet OOM error? It may be just cache.

**Comment by NickPan7779** [comment]
OOM happens on npu device since npu has only 60GB memory. When I sft with sat on npu，it always report OOM during the encode first stage in one train step. So I tried on A800 and set pdb trace before and after encode first stage.Then I watch the nvidia-smi and run the encode step in debug. I find that gpu memory cost always more than 60 GB and 70+GB for max during vae encode first stage. Finally, the memory cost will fall back to 40 GB after vae encode.
So can you reproduce the memory situation?
Or some mistakes happen at my configs.🔧

**Comment by NickPan7779** [comment]
I will try vae cache.
