### ISSUE TITLE
可以在torch2.1上跑吗？

### ISSUE THREAD

**Issue by badarrrr** [THUDM/CogVideo#106]
### System Info / 系統信息

torch 2.1

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1

### Expected behavior / 期待表现

1

**Comment by tengjiayan20** [comment]
In theory, it is ok.

**Comment by zRzRzRzRzRzRzR** [comment]
It is ok(Although I only tested in 2.2 later)

**Comment by badarrrr** [comment]
Thanks！
