### ISSUE TITLE
Share should be FALSE in gradio_web_demo.py

### ISSUE THREAD

**Issue by SoftologyPro** [THUDM/CogVideo#108]
### Feature request  / 功能建议

For security you should default the share to false in the gradio_web_demo.py script.
ie
`    demo.launch(server_name="127.0.0.1", server_port=7870, share=False)`

### Motivation / 动机

Makes it more secure.

### Your contribution / 您的贡献

N/A

**Comment by zRzRzRzRzRzRzR** [comment]
This is a demo for HF space and it need to set share=True(as default, not set this parm), you can changed it to false for your case
