### ISSUE TITLE
现在prompt是只支持英文吗？

### ISSUE THREAD

**Issue by badarrrr** [THUDM/CogVideo#114]
### System Info / 系統信息

/

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

/

### Expected behavior / 期待表现

/

**Comment by zRzRzRzRzRzRzR** [comment]
中文润色成英语，输入到模型的必须是英语
