### ISSUE TITLE
The videos in the finetuning dataset should have same resolution or not?

### ISSUE THREAD

**Issue by StarCycle** [THUDM/CogVideo#117]
Hi @zRzRzRzRzRzRzR @tengjiayan20.

![图片](https://github.com/user-attachments/assets/d685a499-ff2a-4287-a26d-63202ad6d580)

The videos for finetuning should be in 720p, or they can be any resolution?

For example, some videos are in 1080p, some are 480p, some are 730p. Is it possible?

**Comment by tengjiayan20** [comment]
The fine-tuning dataset has no restrictions on the resolution and duration of the video. Our processing code will handle it flexibly.

**Comment by StarCycle** [comment]
Nice!
