### ISSUE TITLE
About height/width_interpolation.

### ISSUE THREAD

**Issue by YTEP-ZHI** [THUDM/CogVideo#118]
@zRzRzRzRzRzRzR   Thank you for open-sourcing the great work! I was wondering what is the meaning of height/width_interpolation? 

https://github.com/THUDM/CogVideo/blob/1727f0646e16c14e5398702b1e6bd6c360e92ec0/sat/configs/cogvideox_2b_sft.yaml#L119-L120

https://github.com/THUDM/CogVideo/blob/1727f0646e16c14e5398702b1e6bd6c360e92ec0/sat/dit_video_concat.py#L84-L85

**Comment by tengjiayan20** [comment]
This comes from the interpolation of the sinusoidal position embedding during our progressive training.

**Comment by YTEP-ZHI** [comment]
@tengjiayan20  Thanks for your feedback, but I'm still a bit confused. It seems that you are using the traditional sin-cos positional embedding, for interpolation from a smaller resolution to a larger resolution, shouldn't it be directly interpolated on the size of the positional grids like this?
https://github.com/baaivision/EVA/blob/5623d08bb08a8268c7bc18e1d9b8b4bd651fe4d9/EVA-CLIP/rei/training/interpolate_patch14_224to336.py#L28
<img width="745" alt="image" src="https://github.com/user-attachments/assets/0aa45008-bd4c-45dc-8516-8e05c7ee93bf">

Why are you dividing the height/width_interpolation here?
https://github.com/THUDM/CogVideo/blob/1727f0646e16c14e5398702b1e6bd6c360e92ec0/sat/dit_video_concat.py#L84-L85

**Comment by YTEP-ZHI** [comment]
I understand now. The two implementations are functionally the same. Thank you.

**Comment by hadipash** [comment]
@zRzRzRzRzRzRzR @tengjiayan20 In the paper you mentioned that you preferred extrapolation over interpolation. However, in the code it seems to be the opposite.

**Comment by tengjiayan20** [comment]
> @zRzRzRzRzRzRzR @tengjiayan20 In the paper you mentioned that you preferred extrapolation over interpolation. However, in the code it seems to be the opposite.

In the paper, our view of interpolation or extrapolation is for rope. Here, the 2B model uses sinusoidal position embedding, so we choose interpolation. But for the better model, we choose rope and use extrapolation.
