### ISSUE TITLE
How to reproduce inference results through seeds？

### ISSUE THREAD

**Issue by kyrie111** [THUDM/CogVideo#123]
Dear Author, I infer the code using SAT weights and achieved very good results. Thank you for your work!
However, according to my experiments, I found that the same results can only be reproduced by following the generated sequence, For example, the contents of `test.txt` are as follows:
a cat is flying.
a cat is flying.
a cat is flying.  
After running `inference.sh`, I get three different results. Repeating the run also gives the same three different results as before. Could you please tell me if it's possible to reproduce the results by using a seed?

**Comment by tengjiayan20** [comment]
Fix the initial random noise will lead to same results

**Comment by kyrie111** [comment]
> Fix the initial random noise will lead to same results

thanks for ur reply, I got it done.
