### ISSUE TITLE
请问lora微调后的模型无法使用给出的脚本转换成diffusers格式，另外，是否会更新一版只保存lora模型而不是全部保存的版本

### ISSUE THREAD

**Issue by SCHfighting** [THUDM/CogVideo#126]
### System Info / 系統信息

无

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1

### Expected behavior / 期待表现

希望lora微调可以只保存lora参数

**Comment by tengjiayan20** [comment]
<img width="1142" alt="image" src="https://github.com/user-attachments/assets/902051ca-fe89-40c5-afe6-763a5a93eb84">

For only save lora parameters, you can modify SwissArmyTransformer/sat/training/model_io.py according to image above.

**Comment by tengjiayan20** [comment]
> <img alt="image" width="1142" src="https://private-user-images.githubusercontent.com/97726897/357497096-902051ca-fe89-40c5-afe6-763a5a93eb84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1OTc5ODEsIm5iZiI6MTcyNDU5NzY4MSwicGF0aCI6Ii85NzcyNjg5Ny8zNTc0OTcwOTYtOTAyMDUxY2EtZmU4OS00MGM1LWFmZTYtNzYzYTVhOTNlYjg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDE0NTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYjNlYmMyY2U0OTNiOTdlODU3MzY2NzJiNGU4NjgwNmJlMzNmMjViN2UyZTQ4YmY3MmVlMDg0YzNjMjQ4Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UdN9HfsVa1ToGgnEwNlKi-wzbUxf79ooA2Oq4W111ZM">
> For only save lora parameters, you can modify SwissArmyTransformer/sat/training/model_io.py according to image above.

But this method will drop dit transformer params weights in ckpt. You need to add origin params to new ckpt manually according to the names of lora model's weights, which have been changed when using lora.
