### ISSUE TITLE
About details for evaluation

### ISSUE THREAD

**Issue by DZY-irene** [THUDM/CogVideo#128]
Thanks for your wonderful work!
I have two questions about the evaluation:
1. if I want to directly utilize the pre-trained model for inference, do I need to do a prompt optimization before running cli_demo.py? I checked the pipe.encode_prompt function in cli_demo.py and it doesn't seem to do optimization.
2. When using VBench for evaluation, do you use a similar prompt optimization function for prompts from VBench?

**Comment by DZY-irene** [comment]
Thanks for your reply!
I also want to confirm that you use the SAT version for evaluation right?

**Comment by zRzRzRzRzRzRzR** [comment]
yes

**Comment by DZY-irene** [comment]
> yes

Thanks a lot!
