### ISSUE TITLE
I'm not sure if you can share some rough details about the training process of image to video?

### ISSUE THREAD

**Issue by trouble-maker007** [THUDM/CogVideo#135]
Could you please share a general training method for image to video, such as how to inject image conditions into the model? concat the image embedding with the text embedding or just replace the noise latent with the image embedding, or use mask strategy like open sora?

**Comment by hadipash** [comment]
> The image is passed through 3D VAE and concatenated with the noised input in the channel dimension.

Appendix A in the paper.

**Comment by trouble-maker007** [comment]
@hadipash Thank you very much, I apologize for not seeing the appendix.
