### ISSUE TITLE
Get "ValueError: Tensors must be contiguous" when trying to finetune on 1 GPU 

### ISSUE THREAD

**Issue by antbaez9** [THUDM/CogVideo#136]
### System Info / 系統信息

UBUNTU 22, CUDA 12
Python 3.10
A40 40 GB GPU

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Follow https://github.com/THUDM/CogVideo/blob/main/sat/README.md

run "bash finetune_single_gpu.sh" while in ~/CogVideo/sat/configs

full error:
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ubuntu/CogVideo/sat/train_video.py", line 226, in <module>
[rank0]:     training_main(
[rank0]:   File "/home/ubuntu/SwissArmyTransformer/sat/training/deepspeed_training.py", line 116, in training_main
[rank0]:     model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
[rank0]:   File "/home/ubuntu/SwissArmyTransformer/sat/training/deepspeed_training.py", line 225, in setup_model_untrainable_params_and_optimizer
[rank0]:     model, optimizer, _, _ = deepspeed.initialize(
[rank0]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/__init__.py", line 181, in initialize
[rank0]:     engine = DeepSpeedEngine(args=args,
[rank0]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 264, in __init__
[rank0]:     self._configure_distributed_model(model)
[rank0]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1192, in _configure_distributed_model
[rank0]:     self._broadcast_model()
[rank0]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1112, in _broadcast_model
[rank0]:     dist.broadcast(p.data, groups._get_broadcast_src_rank(), group=self.seq_data_parallel_group)
[rank0]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 117, in log_wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 224, in broadcast
[rank0]:     return cdb.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
[rank0]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 600, in _fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/comm/torch.py", line 200, in broadcast
[rank0]:     return torch.distributed.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
[rank0]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2209, in broadcast
[rank0]:     work = group.broadcast([tensor], opts)
[rank0]: ValueError: Tensors must be contiguous

### Expected behavior / 期待表现

The error happens while deepspeed is called using 'SATVideoDiffusionEngine' model. I would expect deepspeed to work without error.

**Comment by zRzRzRzRzRzRzR** [comment]
Please follow the instructions in the sat/README file to install T5 and its dependencies. We recently made an update, and this issue has been resolved. Thank you for your cooperation!
