### ISSUE TITLE
能否开源论文中提到的用于筛选低质量视频而训练的video-llama权重？

### ISSUE THREAD

**Issue by tangyipeng100** [THUDM/CogVideo#137]
### Feature request  / 功能建议

能否开源论文中提到的用于筛选低质量视频而训练的video-llama权重？

### Motivation / 动机

筛选低质量视频

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
暂时没有相关计划，不过，你可以使用我们的cogvlm video视频理解模型进行标注
