### ISSUE TITLE
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

### ISSUE THREAD

**Issue by dAItime001** [THUDM/CogVideo#138]
### System Info / 系統信息

运行streamlit run inference/streamlit_web_demo.py

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Loading pipeline components...:   0%|                                                             | 0/5 [00:00<?, ?it/s]The config attributes {'mid_block_add_attention': True} were passed to AutoencoderKLCogVideoX, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  5.72it/s]
Loading pipeline components...: 100%|█████████████████████████████████████████████████████| 5/5 [00:00<00:00,  5.13it/s]
2024-08-16 23:03:02.921 Uncaught app exception
Traceback (most recent call last):
  File "/root/anaconda3/envs/CogVideo/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 75, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/root/anaconda3/envs/CogVideo/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 574, in code_to_exec
    exec(code, module.__dict__)
  File "/opt/data/LLM/CogVideo/inference/streamlit_web_demo.py", line 216, in <module>
    main()
  File "/opt/data/LLM/CogVideo/inference/streamlit_web_demo.py", line 167, in main
    converted_prompt = convert_prompt(prompt=prompt, retry_times=1)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/data/LLM/CogVideo/inference/convert_demo.py", line 39, in convert_prompt
    client = OpenAI()
             ^^^^^^^^
  File "/root/anaconda3/envs/CogVideo/lib/python3.12/site-packages/openai/_client.py", line 105, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

inference/convert_demo.py 调用glm-4-0520 api 为何不用from zhipuai import ZhipuAI 而用from openai import OpenAI，没有填写OPENAI_API_KEY配置的位置？？？

from openai import OpenAI

def convert_prompt(prompt: str, retry_times: int = 3):
    """
    Convert a prompt to a format that can be used by the model for inference
    """

    client = OpenAI()

### Expected behavior / 期待表现

inference/convert_demo.py 调用glm-4-0520 api 为何不用from zhipuai import ZhipuAI 而用from openai import OpenAI，没有填写OPENAI_API_KEY配置的位置？？？

from openai import OpenAI

def convert_prompt(prompt: str, retry_times: int = 3):
    """
    Convert a prompt to a format that can be used by the model for inference
    """

    client = OpenAI()
    text = prompt.strip()

**Comment by zRzRzRzRzRzRzR** [comment]
在这个代码的顶端有英语的说名，要求从环境变量进行设置
