### ISSUE TITLE
Can you open source the CogVLM2-Caption weights mentioned in the paper

### ISSUE THREAD

**Issue by xishuxishu** [THUDM/CogVideo#140]
greate work!Can you open source the CogVLM2-Caption weights mentioned in the paper.

**Comment by huangshiyu13** [comment]
We may open-source in the future, so stay tuned.

**Comment by huangshiyu13** [comment]
CogVLM2-Caption is open-sourced. You can have a check here: https://github.com/THUDM/CogVideo/tree/main/tools/caption
