### ISSUE TITLE
训练代码具体啥时间会补充？

### ISSUE THREAD

**Issue by suimuc** [THUDM/CogVideo#141]
很不错的工作，我们目前想尝试以CogVideoX为基座进行微调，能否告知训练代码的具体开源时间，以及训练所需资源？

**Comment by zRzRzRzRzRzRzR** [comment]
微调代码一直都是开放的，全参数和lora都有sat的方案，资源均为安培以上GPU，建议使用48G以上显存的多卡集群微调

**Comment by suimuc** [comment]
哦好的，谢谢
