### ISSUE TITLE
对于训练代码的建议

### ISSUE THREAD

**Issue by libaolu312** [THUDM/CogVideo#144]
### Feature request  / 功能建议

非常感谢您的开源，请问是否可以开源一版diffuser的训练代码/finetuning代码，这将对未来的二次工作非常有帮助

### Motivation / 动机

对现在diffusion生态更好的开源建议

### Your contribution / 您的贡献

无  感谢您的开源

**Comment by zRzRzRzRzRzRzR** [comment]
我们之后会尝试用diffuser方案进行微调尝试，不过这需要一段时间，我们还在排期中

**Comment by libaolu312** [comment]
非常感谢，谢谢回复，希望早日见到diffuser版本的finetuning代码
