### ISSUE TITLE
Lora Fine Tuned Model outputs little to no difference

### ISSUE THREAD

**Issue by spacegoing** [THUDM/CogVideo#147]
### System Info / 系統信息

Cogvx

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Train model with Lora script. For inference I followed https://github.com/THUDM/CogVideo/issues/103

### Expected behavior / 期待表现

Fine-tune output sytle to customized dataset. Yet there are little difference observed:

https://github.com/user-attachments/assets/3c184094-eb12-426e-87a9-0397d4fdad1e

**Comment by zRzRzRzRzRzRzR** [comment]
Could you using our dev branch or may wait our update the new config of lora finetune. 
This configuration file provides more detailed settings. Additionally, we recommend that the total batch size for fine-tuning should not be less than 8 (our test configuration file was run on 8 A100 GPUs), resulting in a batch size of 16
