### ISSUE TITLE
Role of `cor_emb` in general conditioner

### ISSUE THREAD

**Issue by yjhong89** [THUDM/CogVideo#148]
Hi! 

General conditioner have `cor_emb` and `cor_p` options which not exist in function of stability-ai repo
- https://github.com/THUDM/CogVideo/blob/2825d9b707bb57c363e94a16e07015b052a2a27c/sat/sgm/modules/encoders/modules.py#L189
- What is role of it? (For classifier-free guidance ??) Make embeddings within batch randomly zero ?

Thanks!

**Comment by tengjiayan20** [comment]
This part of the code comes from the sdxl code repository. It is not used actually.

**Comment by yjhong89** [comment]
Thanks!
