### ISSUE TITLE
looping video

### ISSUE THREAD

**Issue by dribnet** [THUDM/CogVideo#149]
### Feature request  / 功能建议

Does anyone know if it is possible to force the video to loop seamlessly?

### Motivation / 动机

Would be a great feature for posting short videos

### Your contribution / 您的贡献

I might be able to implement this with some guidance would gladly contribute this back to the project.

**Comment by zRzRzRzRzRzRzR** [comment]
Could you describe it in more detail? Are you trying to extend the video by continuously generating 6-second segments and stitching them together into a longer video? :)

**Comment by dribnet** [comment]
Well - I meant something like this 😉

![trimmed](https://github.com/user-attachments/assets/b3fa4209-1371-487c-bd5c-16ac592c38a4)

If interested, I can try to clean this up a bit and submit it as a pull request as a pipeline option or maybe just a standalone demo using callback_on_step_end.

**Comment by zRzRzRzRzRzRzR** [comment]
That sounds interesting! Are you connecting the first and last frames of a video to create a 6-second looping animation? If so, I’d be happy to contribute a pull request (PR) as a tool! Looking forward to collaborating.

**Comment by screan** [comment]
> Well - I meant something like this 😉
> 
> ![trimmed](https://private-user-images.githubusercontent.com/945979/359490811-b3fa4209-1371-487c-bd5c-16ac592c38a4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTkzNTgsIm5iZiI6MTcyNTI1OTA1OCwicGF0aCI6Ii85NDU5NzkvMzU5NDkwODExLWIzZmE0MjA5LTEzNzEtNDg3Yy1iZDVjLTE2YWM1OTJjMzhhNC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQwNjM3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGQ1ZTFlMjJiYzdmNjFkYmUzMDcwYWZkN2Y4YTJhMmRlNmZiYTcwOTQzYmQ3NjcyODAyYTk3M2Q4YTBjYWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TCcCIy-L-ZY4Fg6Og9xNNnHBcWB_iaN_Zqbypz780cU) [ ![trimmed](https://private-user-images.githubusercontent.com/945979/359490811-b3fa4209-1371-487c-bd5c-16ac592c38a4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTkzNTgsIm5iZiI6MTcyNTI1OTA1OCwicGF0aCI6Ii85NDU5NzkvMzU5NDkwODExLWIzZmE0MjA5LTEzNzEtNDg3Yy1iZDVjLTE2YWM1OTJjMzhhNC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQwNjM3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGQ1ZTFlMjJiYzdmNjFkYmUzMDcwYWZkN2Y4YTJhMmRlNmZiYTcwOTQzYmQ3NjcyODAyYTk3M2Q4YTBjYWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TCcCIy-L-ZY4Fg6Og9xNNnHBcWB_iaN_Zqbypz780cU) ](https://private-user-images.githubusercontent.com/945979/359490811-b3fa4209-1371-487c-bd5c-16ac592c38a4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTkzNTgsIm5iZiI6MTcyNTI1OTA1OCwicGF0aCI6Ii85NDU5NzkvMzU5NDkwODExLWIzZmE0MjA5LTEzNzEtNDg3Yy1iZDVjLTE2YWM1OTJjMzhhNC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQwNjM3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGQ1ZTFlMjJiYzdmNjFkYmUzMDcwYWZkN2Y4YTJhMmRlNmZiYTcwOTQzYmQ3NjcyODAyYTk3M2Q4YTBjYWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TCcCIy-L-ZY4Fg6Og9xNNnHBcWB_iaN_Zqbypz780cU) [ ](https://private-user-images.githubusercontent.com/945979/359490811-b3fa4209-1371-487c-bd5c-16ac592c38a4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTkzNTgsIm5iZiI6MTcyNTI1OTA1OCwicGF0aCI6Ii85NDU5NzkvMzU5NDkwODExLWIzZmE0MjA5LTEzNzEtNDg3Yy1iZDVjLTE2YWM1OTJjMzhhNC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQwNjM3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGQ1ZTFlMjJiYzdmNjFkYmUzMDcwYWZkN2Y4YTJhMmRlNmZiYTcwOTQzYmQ3NjcyODAyYTk3M2Q4YTBjYWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TCcCIy-L-ZY4Fg6Og9xNNnHBcWB_iaN_Zqbypz780cU)
> 
> If interested, I can try to clean this up a bit and submit it as a pull request as a pipeline option or maybe just a standalone demo using callback_on_step_end.

looks great! came looking for the same

**Comment by dribnet** [comment]
> looks great! came looking for the same

Thanks - my version is a quick hack, but I cleaned it up a bit and pushed it to a [with_looping branch in my fork](https://github.com/dribnet/CogVideo/tree/with_looping) in case anyone wants to use it as a starting point. There's a utility called `cli_demo_loop.py` that will create videos that more or less match at the beginning and end. Here's a few examples:

`python cli_demo_loop.py --prompt "A couple are having dinner together."`
![with_loop_02g](https://github.com/user-attachments/assets/ead1cf53-bcac-4987-bead-3996c06f5878)

`python cli_demo_loop.py --prompt "A woman is running on the beach in the late afternoon."`
![with_loop_03g](https://github.com/user-attachments/assets/c65f8a65-1676-41b8-b0af-727a73f10517)

`python cli_demo_loop.py --prompt "A lion is drinking water."`
![with_loop_06g](https://github.com/user-attachments/assets/4b72c657-a703-4979-80aa-49355d99b918)

There's still some glitchiness at the seam and depending on the prompt you might get only an approximate match. For example:

`python cli_demo_loop.py --prompt "A man is skiing."`
![with_loop_04g](https://github.com/user-attachments/assets/ad0b7a6b-1cc1-421f-9a33-7a4be82624c2)

or it might not match at all and just insert a cut frame 🤷‍♂️

`python cli_demo_loop.py --prompt "Nightfall in a metropolis."`
![with_loop_05g](https://github.com/user-attachments/assets/f3d07b7b-4c5e-4842-adac-b668ebd60b33)


but when it does work it's pretty neat. I might come back to it and refine it or happy to discuss & improve it with anyone.

**Comment by rodjjo** [comment]
https://github.com/feizc/CogvideX-Interpolation/tree/main?tab=readme-ov-file
