### ISSUE TITLE
Did you use 3D-RoPE?

### ISSUE THREAD

**Issue by ProKSMT** [THUDM/CogVideo#153]
It seems that the code does not use 3D-RoPE mentioned in the paper, why?

**Comment by zRzRzRzRzRzRzR** [comment]
That is ues in 5B model and will release soon

**Comment by skeletonNN** [comment]
When open source the 5b model?

**Comment by zRzRzRzRzRzRzR** [comment]
Before Sep expect

**Comment by SanGilbert** [comment]
Just curious, I think the model will be better to adjust to different resolution if adding the 3D-RoPE? Is there any bad impact by adding it?
