### ISSUE TITLE
Model parallel

### ISSUE THREAD

**Issue by yjhong89** [THUDM/CogVideo#154]
Hi! 

When I try to model parallel (change this setting larger than 1),
- https://github.com/THUDM/CogVideo/blob/6a93ac614c7aae4fc00df36d36a87a52dcc93650/sat/configs/sft.yaml#L3

Following error occured
- https://github.com/THUDM/CogVideo/blob/6a93ac614c7aae4fc00df36d36a87a52dcc93650/sat/arguments.py#L184

Is that not supported yet ?? Or any plan to release this option??

Thanks!

**Comment by tengjiayan20** [comment]
The current mainstream frameworks such as deepspeed and megatron do not support the MP of the diffusion model well, because the shared parameters between MP ranks, such as adaLN, will cause inconsistent updates during training due to numerical precision.

**Comment by yjhong89** [comment]
Thanks!
