### ISSUE TITLE
How to training with multi-node gpus?

### ISSUE THREAD

**Issue by gxd1994** [THUDM/CogVideo#156]

**Comment by zRzRzRzRzRzRzR** [comment]
we provdie a multi gpus scripe, check here 

https://github.com/THUDM/CogVideo/blob/main/sat/finetune_multi_gpus.sh

**Comment by gxd1994** [comment]
> we provdie a multi gpus scripe, check here
> 
> https://github.com/THUDM/CogVideo/blob/main/sat/finetune_multi_gpus.sh

Maybe I didn't state the question clearly, I mean how to train model with multi node multi gpu?

**Comment by yzy-thu** [comment]
SAT supports multi-node training, you need to start script with slurm, mpi or torchrun and make sure the environment variables 'rank' and 'world_size' are set correctly.
