### ISSUE TITLE
有计划优化 VEnhancer 的显存占用吗

### ISSUE THREAD

**Issue by dmzlingyin** [THUDM/CogVideo#159]
### System Info / 系統信息

Ubuntu

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

降低显存占用

**Comment by zRzRzRzRzRzRzR** [comment]
这个需要去VEnhancer提一个issue，我们暂时没有这个计划，感谢
