### ISSUE TITLE
Details of sampler 

### ISSUE THREAD

**Issue by yjhong89** [THUDM/CogVideo#160]
Hi!

- cogvideo_2b.yaml uses VPSDEDPMP2MSampler, and wonder where this sampler comes from? (from Karras paper ?)
- Any plan to release rectified flow version ? (which is used on Open-Sora and Stable 3)

Thanks!

**Comment by tengjiayan20** [comment]
1. It is just a standard DPM++2M sampler.
2. From SD3's ablation study and our understanding of diffusion, we do not think flow matching objective is better than traditional diffusion objective.

**Comment by yjhong89** [comment]
Thanks!
