### ISSUE TITLE
关于VAE encode的时序tile问题 

### ISSUE THREAD

**Issue by bendanzzc** [THUDM/CogVideo#166]
@tengjiayan20 你好，之前咨询过关于 decode为了节省显存 所以使用for循环还在t维度tile decode的相关问题，那是否encode也可以用这个方法节省现存，按照论文里卷积kernel为3，所以是否encode的时候第一次输入13帧，后面依次输入12帧即可完成 对49帧的的图像编码
谢谢

**Comment by zRzRzRzRzRzRzR** [comment]
应该可以跟docode一样，不过第一帧是没用到的
