### ISSUE TITLE
训练速度超级慢，请问要怎么设置才会提速呢？

### ISSUE THREAD

**Issue by lith0613** [THUDM/CogVideo#167]
感谢开源代码！目前在A100训练，关掉gradient_checkpoint，frames设置为33，其它设置保持官方代码不变，在6卡并行训练的时候单个iteration耗时约24秒，但是GPU利用率持续保持在100%的状态，请问哪里有什么别的设置能提高训练速度吗？

**Comment by zRzRzRzRzRzRzR** [comment]
在的方案已经是比较高的速度了，目前暂时没有太多提速的方案，我们之后会尝试使用diffusers 和 PEFT框架进行微调，如果我们有更新方案，我们会第一时间更新。

**Comment by lith0613** [comment]
> 在的方案已经是比较高的速度了，目前暂时没有太多提速的方案，我们之后会尝试使用diffusers 和 PEFT框架进行微调，如果我们有更新方案，我们会第一时间更新。

感谢您的回复，请问我目前这个训练速度和你们自己训练的差异明显吗，你们自己训练大概是什么耗时呢

**Comment by bendanzzc** [comment]
我自己撸的 diffusers版本 720P 39frames 7s一个step，用了 zero-2 + int8 adamw，4张A100 bs=1*4 供参考

**Comment by tengjiayan20** [comment]
> 感谢开源代码！目前在A100训练，关掉gradient_checkpoint，frames设置为33，其它设置保持官方代码不变，在6卡并行训练的时候单个iteration耗时约24秒，但是GPU利用率持续保持在100%的状态，请问哪里有什么别的设置能提高训练速度吗？

每张卡的batch size多大

**Comment by lith0613** [comment]
> > 感谢开源代码！目前在A100训练，关掉gradient_checkpoint，frames设置为33，其它设置保持官方代码不变，在6卡并行训练的时候单个iteration耗时约24秒，但是GPU利用率持续保持在100%的状态，请问哪里有什么别的设置能提高训练速度吗？
> 
> 每张卡的batch size多大

只能1，超过就OOM了

**Comment by tengjiayan20** [comment]
> > > 感谢开源代码！目前在A100训练，关掉gradient_checkpoint，frames设置为33，其它设置保持官方代码不变，在6卡并行训练的时候单个iteration耗时约24秒，但是GPU利用率持续保持在100%的状态，请问哪里有什么别的设置能提高训练速度吗？
> > 
> > 
> > 每张卡的batch size多大
> 
> 只能1，超过就OOM了

确定gradient_accumulation_steps是1吗，以及分辨率是多大

**Comment by lith0613** [comment]
> > > > 感谢开源代码！目前在A100训练，关掉gradient_checkpoint，frames设置为33，其它设置保持官方代码不变，在6卡并行训练的时候单个iteration耗时约24秒，但是GPU利用率持续保持在100%的状态，请问哪里有什么别的设置能提高训练速度吗？
> > > 
> > > 
> > > 每张卡的batch size多大
> > 
> > 
> > 只能1，超过就OOM了
> 
> 确定gradient_accumulation_steps是1吗，以及分辨率是多大

分辨率是480*720，gradient_accumulation_steps是1，这些参数都是默认的，没有修改过，请问您那边训练是大概什么耗时呢，我刚又看了下是21秒左右，24是因为保存checkpoint花了些时间

**Comment by zRzRzRzRzRzRzR** [comment]
目前已经确定是数据载入的问题，这目前没有很好的解决方案，我们尝试使用硬件解码，但是并没有提升多少速度
