### ISSUE TITLE
Cannot Clone

### ISSUE THREAD

**Issue by BenClarkPersonal** [THUDM/CogVideo#168]
### System Info / 系統信息

C:\Users\bencl>git clone https://github.com/THUDM/CogVideo.git C:\Code\CogVideo
Cloning into 'C:\Code\CogVideo'...
remote: Enumerating objects: 687, done.
remote: Counting objects: 100% (252/252), done.
remote: Compressing objects: 100% (120/120), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 1344 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

C:\Users\bencl>git clone https://github.com/THUDM/CogVideo.git C:\Code\CogVideo
Cloning into 'C:\Code\CogVideo'...
remote: Enumerating objects: 687, done.
remote: Counting objects: 100% (252/252), done.
remote: Compressing objects: 100% (120/120), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 1344 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

### Expected behavior / 期待表现

Should clone

**Comment by zRzRzRzRzRzRzR** [comment]
This should have been interrupted when you cloned it, git lfs install needs to be installed
