### ISSUE TITLE
Finetune时GPU利用率波动很大

### ISSUE THREAD

**Issue by hanshumin001** [THUDM/CogVideo#172]
### System Info / 系統信息

A100/官方配置环境

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

直接运行

### Expected behavior / 期待表现

希望GPU利用率稳定。有时候GPU 23G，有时候70G+利用率。

**Comment by zRzRzRzRzRzRzR** [comment]
70G在训练，23G在验证

**Comment by lith0613** [comment]
> 70G在训练，23G在验证

但是我的程序不做验证的时候依然波动很大，感觉不是因为程序在做验证的问题，这个代码里面有什么别的设置导致的显存波动吗，希望能持续维持最大显存，这样避免有其他程序插入导致训练OOM
