### ISSUE TITLE
I get this error: Repository Not Found for url: https://huggingface.co/api/models/THUDM/CogVideoX-5b. Is CogVideoX-5b not open sourced?

### ISSUE THREAD

**Issue by SamitM1** [THUDM/CogVideo#174]
### System Info / 系統信息

When running the following code which i got from the official Diffusers [Github](https://github.com/huggingface/diffusers/blob/main/docs/source/en/api/pipelines/cogvideox.md), which states that:

There are two models available that can be used with the CogVideoX pipeline:

[THUDM/CogVideoX-2b](https://huggingface.co/THUDM/CogVideoX-2b)
[THUDM/CogVideoX-5b](https://huggingface.co/THUDM/CogVideoX-5b)

```
import torch
from diffusers import CogVideoXPipeline
from diffusers.utils import export_to_video

pipe = CogVideoXPipeline.from_pretrained("THUDM/CogVideoX-5b").to("cuda")
```

I get the following error when i run the code above:

```
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Couldn't connect to the Hub: 401 Client Error. (Request ID: Root=1-66ccda44-4ad8d0340c57e3de2ef72472;02e029d2-a309-4f35-be66-b6a1cc146a52)

Repository Not Found for url: https://huggingface.co/api/models/THUDM/CogVideoX-5b.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password..
Will try to load from local cache.
```

Is CogVideoX-5b not open sourced? If not, approximately when will it be released/open-sourced?

Thanks in advance! 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. !git clone https://github.com/THUDM/CogVideo.git
2. !pip install -r CogVideo/requirements.txt
3.
```
import torch
from diffusers import CogVideoXPipeline
from diffusers.utils import export_to_video

pipe = CogVideoXPipeline.from_pretrained("THUDM/CogVideoX-5b").to("cuda")
```

### Expected behavior / 期待表现

I expected it download the model similar to how it downloads CogVideoX-2b:

<img width="958" alt="Screen Shot 2024-08-26 at 12 53 26 PM" src="https://github.com/user-attachments/assets/02440f68-bb19-4404-8561-edd1e48ad8bc">

**Comment by johnwick123f** [comment]
@SamitM1 CogVideoX-5b is not released yet. They are going to release it a bit later I believe.

**Comment by Weifeng-Chen** [comment]
when will the 5b model be released ?

**Comment by zRzRzRzRzRzRzR** [comment]
Now release
