### ISSUE TITLE
Img2Img

### ISSUE THREAD

**Issue by Alx-AI** [THUDM/CogVideo#185]
### Feature request  / 功能建议

Is it possible to create a transition from one image to another with CogVideoX?
Similar to https://github.com/Vchitect/SEINE

### Motivation / 动机

CogX seems good enough to serve as a general transition tool which could drastically speed up the ability to automatically cut together videos 

### Your contribution / 您的贡献

only have the idea unfortunately

**Comment by zRzRzRzRzRzRzR** [comment]
My understanding is that you want to make a transition between two videos, with the input and output corresponding to the last frame of the first video and the first frame of the next video, respectively

**Comment by Alx-AI** [comment]
Corrwct

**Comment by zRzRzRzRzRzRzR** [comment]
Given this, a good suggestion would be to fine-tune the model for downstream tasks. This would require some changes to the model structure, but not much, as it's for a downstream task.

We recommend using Diffusers-like models and adding the corresponding modules yourself to experiment. Currently, we don't have the resources to focus on downstream tasks, so we appreciate your understanding.
