### ISSUE TITLE
Inference with CogX-5B

### ISSUE THREAD

**Issue by GFENGG** [THUDM/CogVideo#187]
### System Info / 系統信息

Linux cuda12.1

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

run gradio demo,and the result is
<img width="644" alt="image" src="https://github.com/user-attachments/assets/ad116641-2cf2-4fce-9fe2-dd7f0ad6881d">

and i have tried opencv and imageio, 

### Expected behavior / 期待表现

why? and how to fix it? thanks

**Comment by GFENGG** [comment]
if i use moviepy, the result is:
<img width="697" alt="image" src="https://github.com/user-attachments/assets/a7862c0f-a8e2-4df6-a574-5123255438df">

**Comment by zRzRzRzRzRzRzR** [comment]
update the diffusers lib

**Comment by GFENGG** [comment]
> update the diffusers lib

Thanks for your reply, my diffusers is updated to 0.30.1, and the issue is the same.

**Comment by GFENGG** [comment]
> update the diffusers lib

Thanks

**Comment by shm4771** [comment]
If anyone else is facing the same issue, this issue arises from some problem in video exporting logic. No need to change diffusers lib, just write your logic for saving pil images as video
