### ISSUE TITLE
cli_demo.py里，2b模型直接运行，换成5b模型报错

### ISSUE THREAD

**Issue by henbucuoshanghai** [THUDM/CogVideo#189]
### System Info / 系統信息

    pipe = CogVideoXPipeline.from_pretrained(model_path, torch_dtype=dtype)

diffusers/models/modeling_utils.py", line 774, in from_pretrained
    accelerate.load_checkpoint_and_dispatch(
TypeError: load_checkpoint_and_dispatch() got an unexpected keyword argument 'strict'

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1

### Expected behavior / 期待表现

运行

**Comment by zixian-wu** [comment]
the same Issue
![image](https://github.com/user-attachments/assets/f94a4a82-e9fd-4a25-beb2-c44965c89015)

**Comment by zRzRzRzRzRzRzR** [comment]
The 2B model needs to be loaded using fp16 and for 5b need to update the diffusers lib to 0.30.1.
the cli demo have updated, please check the comment in code

**Comment by zixian-wu** [comment]
I re-run pip install -r requirements.txt&& pip install diffusers==0.30.1, video can be generated normally with 5B model

**Comment by caozhenxiang-kouji** [comment]
I changed the diffusers version to 0.30.1 but the problem still exists, what now?

**Comment by caozhenxiang-kouji** [comment]
Well, it seems that https://github.com/black-forest-labs/flux/issues/134#issuecomment-2328148028 solves my problem
