### ISSUE TITLE
Why did the scale factor change?

### ISSUE THREAD

**Issue by Blueskyvvvvv** [THUDM/CogVideo#190]
### Feature request  / 功能建议

Excellent work! I have a few questions about the parameter details. The VAE used for both the 5B model and the 2B model remains unchanged, but why did the scale factor change from 1.15 to 0.7?
<img width="1030" alt="image" src="https://github.com/user-attachments/assets/be815446-9682-415c-a5b4-f9aad75c628e">

### Motivation / 动机

Having doubts about the “scale factor” parameter

### Your contribution / 您的贡献

None

**Comment by tengjiayan20** [comment]
Frankly speaking, we think scale factor is more like an empirical parameter, although it was originally proposed to normalize the variance of latent.
Essentially, the scale factor adjusts the relative degree of the video and the noise. So we change it empirically.

**Comment by Blueskyvvvvv** [comment]
Is the selection criterion related to the distribution of the training data, or what does the empirical selection depend on?

**Comment by tengjiayan20** [comment]
Depends only on the observed generation results. And we find that small changes do not have a big impact

**Comment by tengjiayan20** [comment]
The difference between 1.15 and 0.7 is not that big. The original intention of scale_factor is to change the standard deviation of latent to 1, so it is 1/std. The average std of latent generated by our vae is around 1.15. We fluctuate the scale_factor based on experience.
As for the SVD of only 0.18, it is because they use a different vae than us.

**Comment by yjhong89** [comment]
- Thanks for letting me know!
- As you said, controlling scale factor wouldn't be an impact (or even worse)

**Comment by Blueskyvvvvv** [comment]
Thank you for your answer, I think I get it now.
