### ISSUE TITLE
API支持图像和文本一起输入，CogVideoX-5B什么时候可以支持呢？

### ISSUE THREAD

**Issue by XHB-ZMM** [THUDM/CogVideo#191]
### Feature request  / 功能建议

可以支持图像和文本一起输入吗

### Motivation / 动机

图像和文本一起输入，生成视频，可能更符合用户的需求

### Your contribution / 您的贡献

...

**Comment by zRzRzRzRzRzRzR** [comment]
你的内容和 #182 相似，我们已经收到您的诉求，我们会评估和讨论后决定相应的计划。
目前，暂时无排期

**Comment by zRzRzRzRzRzRzR** [comment]
重复#182，已关闭并保留 #182
