### ISSUE TITLE
tiled encode on AutoencoderKLCogVideoX from Diffusers

### ISSUE THREAD

**Issue by xesdiny** [THUDM/CogVideo#198]
### Feature request  / 功能建议

From [zRzRzRzRzRzRzR/diffusers](https://github.com/zRzRzRzRzRzRzR/diffusers/tree/main) commit
Only the decoded tiles are segmented. Consider improving GPU efficiency by directly loading the vae.encoder.sampler results during the training process. After completing the ImagePix encoding in the offline process, train again. It is found that using a longer frame 3D encoding cache memory consumes too much. So that it cannot fulfill expectations.

### Motivation / 动机

Encode longer videos.

### Your contribution / 您的贡献

None

**Comment by zRzRzRzRzRzRzR** [comment]
If the VAE encoder is added, the memory usage for a single run should be around 71G, because the VAE does not perform the aforementioned operations. During the training phase (if using SAT), you can use fakecp to optimize in a manner similar to the decoder.

**Comment by xesdiny** [comment]
> fakecp

`_FakeCPConvolutionPassFromPreviousRank`?

**Comment by zRzRzRzRzRzRzR** [comment]
是的

def fake_cp_pass_from_previous_rank(input_, dim, kernel_size, cache_padding):
    return _FakeCPConvolutionPassFromPreviousRank.apply(input_, dim, kernel_size, cache_padding)
