### ISSUE TITLE
Finetune时GPU利用率波动很大

### ISSUE THREAD

**Issue by lith0613** [THUDM/CogVideo#199]
不做验证的时候纯训练，显存波动特别大，sft模式下从20多G到接近80G，波动范围特别大，这个有什么设置能解决吗，希望能持续保持在最大显存占用，尝试过关掉checkpoint_activations也还是会动态变化。

**Comment by zRzRzRzRzRzRzR** [comment]
因为你是多卡zero_2的状态，然后80G是正常的，20G因该是在读数据和传输吧，这时候没有激活模型的训练部分，只是load状态

**Comment by lith0613** [comment]
> 因为你是多卡zero_2的状态，然后80G是正常的，20G因该是在读数据和传输吧，这时候没有激活模型的训练部分，只是load状态

请问有什么设置可以让显存一直维持固定的数值吗，正常训练其它模型应该是不会变化的

**Comment by yzy-thu** [comment]
先确认下数据读取没有卡住训练？
