### ISSUE TITLE
When will the code release?

### ISSUE THREAD

**Issue by yhw-yhw** [THUDM/CogVideo#2]

**Comment by wenyihong** [comment]
The code and model will be released in the near future :) Also, a demo API is under development. 
We are currently cleaning up the code to make it simple to reproduce.

**Comment by zhoudaquan** [comment]
Great work! Is there any update on the code release schedule?

**Comment by begumcitamak** [comment]
Do you have a deadline for sharing the code?

**Comment by wenyihong** [comment]
The code has been released. Have fun!
