### ISSUE TITLE
pip install -r requirements.txt 安装依赖一直失败

### ISSUE THREAD

**Issue by jian27com** [THUDM/CogVideo#200]
Python 3.10.14  conda环境下 安装 pip install -r requirements.txt

一直提示

 Using cached https://mirrors.aliyun.com/pypi/packages/13/14/5cde975724b07a70ef6cf58cf15efe8505c7c4dbf0a3d9e6ef36adc48775/deepspeed-0.15.0.tar.gz (1.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      test.c
      LINK : fatal error LNK1181: 无法打开输入文件“aio.lib”
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\tmp\pip-install-3jsy6hks\deepspeed_3dd6e707adcd4245a3c858446a4672e5\setup.py", line 187, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Users\tmp\pip-install-3jsy6hks\deepspeed_3dd6e707adcd4245a3c858446a4672e5\setup.py", line 56, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      DS_BUILD_OPS=1
       [WARNING]  One can disable async_io with DS_BUILD_AIO=0
       [ERROR]  Unable to pre-compile async_io
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

这是什么原因导致的？python 版本我也换过，但是还是不行。 感谢回复

**Comment by zRzRzRzRzRzRzR** [comment]
因为你是windows，ds要在linux装

**Comment by jian27com** [comment]
那怎么在windows下安装上？

**Comment by zRzRzRzRzRzRzR** [comment]
如果你不微调，就不装ds就行了，微调必须在Linux，或者你能找到能兼容windows的ds也可以

**Comment by jian27com** [comment]
感谢回复 明白了
