### ISSUE TITLE
Fail to download SAT 5B model 

### ISSUE THREAD

**Issue by DZY-irene** [THUDM/CogVideo#203]
<img width="1000" alt="1724918133435" src="https://github.com/user-attachments/assets/50df3a03-7b0d-4128-ad43-9be40aabc916">

I also tried downloading CogVideoX-5B-transformer.tar.gz in file 1, but it cannot be unzipped correctly. Could you provide a way to get 5B transformer model for SAT? Thank you so much.

**Comment by zRzRzRzRzRzRzR** [comment]
Do not package it into a zip file; instead, you should directly download this file. Click on the "1" folder and download the tar.gz file.

**Comment by DZY-irene** [comment]
When I tried to extract this tar.gz file, it threw an error: 
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

My command is tar -xzvf transformer.tar.gz

**Comment by zRzRzRzRzRzRzR** [comment]
Exiting now because you already have duplicate files, the correct way to download is
1. Download latest separately
2. Open 1 and download that tar.gz separately.
Tsinghua Cloud Disk cannot transfer content larger than 10G, so we compressed it into tar.gz.
Try downloading it this way. I have already tried it and this problem does not occur. Make sure your tar.gz file is 9.7G before extraction and 11G after extraction.

**Comment by peki12345** [comment]
> Exiting now because you already have duplicate files, the correct way to download is
> 
> 1. Download latest separately
> 2. Open 1 and download that tar.gz separately.
>    Tsinghua Cloud Disk cannot transfer content larger than 10G, so we compressed it into tar.gz.
>    Try downloading it this way. I have already tried it and this problem does not occur. Make sure your tar.gz file is 9.7G before extraction and 11G after extraction.

关于第2步，我就是这样下载的，但是每次下载到一半都会报网络错误。

**Comment by zRzRzRzRzRzRzR** [comment]
超时还是其他原因，我用的wget能正常下载

**Comment by peki12345** [comment]
> 超时还是其他原因，我用的wget能正常下载

提示的网络错误，我是直接点的下载按钮，我试试wget

**Comment by zRzRzRzRzRzRzR** [comment]
单个文件很大，我直接下载文件是在一个网速比较快的环境下载的，大概 20MB/s，没有测试过慢速的时候会不会中断

**Comment by cyandddd** [comment]
![image](https://github.com/user-attachments/assets/0cbd70f7-2ddc-4855-ab51-48221d39bd1c)
我在google colab里下的，感觉不对啊，不是9个g那个

**Comment by Eurus-Holmes** [comment]
this could be working 
`curl -L -o transformer.tar.gz "https://cloud.tsinghua.edu.cn/d/fcef5b3904294a6885e5/files/?p=%2F1%2FCogVideoX-5B-transformer.tar.gz&dl=1"`
