### ISSUE TITLE
Use case demonstration on single 3090ti

### ISSUE THREAD

**Issue by Omarch47** [THUDM/CogVideo#207]
I wanted to test the cogvideo 2b and 5b models and compare their results with the same prompt. The only other experimenting I have done with locally run video generation was opensora a few months back and the difference is mind-blowing. Not only is this far more computationally efficient, but the generations are much, much higher quality. The repo talks about polishing the prompts with AI to get more detail and I have to say that it makes a large impact on the final result. The prompt adherence was fairly impressive and this is really bringing me a lot of excitement for the future of this tech in terms of offline, non subscription based options for video generation. Thanks devs!

Here is a link to the results: https://youtu.be/MFLEQmvugKI

**Comment by zRzRzRzRzRzRzR** [comment]
Thank you so much for your support and feedback! We’re thrilled to hear that you had a positive experience testing CogVideoX, especially regarding the improvements in computational efficiency and generation quality. We’re also excited about the future potential of this technology, particularly in providing high-quality video generation offline without subscriptions. Your shared results and experiences mean a lot to us, and we’re eager to see more of your creative work. Thanks again for your support!
