### ISSUE TITLE
VAE时序恢复不能和原视频保持一致

### ISSUE THREAD

**Issue by bendanzzc** [THUDM/CogVideo#212]
你好，我尝试用cli_vae_demo 重建视频，但发现重建之后的视频一卡一卡的
使用的diffusers==0.30.1
最新补充：我用0.30.0尝试没有问题
原视频：

https://github.com/user-attachments/assets/f80ea85f-5818-4e09-af9b-c88cbf5261f4

重建之后的视频

https://github.com/user-attachments/assets/3e6cd46a-f533-478f-9494-eadcf2876a54

请问是否是我哪里没操作正确

**Comment by zRzRzRzRzRzRzR** [comment]
You can respond to the issue by acknowledging that the logic for 2 * i + 1, 2 * i + 3 in the decode_video function is no longer needed, as it has been integrated into the Diffusers’ autoencoder. This change simplifies the implementation of tiled decoding, as the previous logic was part of the pipeline. You can refer to the specific changes in the Diffusers repository [here](https://github.com/huggingface/diffusers/blob/1d4d71875b495a5322f85bef2e99ac2bfa802e7a/src/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py#L1116).

for cli_vae_demo we will update asap
