### ISSUE TITLE
[Ask] BF16 vs FP16

### ISSUE THREAD

**Issue by yjhong89** [THUDM/CogVideo#217]
Hi!

- 5b model uses bf16 but 2b model uses fp16.
- Why 2b and 5b model use different dtype ??
- If I gonna finetune 5b model, do I need to use bf16 mode ??

Thanks!

**Comment by zRzRzRzRzRzRzR** [comment]
The 2B model uses FP16 for training, and the 5B model uses BF16 for training. If you fine-tune the 5B model, be sure to use bf16 for fine-tuning

**Comment by yjhong89** [comment]
Thanks! 
- Then why 2B model uses FP16 and 5B model uses BF16 separately? Any reason for this ?

**Comment by zRzRzRzRzRzRzR** [comment]
We all want to use BF16, but this might not be feasible for inference on weaker devices. For the 2B model, we want to achieve more compatibility, especially for earlier generations of GPU devices that do not support BF16.
If the FP16 inference is used for the BF16 model, the performance decreases, so we directly trained a 2B FP16 model during training, allowing more developers to use it.

However, the precision expressed by FP16 is limited, and training 5B cannot succeed

So we 5B insisted on using BF16

**Comment by yjhong89** [comment]
Thanks for detailed answer!
