### ISSUE TITLE
Computation Requirement to train CogVideo

### ISSUE THREAD

**Issue by g1910** [THUDM/CogVideo#22]
Hi,

First of all, great work in developing CogVideo. Could you please provide information on how many GPUs and how much duration it took to train the model?

Thanks
Gaurav

**Comment by wenyihong** [comment]
We use 13*8 A100 to train the model. The two stages were trained for ~100k iterations in total, which took ~20 days.

**Comment by xfguo-ucas** [comment]
> 

How much GPU memory and how much duration it took to infer the model? I have a RTX3090Ti, but OOM occurred.

**Comment by anish-yadav94** [comment]
Great work!
Could you please help me with below issue?
How much GPU memory is required for Inferencing? With a 15 GB GPU, I tried it, but a runtime problem appeared.

**Comment by wenyihong** [comment]
It takes around 25GB GPU memory to inference with batchsize=1 (on our A100).

**Comment by wenyihong** [comment]
> 

hi, what's the runtime problem?
