### ISSUE TITLE
请问是否有可能仅基于图片训练CogVideo的风格Lora？

### ISSUE THREAD

**Issue by GallenShao** [THUDM/CogVideo#226]
在社区使用中，除了图生视频，风格训练也是比较重要的一个场景，但目前风格资源更多是图片，而没什么视频，是否有可能通过图片来训练视频模型的Lora？该怎么做？

**Comment by SCHfighting** [comment]
同问

**Comment by zRzRzRzRzRzRzR** [comment]
没有，因为这个模型不是图生视频，所以输入一定是文字

**Comment by schhaohao** [comment]
> 没有，因为这个模型不是图生视频，所以输入一定是文字

他的意思是用image data训练视频，而不一定必须是video da ta

**Comment by zRzRzRzRzRzRzR** [comment]
也不行，输入一定是文字 226个token之内，输出一定是720 * 480

**Comment by GallenShao** [comment]
为啥close了呀，我觉得我问题表述没有问题……我是希望用图文对数据训练CogVideo这个视频模型的Lora，如果我强行用图片组装成视频训练效果会比较差（比如生成的视频是静态的），是否有什么别的好办法？

**Comment by schhaohao** [comment]
> 为啥close了呀，我觉得我问题表述没有问题……我是希望用图文对数据训练CogVideo这个视频模型的Lora，如果我强行用图片组装成视频训练效果会比较差（比如生成的视频是静态的），是否有什么别的好办法？

我也觉得，同想知道怎么用image data训练视频lora

**Comment by schhaohao** [comment]
> 为啥close了呀，我觉得我问题表述没有问题……我是希望用图文对数据训练CogVideo这个视频模型的Lora，如果我强行用图片组装成视频训练效果会比较差（比如生成的视频是静态的），是否有什么别的好办法？

请问您解决了吗，怎么使用图片进行训练。Dit架构是可以支持图片训练的，他们原文中也介绍了说图片和视频进行联合训练，我感觉是官方没有放出图片训练的方法和脚本
