### ISSUE TITLE
How to encode a tensor with a time dimension size of 1 using the provided 3D-VAE

### ISSUE THREAD

**Issue by mm-diff** [THUDM/CogVideo#227]
Amazing work！
How to encode a tensor with a time dimension size of 1（i.e., image tensor) using the provided 3D-VAE. 
For example, when I use VAE to encode a tensor of size (1, 3, 1, 480, 720)(B, C, T, H, W), the following error occurs:

Error: Calculated padded input size per channel: (1 x 482 x 722). Kernel size: (3 x 3 x 3). Kernel size can't be greater than actual input size

**Comment by shiyi-zh0408** [comment]
Hi! I encountered the same issue when training images. How did you resolve it?
