### ISSUE TITLE
How use ema model for inference

### ISSUE THREAD

**Issue by yjhong89** [THUDM/CogVideo#229]
Hi!

When I do fine-tunining, step and step-ema model automatically saved.
- https://github.com/THUDM/SwissArmyTransformer/blob/b68c4460b9fa2b5312be49a1da152986c6351262/sat/training/model_io.py#L166

But inference don't use ema model. Is there any way to use ema model ? (Since I'm not still familiar with SwissArmyTransformer)
- Or inference with ema model has no effect ?

**Comment by tengjiayan20** [comment]
You can change the name of the ema directory, for example, change 1000-ema to 1000, and the sat load logic will automatically load the directory name written in the latest file.

**Comment by yjhong89** [comment]
Thanks!

**Comment by antragoudaras** [comment]
@tengjiayan20 The weights provided [in this link](https://cloud.tsinghua.edu.cn/d/fcef5b3904294a6885e5/?p=%2F1&mode=list) are the EMA ones or the non-EMA (standard) ones? In general the are limited information and I found out that the EMA are better to be used for evaluation https://github.com/THUDM/SwissArmyTransformer/issues/180#issuecomment-2283446434. 

What would you suggest one using for fine-tuning your model in multiple fine-tuning stages?
