### ISSUE TITLE
期盼diffusers版脚本的第n天

### ISSUE THREAD

**Issue by SCHfighting** [THUDM/CogVideo#230]
### Feature request  / 功能建议

渴望贵公司早日发布diffusers版的脚本

### Motivation / 动机

大一统

### Your contribution / 您的贡献

push一下

**Comment by zRzRzRzRzRzRzR** [comment]
说的是微调吗，推理早就通了

**Comment by SHYuanBest** [comment]
微调大概啥时候可以出脚本，sat可太难用了

**Comment by glide-the** [comment]
+1

**Comment by zRzRzRzRzRzRzR** [comment]
已经在PR了
 https://github.com/huggingface/diffusers/pull/9302
