### ISSUE TITLE
Compute resources used to train CogVideoX

### ISSUE THREAD

**Issue by michal-stary** [THUDM/CogVideo#231]
Hey, can you share details on how much compute was used to train the CogVideoX models?

**Comment by zRzRzRzRzRzRzR** [comment]
> 100,000 GPU hours of H100 as told in X before

**Comment by yzhang2016** [comment]
> More than 100,000 GPU hours of H100 as told in X before

What are the batchsize and training iterations?

**Comment by zRzRzRzRzRzRzR** [comment]
These are limited by the company's requirements, and we are not at liberty to disclose them directly. However, I believe you can estimate based on the data I mentioned; the batch size must be greater than 1024, preferably above 2048.
