### ISSUE TITLE
pipe.vae.enable_slicing() 用了为什么现场还需要50多G

### ISSUE THREAD

**Issue by lonngxiang** [THUDM/CogVideo#232]
### System Info / 系統信息

https://colab.research.google.com/drive/14TTaDTM3_lk69qKb5u4-1_gm_YK6lM3m?usp=sharing  代码版本

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

https://colab.research.google.com/drive/14TTaDTM3_lk69qKb5u4-1_gm_YK6lM3m?usp=sharing  代码

### Expected behavior / 期待表现

正常运行

**Comment by zRzRzRzRzRzRzR** [comment]
请按照issue置顶的方案解决
