### ISSUE TITLE
训练后convert_weight_sat2hf保存的ckpt再直接用diffusers载入，出视频会变糊？

### ISSUE THREAD

**Issue by GallenShao** [THUDM/CogVideo#236]
### System Info / 系統信息

5b模型有这个问题，2b好像没有

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. 全量训练
2. 用convert_weight_sat2hf脚本转换ckpt
3. 用pipe = CogVideoXPipeline.from_pretrained(model_path, torch_dtype=torch.bfloat16).to("cuda")载入模型并推理即可复现
4. 改成以下载入方式效果正常：
transformer = CogVideoXTransformer3DModel.from_pretrained(f'{model_path}/transformer', torch_dtype=torch.bfloat16, use_safetensors=False)
pipe = CogVideoXPipeline.from_pretrained('THUDM/CogVideoX-5b', transformer=transformer, torch_dtype=torch.bfloat16, use_safetensors=False).to("cuda")

根据表现，疑似vae在保存过程中丢失精度？

### Expected behavior / 期待表现

期望convert_weight_sat2hf转换后直接用CogVideoXPipeline.from_pretrained载入即可使用

**Comment by peki12345** [comment]
请问你是如何用convert_weight_sat2hf脚本转换ckpt的，我2b是可以转的，5b会报错。我似乎该修改某些层的通道配置？但我不知道在哪里修改
<img width="1190" alt="image" src="https://github.com/user-attachments/assets/cdecc435-6cea-42e0-9f1b-e9f70ab3159c">

**Comment by GallenShao** [comment]
<img width="690" alt="image" src="https://github.com/user-attachments/assets/5172b281-e22f-46eb-9aa0-51a74486d8fa">
我这里稍微改了下

**Comment by zRzRzRzRzRzRzR** [comment]
> 请问你是如何用convert_weight_sat2hf脚本转换ckpt的，我2b是可以转的，5b会报错。我似乎该修改某些层的通道配置？但我不知道在哪里修改 <img alt="image" width="1190" src="https://private-user-images.githubusercontent.com/92427482/364190662-cdecc435-6cea-42e0-9f1b-e9f70ab3159c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDk0NzEsIm5iZiI6MTcyNTQ0OTE3MSwicGF0aCI6Ii85MjQyNzQ4Mi8zNjQxOTA2NjItY2RlY2M0MzUtNmNlYS00MmUwLTlmMWItZTlmNzBhYjMxNTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDExMjYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ODk2OTBlZDExZTAwYmRlMmUzNzgxYTFjZTI0MGZlNjg1MTkzOGY2MjllMzc1OWZlYjZkNzA3ZDZiMjk0ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ytH__xDpoVM_J6gt-woCDKGcp1iNmF0zssSQ8_y2lk">

这个我们之后更新，转换脚本已经升级了，适配了diffusers 0.30.1

**Comment by peki12345** [comment]
> > 请问你是如何用convert_weight_sat2hf脚本转换ckpt的，我2b是可以转的，5b会报错。我似乎该修改某些层的通道配置？但我不知道在哪里修改 <img alt="image" width="1190" src="https://private-user-images.githubusercontent.com/92427482/364190662-cdecc435-6cea-42e0-9f1b-e9f70ab3159c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDk0NzEsIm5iZiI6MTcyNTQ0OTE3MSwicGF0aCI6Ii85MjQyNzQ4Mi8zNjQxOTA2NjItY2RlY2M0MzUtNmNlYS00MmUwLTlmMWItZTlmNzBhYjMxNTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDExMjYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ODk2OTBlZDExZTAwYmRlMmUzNzgxYTFjZTI0MGZlNjg1MTkzOGY2MjllMzc1OWZlYjZkNzA3ZDZiMjk0ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ytH__xDpoVM_J6gt-woCDKGcp1iNmF0zssSQ8_y2lk">
> 
> 这个我们之后更新，转换脚本已经升级了，适配了diffusers 0.30.1

期待更新！

**Comment by peki12345** [comment]
> <img alt="image" width="690" src="https://private-user-images.githubusercontent.com/12490086/364205926-5172b281-e22f-46eb-9aa0-51a74486d8fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MDAwMTgsIm5iZiI6MTcyNTQ5OTcxOCwicGF0aCI6Ii8xMjQ5MDA4Ni8zNjQyMDU5MjYtNTE3MmIyODEtZTIyZi00NmViLTlhYTAtNTFhNzQ0ODZkOGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDAxMjgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1YzU5MDM4NmFjODFiZmVhYThkM2E3NjRkYWU5MjM1NjEwYWVmY2M1YjQ2ODFlNjQ2MmQ4ZGRjMGU2ZDgyMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.beLAT5Ju9_QCsol0t1793eay5Mu6GvsaaglXswh_X_s"> 我这里稍微改了下

感谢，我用你的修改成功转好了模型，同样遇到了视频变模糊的问题。但我认为这个不是vae导致的，5b模型的vae和2b模型应该没有不同，我更倾向于transformer finetune崩了，但具体原因不清楚，loss也很正常...

**Comment by GallenShao** [comment]
> > <img alt="image" width="690" src="https://private-user-images.githubusercontent.com/12490086/364205926-5172b281-e22f-46eb-9aa0-51a74486d8fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MDAwMTgsIm5iZiI6MTcyNTQ5OTcxOCwicGF0aCI6Ii8xMjQ5MDA4Ni8zNjQyMDU5MjYtNTE3MmIyODEtZTIyZi00NmViLTlhYTAtNTFhNzQ0ODZkOGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDAxMjgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1YzU5MDM4NmFjODFiZmVhYThkM2E3NjRkYWU5MjM1NjEwYWVmY2M1YjQ2ODFlNjQ2MmQ4ZGRjMGU2ZDgyMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.beLAT5Ju9_QCsol0t1793eay5Mu6GvsaaglXswh_X_s"> 我这里稍微改了下
> 
> 感谢，我用你的修改成功转好了模型，同样遇到了视频变模糊的问题。但我认为这个不是vae导致的，5b模型的vae和2b模型应该没有不同，我更倾向于transformer finetune崩了，但具体原因不清楚，loss也很正常...

但正如我提到的，换了一种载入方式后，正常了。。。是否是vae也只是我的猜测，我没做进一步实验，其实可以试试分别载入各个部分做个对照看

**Comment by zRzRzRzRzRzRzR** [comment]
使用现在的代码呢？vae应该是不会动的啊

**Comment by linwenzhao1** [comment]
> 感谢，我用你的修改成功转好了模型，同样遇到了视频变模糊的问题。但我认为这个不是vae导致的，5b模型的vae和2b模型应该没有不同，我更倾向于transformer finetune崩了，但具体原因不清楚，loss也很正常...

你好，问下你用的是Cogvideo-5b lora微调后的模型（pt格式）吗？我遇到下面这个问题了：
RuntimeError: Error(s) in loading state_dict for CogVideoXTransformer3DModel:
	Missing key(s) in state_dict: "transformer_blocks.0.attn1.to_q.weight", "transformer_blocks.0.attn1.to_q.bias",

**Comment by linwenzhao1** [comment]
> <img alt="image" width="690" src="https://private-user-images.githubusercontent.com/12490086/364205926-5172b281-e22f-46eb-9aa0-51a74486d8fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MjE5MTMsIm5iZiI6MTczNTUyMTYxMywicGF0aCI6Ii8xMjQ5MDA4Ni8zNjQyMDU5MjYtNTE3MmIyODEtZTIyZi00NmViLTlhYTAtNTFhNzQ0ODZkOGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDAxMjAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNjJlYjdiMTc3ZWNiZTFkYjg4OTM2YTk1OWM2NDRjYTdlZDhhOGJhODE5Y2NjODFjYWRjYzBiMDhhYzg0YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sE207JZW13f4GS-Y0Mz8J6TQnRDzSH5PBAa2cNTJE94"> 我这里稍微改了下

你好，问下你用的是Cogvideo-5b lora微调后的模型（pt格式）吗？有遇过下面问题吗
RuntimeError: Error(s) in loading state_dict for CogVideoXTransformer3DModel:
	Missing key(s) in state_dict: "transformer_blocks.0.attn1.to_q.weight", "transformer_blocks.0.attn1.to_q.bias",

**Comment by linwenzhao1** [comment]
> ### System Info / 系統信息
> 5b模型有这个问题，2b好像没有
> 
> ### Information / 问题信息
> * [ ]  The official example scripts / 官方的示例脚本
> * [x]  My own modified scripts / 我自己修改的脚本和任务
> 
> ### Reproduction / 复现过程
> 1. 全量训练
> 2. 用convert_weight_sat2hf脚本转换ckpt
> 3. 用pipe = CogVideoXPipeline.from_pretrained(model_path, torch_dtype=torch.bfloat16).to("cuda")载入模型并推理即可复现
> 4. 改成以下载入方式效果正常：
>    transformer = CogVideoXTransformer3DModel.from_pretrained(f'{model_path}/transformer', torch_dtype=torch.bfloat16, use_safetensors=False)
>    pipe = CogVideoXPipeline.from_pretrained('THUDM/CogVideoX-5b', transformer=transformer, torch_dtype=torch.bfloat16, use_safetensors=False).to("cuda")
> 
> 根据表现，疑似vae在保存过程中丢失精度？
> 
> ### Expected behavior / 期待表现
> 期望convert_weight_sat2hf转换后直接用CogVideoXPipeline.from_pretrained载入即可使用

>    transformer = CogVideoXTransformer3DModel.from_pretrained(f'{model_path}/transformer', torch_dtype=torch.bfloat16, use_safetensors=False)
>    pipe = CogVideoXPipeline.from_pretrained('THUDM/CogVideoX-5b', transformer=transformer, torch_dtype=torch.bfloat16, use_safetensors=False).to("cuda")
这个命令加载不起来吧， 保存的文件格式safetensors？
