### ISSUE TITLE
为什么生成的视频经常是动画风格？Why are generated videos often animated?

### ISSUE THREAD

**Issue by Bellzs** [THUDM/CogVideo#237]
I am using Comfyui with cogvideoX-Wrapper node to generate video，the prompt is 'A monkey and a tiger are driving a roadster,realistic style.'，however，the result is anime style. the model I use is CogVideo 5B
I expect the video is realistic style, could you give me a favor?
![微信图片_20240903224959](https://github.com/user-attachments/assets/f7d417a1-bd55-48d1-8fae-18cb6e82bcf8)

**Comment by zRzRzRzRzRzRzR** [comment]
I believe you need refine the prompt, as mentioned in the convert_demo.py from the repository. Here’s an example:

“In a scene that defies reality, a realistic portrayal unfolds of a monkey, donning a classic driver’s cap and goggles, at the wheel of a sleek, red roadster. Beside him, a majestic tiger, with its striking stripes and a pair of aviator sunglasses, sits coolly in the passenger seat. The unlikely duo cruises down an open coastal highway, the wind ruffling their fur as the sun casts a golden glow over the horizon. The level of detail in their fur, the shine of the car’s paint, and the realistic scenery around them bring an extraordinary sense of realism to this whimsical and captivating tableau.”

I believe this approach can more effectively solve your problem.

**Comment by Bellzs** [comment]
> I believe you need refine the prompt, as mentioned in the convert_demo.py from the repository. Here’s an example:
> 
> “In a scene that defies reality, a realistic portrayal unfolds of a monkey, donning a classic driver’s cap and goggles, at the wheel of a sleek, red roadster. Beside him, a majestic tiger, with its striking stripes and a pair of aviator sunglasses, sits coolly in the passenger seat. The unlikely duo cruises down an open coastal highway, the wind ruffling their fur as the sun casts a golden glow over the horizon. The level of detail in their fur, the shine of the car’s paint, and the realistic scenery around them bring an extraordinary sense of realism to this whimsical and captivating tableau.”
> 
> I believe this approach can more effectively solve your problem.

it worked, thanks for your help! I understand how to write prompt.

**Comment by loretoparisi** [comment]
> a

Supposed I would like to do the opposite i.e. using an **anime** style or let's say a **cinematic** style, what is the guidance?
