### ISSUE TITLE
Inference but no memory/VRAM using in GPU

### ISSUE THREAD

**Issue by Zctoylm0927** [THUDM/CogVideo#238]
### System Info / 系統信息

cuda 11.8, A800, pytorch 2.4

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

python inference/cli_demo.py --prompt  "xxx"

### Expected behavior / 期待表现

I turn off all of the four options during the inference because I think A800 80G(the text-encode and transformer is about 20G) is enough and get the minimum latency.  But it takes me 50 minutes to finish one step and no VRAM using.

![屏幕截图(3)](https://github.com/user-attachments/assets/d67a1f95-e5bb-4db4-ae80-d9cf68aedf68)

When I added the following according to #197 , it takes about 20 seconds to finish one step.

```
pipe.enable_model_cpu_offload()
pipe.vae_enable_tiling()
```

If I want to load all the model to GPU, what should I do? thx

**Comment by tonney007** [comment]
请问解决了么？同样使用a800，CUDA12.4 尝试了上述的所有，都没有解决。
![1725617909361](https://github.com/user-attachments/assets/f03ebf25-0675-4050-a1dc-a73cae7d8602)

**Comment by tonney007** [comment]
把scheduling_ddim_cogvideox.py中改一下prev_timestep = int(prev_timestep.to('cpu').item())可以解决~

**Comment by Zctoylm0927** [comment]
> remove all of these two code and then pipe.to("cuda")

 I have made it.
