### ISSUE TITLE
训练2B和5B除了模型参数和shift-scale有区别，还有别的地方有区别嘛

### ISSUE THREAD

**Issue by bendanzzc** [THUDM/CogVideo#240]
你好，感谢你们开源强大的T2V模型，为开源社区带来强大的pretrain模型。我想请教下训练2B和5B的时候，除了训练精度、模型参数、vae的scale和sampler的shift-scale有区别外，别的地方有区别嘛，我训练2B没问题，但是5B崩掉了，不知道原因在哪，谢谢

**Comment by tengjiayan20** [comment]
崩掉具体是指？

**Comment by bendanzzc** [comment]
> 崩掉具体是指？

不好意思，自己的问题，已解决，谢谢及时反馈
