### ISSUE TITLE
请问是否可以微调text encoder，因为做图片lo ra的时候也有给text encoder加上lo ra的

### ISSUE THREAD

**Issue by schhaohao** [THUDM/CogVideo#242]
### Feature request  / 功能建议

1

### Motivation / 动机

1

### Your contribution / 您的贡献

1

**Comment by zRzRzRzRzRzRzR** [comment]
微调T5似乎没必要吧
T5和VAE通常都是不动的，改动了需要的资源都不是按照单台GPU服务器算的
