### ISSUE TITLE
何时可以解耦lora模型和base模型

### ISSUE THREAD

**Issue by schhaohao** [THUDM/CogVideo#243]
### Feature request  / 功能建议

解耦lora模型和base模型，单独保存和加载lo ra模型，就像diffusers中

### Motivation / 动机

1

### Your contribution / 您的贡献

1

**Comment by zRzRzRzRzRzRzR** [comment]
还在做，没成功，相关PR可以在diffuser中查看

**Comment by zRzRzRzRzRzRzR** [comment]
已经完成，可以在sat的readme中看到怎么合并

**Comment by schhaohao** [comment]
> 已经完成，可以在sat的readme中看到怎么合并
已经完成了吗，还没有看到
