### ISSUE TITLE
do you guys have a plan about 10B model

### ISSUE THREAD

**Issue by codeplay0000** [THUDM/CogVideo#247]
thanks for your awesome work, do you have a plan to train a 10B or even larger model?

**Comment by zRzRzRzRzRzRzR** [comment]
Not at the moment. Currently, we are all working on video generation models that are under 10B in size.

**Comment by codeplay0000** [comment]
> Not at the moment. Currently, we are all working on video generation models that are under 10B in size.

larger than 5B?

**Comment by zRzRzRzRzRzRzR** [comment]
Still the 5B model, currently I am rushing to complete the preparation work for the open-source of the I2V model

**Comment by codeplay0000** [comment]
> Still the 5B model, currently I am rushing to complete the preparation work for the open-source of the I2V model

really excited and looking forward the i2v model release. btw, what kind of solution you choose to implement the i2v model, 've tried the mask inpainting way (like opensora's i2v ),  look like it works:。
https://github.com/user-attachments/assets/d0af3128-6672-4fa5-92a6-42c8a67a25c0
https://github.com/user-attachments/assets/24a36081-3010-418f-abc3-ddc3e75126c9

**Comment by zRzRzRzRzRzRzR** [comment]
You can check solutions similar to SVD, where the input channels are doubled for processing image embeddings
