### ISSUE TITLE
Question regarding classifier free guidance

### ISSUE THREAD

**Issue by xvjiarui** [THUDM/CogVideo#255]
Hi CogVideo Team,

Thanks for open-sourcing this great codebase with fine-tuning code.

While I am checking the details, I have a maybe dumb question. I found while we are training, we didn't randomly drop the text condition with e.g. 10% probability for classifier free guidance training. May I ask the reason or did I miss something?

**Comment by tengjiayan20** [comment]
<img width="788" alt="image" src="https://github.com/user-attachments/assets/30306c02-d23a-4496-b12d-f097bcec556a">
This hyper-parameter is set to drop text condition.

**Comment by xvjiarui** [comment]
Thank you so much!
