### ISSUE TITLE
什么时候可以支持lora权重的单独保存与加载，现在的finetune，每回保存整个模型太占空间了

### ISSUE THREAD

**Issue by schhaohao** [THUDM/CogVideo#265]
### Feature request  / 功能建议

lora权重的单独保存与加载

### Motivation / 动机

finetune保存整个模型太占空间

### Your contribution / 您的贡献

1

**Comment by glide-the** [comment]
hf的工作正在进行。

**Comment by zRzRzRzRzRzRzR** [comment]
我们正在做这个工作，一旦完成，我们会更新到readme
