### ISSUE TITLE
DynamicCFG timesteps seems not correct in SAT version

### ISSUE THREAD

**Issue by mhh0318** [THUDM/CogVideo#267]
### System Info / 系統信息

CUDA == 12.4
Python==3.10.14
PyTorch==2.4.0
Diffusers == 0.30.1

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

#258 

Follow all instructions inference 2B model. 

https://github.com/THUDM/CogVideo/blob/354c906f8160084bbdf1f1c42b3b292d509fe24b/sat/sgm/modules/diffusionmodules/sampling.py#L518

here `self.num_steps` is actual inference step (e.g. 50) but `timestep` in [0,1000].  

### Expected behavior / 期待表现

The output should be positive number related to the current timesteps as Diffusers implementation.

**Comment by tengjiayan20** [comment]
This is a coincidence. We found that the wave-like cfg schedule can have the advantages of high cfg while avoiding overexposure.

**Comment by mhh0318** [comment]
Thanks for the explanation. I just realized both versions are aligned.
