### ISSUE TITLE
What are the prompts of "运镜方式" from website "https://chatglm.cn/video"?

### ISSUE THREAD

**Issue by Endrother** [THUDM/CogVideo#269]
Thank you very much for your work. There is a setting named "运镜方式" on your official website "清影-AI生视频", what are the additional prompts added to model if I choose it? For instance, the original prompt I input is "a dog in hat is sleeping", when I choose "推进" of "运镜方式", the prompt turns to "a dog in hat is sleeping **with camera zooming in**" or another one?

**Comment by zRzRzRzRzRzRzR** [comment]
Yes, translate directly into English, because open-source models do not support Chinese, just follow the understanding of English
