### ISSUE TITLE
Make a new demo on Hugging Face

### ISSUE THREAD

**Issue by refreshedcyberjohn** [THUDM/CogVideo#27]
So the old CogVideo space on Hugging Face was removed. I'm not using Replicate because I need a credit card to continue. Please, make a new demo on CogVideo.

**Comment by wenyihong** [comment]
Hi, thanks for the suggestion! The old demo was temporally removed because of computational resources issues, and we will recover it as soon as we can

**Comment by refreshedcyberjohn** [comment]
Okay.
