### ISSUE TITLE
video with more then 6 seconds 

### ISSUE THREAD

**Issue by issam1975** [THUDM/CogVideo#274]
i want to generate 360° orbit camera animation in order to use it in 3d gaussian splatting app .

can cogvideo genrate such  videos  since it may have more than 6 seconds in length .

thanks .

**Comment by zRzRzRzRzRzRzR** [comment]
Cannot, but currently the diffuser provides a method for video2video continuation, and there is also a release, which might be helpful to you
https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/cogvideo/pipeline_cogvideox_video2video.py
