### ISSUE TITLE
new finetune code report error

### ISSUE THREAD

**Issue by zyssyz123** [THUDM/CogVideo#277]
### System Info / 系統信息

1 H00 Gpu 单卡训练

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1

### Expected behavior / 期待表现

自从更新了代码，我用相同的数据集finetune 。
https://github.com/THUDM/CogVideo/blob/dcb82ae30b454ab898aeced0633172d75dbd55b8/sat/data_video.py#L405
报错 IndexError: index 144 is out of bounds for dimension 0 with size 144。

dcb82ae30b454ab898aeced0633172d75dbd55b8 这个版本之后我就会报错，不知道为什么

**Comment by zRzRzRzRzRzRzR** [comment]
能给出具体报错信息吗，我现在能work

**Comment by lishiyuwhu** [comment]
我这边是个偶然报错, 看看你是不是第一个视频固定报错了. 我暂时是拿try跳过了, 中秋过后再查

**Comment by zyssyz123** [comment]
应该是数据集的问题，我改了代码就解决了

**Comment by mercywang111** [comment]
> 应该是数据集的问题，我改了代码就解决了

请问改了什么代码？我遇到了相同的问题

**Comment by zyssyz123** [comment]
看下报错位置的代码是什么，我不知道我是不是和你在同一个位置报错
