### ISSUE TITLE
How to use Rank and Local_Rank

### ISSUE THREAD

**Issue by zyssyz123** [THUDM/CogVideo#278]
### System Info / 系統信息

1

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1

### Expected behavior / 期待表现

比如我的机器有8张卡，我想指定编号7 做 single GPU finetune 这里要怎么设置
https://github.com/THUDM/CogVideo/blob/main/sat/finetune_single_gpu.sh#L5

**Comment by zRzRzRzRzRzRzR** [comment]
echo "RUN on `hostname`, CUDA_VISIBLE_DEVICES=7
