### ISSUE TITLE
连接校园网无法打开清华云盘

### ISSUE THREAD

**Issue by schhaohao** [THUDM/CogVideo#284]
### System Info / 系統信息

1

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1

### Expected behavior / 期待表现

1

**Comment by zRzRzRzRzRzRzR** [comment]
如果使用流量等可以，那大概率是校园网屏蔽了
