### ISSUE TITLE
I2V model PT seems corrupt

### ISSUE THREAD

**Issue by phr00t** [THUDM/CogVideo#291]
### System Info / 系統信息

transformers-4.43.3
Windows 11 x64

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Download the PT seen here, URL provided in GitHub comments:

https://cloud.tsinghua.edu.cn/d/5cc62a2d6e7d45c0a2f6/?p=%2F1&mode=list

... try to load it in PyTorch:

  model = torch.load(model_path)
An error occurred: PytorchStreamReader failed reading zip archive: failed finding central directory

### Expected behavior / 期待表现

Correctly loading the PyTorch file.

**Comment by zRzRzRzRzRzRzR** [comment]
We have not yet released the I2V model, it is expected to be released this month, and the final preparations for the model are underway

**Comment by rodjjo** [comment]
If you run this on ubuntu, you maybe you fix it:

`zip -FF mp_rank_00_model_states.pth --out not_corrupted.pth`

as pt/pth is a zip file.

**Comment by xvjiarui** [comment]
Hi @zRzRzRzRzRzRzR 

Great job on releasing I2V model! Is there any plan on updating the I2V model download link for SAT?

**Comment by zRzRzRzRzRzRzR** [comment]
https://cloud.tsinghua.edu.cn/d/5cc62a2d6e7d45c0a2f6/?p=%2F1&mode=list here

**Comment by xvjiarui** [comment]
Hi @zRzRzRzRzRzRzR 
Thanks for your prompt reply. I just tried this file, it still raise "RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory"

**Comment by runzeer** [comment]
@zRzRzRzRzRzRzR
It seemed the link
https://cloud.tsinghua.edu.cn/d/5cc62a2d6e7d45c0a2f6/?p=%2F1&mode=list  
has not been refreshed. It seemed that the model weights is 5 days ago. And the weights can not be loaded by pytorch.

**Comment by zRzRzRzRzRzRzR** [comment]
I discovered this issue, and my colleague is handling it. It should be resolved within 12 hours. In the worst case, we will re-upload the model and update the link. Please keep an eye on this issue, and we will update as soon as possible

The diffusers version can be used normally

**Comment by zRzRzRzRzRzRzR** [comment]
will it work now? upload again

**Comment by hanshumin001** [comment]
hi, When I use the latest version model，there still are some errors. 

[rank0]: RuntimeError: Given groups=1, weight of size [3072, 32, 2, 2], expected input[26, 16, 60, 90] to have 32 channels, but got 16 channels instead.

**Comment by zRzRzRzRzRzRzR** [comment]
did you change infer yaml with 
```
args:
  image2video: True # True for image2video, False for text2video
  latent_channels: 16
```
This config need to changed for CogVideoX-5B-I2V

**Comment by xvjiarui** [comment]
> will it work now? upload again

It works! Thank you!
