### ISSUE TITLE
THUDM/CogVideoX-5b-I2V not found

### ISSUE THREAD

**Issue by SoftologyPro** [THUDM/CogVideo#293]
### System Info / 系統信息

CUDA 12, Windows 11, Python 3.10.8

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

I am running the latest cli_demo.py under Windows.
T2V works fine.
Trying I2V I pass in  `--model_path "THUDM/CogVideoX-5b-I2V"`
and get the error
```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/THUDM/CogVideoX-5b-I2V
OSError: Cannot load model THUDM/CogVideoX-5b-I2V: model is not cached locally and an error occurred while trying to fetch metadata from the Hub. Please check out the root cause in the stacktrace above.
```
What model path do I need to use for I2V?

### Expected behavior / 期待表现

I expect it to not crash :)

**Comment by zRzRzRzRzRzRzR** [comment]
September open source, not yet currently

**Comment by SoftologyPro** [comment]
How can I change cli_demo to use the pt i2v model from here?
https://cloud.tsinghua.edu.cn/d/5cc62a2d6e7d45c0a2f6/?p=%2F1&mode=list
