### ISSUE TITLE
Video doesn't play

### ISSUE THREAD

**Issue by supersonic71** [THUDM/CogVideo#3]
Hey, the first video in the page doesn't seem to work

**Comment by melMass** [comment]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/7041726/171214507-f2fc9424-01c1-4256-86a4-886bc1b2feec.png">

**Comment by wenyihong** [comment]
How about trying another browser?

**Comment by woctezuma** [comment]
It does not work in Firefox 🔥 🦊 , but it works in Microsoft Edge.

**Comment by tom-doerr** [comment]
Also doesn't work in Brave and Chrome
