### ISSUE TITLE
Image to video ending frame option

### ISSUE THREAD

**Issue by rodjjo** [THUDM/CogVideo#300]
### Feature request  / 功能建议

Is it possible to use a ending frame optionally?

By combining two videos one with starting frame , other with endframe we could create a seamless loop if the end and starting frame are the same 

### Motivation / 动机

Allow to create seamless loops

### Your contribution / 您的贡献

*

**Comment by rodjjo** [comment]
It looks like there is a support in another similar project [CogVideoX-Fun at comfyui_nodes.py](https://github.com/aigc-apps/CogVideoX-Fun/blob/main/comfyui/comfyui_nodes.py#L276)

**Comment by sam598** [comment]
@zRzRzRzRzRzRzR Is there any more information on what was changed? How do you add both the start frame and end frame?

**Comment by rodjjo** [comment]
@sam598 another person implemented this: https://github.com/feizc/CogvideX-Interpolation/tree/main?tab=readme-ov-file
