### ISSUE TITLE
Smart VRAM Management

### ISSUE THREAD

**Issue by realisticdreamer114514** [THUDM/CogVideo#301]
### Feature request  / 功能建议

I noticed if I have all the VRAM optimization options on, it uses ~3.3GB of the VRAM regardless of my total VRAM (6GB), GPU usage is never ~85% (safe level for image generation tasks). Can it detect my available VRAM and adjust its usage so it can be maximized? 

### Motivation / 动机

50 min to generate a video

**Comment by zRzRzRzRzRzRzR** [comment]
Not too feasible, because if this line of offload is omitted, it will definitely exceed 6GB, which the 2060 cannot handle, so cpu_offload must be used, and it should even be cpu_sequence_offload
