### ISSUE TITLE
The V2V and The I2V model has opened? when to update the finetune readme and the code for the v2v and i2v model

### ISSUE THREAD

**Issue by guiyuanyuanbao** [THUDM/CogVideo#302]
### Feature request  / 功能建议

The V2V and The I2V model has opened? when to update the finetune readme and the code for the v2v and i2v model

### Motivation / 动机

The V2V and The I2V model has opened? when to update the finetune readme and the code for the v2v and i2v model

### Your contribution / 您的贡献

The V2V and The I2V model has opened? when to update the finetune readme and the code for the v2v and i2v model

**Comment by zRzRzRzRzRzRzR** [comment]
V2V is the same as T2V and I2V is different please check our readme
