### ISSUE TITLE
About the noised_image_all_concat

### ISSUE THREAD

**Issue by WangFeng18** [THUDM/CogVideo#305]
Hi, Thanks a lot for the amazing work. I am curious about your i2v setting, it seems the default training way for i2v is just cat image at the first frame and I found you leave a interface named noised_image_all_concat which is set to False default. So my problem is that if the current cat way is better than setting the noised_image_all_concat to True, and what the differences of the i2v models trained under these two settings. 
Thanks again!

**Comment by tengjiayan20** [comment]
You can just have a try. We can not conclude which one is better.
