### ISSUE TITLE
CogVideoX-5B-I2V diffusers finetune support

### ISSUE THREAD

**Issue by JonathanLi19** [THUDM/CogVideo#306]
### Feature request  / 功能建议

CogVideoX-5B-I2V diffusers finetune suppor release

### Motivation / 动机

Hi , Great work! I want to ask when will CogVideoX-5B-I2V diffusers finetune support be released?

### Your contribution / 您的贡献

None

**Comment by zRzRzRzRzRzRzR** [comment]
We are still experimenting, and it will definitely OOM at the moment, unable to fine-tune on an 8-card H100 device, we are working on it

**Comment by chenshuo20** [comment]
Thank you for your excellent work! I wanted to check if there are any updates about the I2V diffuser fine-tuning?
