### ISSUE TITLE
run scripts, no error,no result

### ISSUE THREAD

**Issue by ayew22** [THUDM/CogVideo#31]
![image](https://user-images.githubusercontent.com/106938762/220089759-13b662ca-bec7-4089-a6c9-edc37a2cc72d.png)

I did't know why

**Comment by ayew22** [comment]
./scripts/inference_cogvideo_pipeline.sh: line 38: 99675 Killed   

just this

**Comment by wqf321** [comment]
I got the same problem with you. Have you sloved it?

**Comment by wenyihong** [comment]
Hi, what's your GPU memory?

**Comment by suxuanya** [comment]
> 你好，请问你的GPU显存是多少？

16G 是不是显存不足都会这样 但是我用nvidia-smi显示GPU只占用了2MB top命令显示CPU占用100% 每次都是在这一句话之后kill进程
![image](https://github.com/THUDM/CogVideo/assets/130747112/432eafd8-1b8b-4893-aaa7-e20710d2ce59)

**Comment by Louis2099** [comment]
v100 32G GPU memory, also got process killed problem.
Yet I could successfully load stage1, and stage2 models, but got killed when loading cogview2-dsr model every time.
