### ISSUE TITLE
Why is Maximum Prompt Length 226?

### ISSUE THREAD

**Issue by Yuancheng-Xu** [THUDM/CogVideo#310]
For T5, the input length is 512. Is there a reason why the Maximum Prompt Length is 226 in CogVideoX?

**Comment by tengjiayan20** [comment]
There is no special meaning. Just a medium length.

**Comment by Yuancheng-Xu** [comment]
[Here](https://github.com/THUDM/CogVideo#model-introduction) it says that "Maximum Prompt Length" is 226. Just to make sure, is it true that in fact the medium of all the training prompt lengths is 226? So we can use, for example, 300 tokens text prompts on this model?

**Comment by zRzRzRzRzRzRzR** [comment]
In theory, this should be feasible, and you can also try to expand the prompt words to 512 (the upper limit length of T5) during training

**Comment by tengjiayan20** [comment]
> [Here](https://github.com/THUDM/CogVideo#model-introduction) it says that "Maximum Prompt Length" is 226. Just to make sure, is it true that in fact the medium of all the training prompt lengths is 226? So we can use, for example, 300 tokens text prompts on this model?

When we training, we just padding all text prompt to the length of 226.
