### ISSUE TITLE
finetune 的时候我要如何知道每个epoch处理了多少数据

### ISSUE THREAD

**Issue by zyssyz123** [THUDM/CogVideo#313]
### System Info / 系統信息

finetune 的时候我要如何知道每个epoch处理了多少数据

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

finetune 的时候我要如何知道每个epoch处理了多少数据

### Expected behavior / 期待表现

finetune 的时候我要如何知道每个epoch处理了多少数据

**Comment by zRzRzRzRzRzRzR** [comment]
每个epoch就是你数据集的大小，但是这里是step， 每个step 每个卡一个数据（bs =1）
