### ISSUE TITLE
Can cogvlm2-llama3-caption generate Chinese caption?

### ISSUE THREAD

**Issue by MinliangLin** [THUDM/CogVideo#319]
### Feature request  / 功能建议

Can cogvlm2-llama3-caption generate Chinese caption? If no, is it possible to fine tune a Chinese captioning model with low cost, i.e. 20~60 GPU hours?

### Motivation / 动机

I want to generate Chinese caption for a huge dataset using cogvlm2-llama3-caption.

### Your contribution / 您的贡献

N/A

**Comment by huangshiyu13** [comment]
CogVLM2-Caption can not generate Chinese captions. You can finetune your own Chinese caption model using SWIFT: https://github.com/modelscope/ms-swift/blob/main/docs/source_en/Multi-Modal/cogvlm2-video-best-practice.md

**Comment by huangshiyu13** [comment]
We released GLM-4V-Plus-0111 beta, which can generate better video captions. Find more here: https://bigmodel.cn/dev/api/normal-model/glm-4v
