### ISSUE TITLE
install on google free colab,  Killed  when building InferenceModel_Sequential model

### ISSUE THREAD

**Issue by ayew22** [THUDM/CogVideo#32]
all log in 
https://colab.research.google.com/drive/13oB5IP54VzlNM9Tzyuv9Un_vOBZNWT77

env :
GPU     Tesla T4    15360MiB
cuda    11.6
torch   1.13.1+cu116

already update  
--batch-size 1 \
--max-inference-batch-size 1 \

![image](https://user-images.githubusercontent.com/106938762/221085730-62f666dd-40c6-417f-b4bd-9380751e95ca.png)

**Comment by ayew22** [comment]
And I guess

![image](https://user-images.githubusercontent.com/106938762/221086188-3b394532-a411-4b26-8ae4-423c56daa55e.png)

**Comment by wenyihong** [comment]
Hi, It takes around 25GB GPU memory to inference with batchsize=1 (on our A100). I'm afraid that GPU Tesla T4 15360MiB do not have enough GPU memory.
