### ISSUE TITLE
Load LoRA for diffusers test

### ISSUE THREAD

**Issue by wenqsun** [THUDM/CogVideo#320]
### System Info / 系統信息

Thanks for your great effort!
Now I can convert the Lora weight from SAT to diffusers version. However, I found that I cannot load the Lora weight as you have provided in cli_demo.py below:
![image](https://github.com/user-attachments/assets/6db17f2d-b52e-4f5d-903b-464ee97bbbfd)

The error is AttributeError: 'CogVideoXPipeline' object has no attribute 'load_lora_weights'. It seems that the Lora part has not been merged into the CogVideoXPipeline in diffusers. Is it still an ongoing work? My diffusers version is 0.30.3.

Thanks for your reply!

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

The loading weight of Lora in the provided code does not work.

### Expected behavior / 期待表现

Reply to the Lora loading process.

**Comment by a-r-r-o-w** [comment]
> My diffusers version is 0.30.3.

LoRA support was not part of the 0.30.3 release. It will be part of the 0.31.0 release in the future. For now, it's best to install from `diffusers:main` which does contain lora loading support

**Comment by wenqsun** [comment]
Thanks for your help! I will check that!
