### ISSUE TITLE
Discord invite link has expired

### ISSUE THREAD

**Issue by ameasure** [THUDM/CogVideo#321]
### System Info / 系統信息

Chrome browser

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Click the Discord invite link in the GitHub README: https://discord.gg/Qqjtj69f

### Expected behavior / 期待表现

Expected to go to discord channel, instead get invalid invite.

**Comment by zRzRzRzRzRzRzR** [comment]
We will update soon
