### ISSUE TITLE
Support for ControlNet

### ISSUE THREAD

**Issue by tliby** [THUDM/CogVideo#322]
Thanks for your awasome work.
Can this model attain nuanced control through adjustments (like ControlNet or T2I-Adapter)?

**Comment by zRzRzRzRzRzRzR** [comment]
Currently, there has been no attempt at related work, perhaps the community can give it a try

**Comment by rodjjo** [comment]
https://github.com/TheDenk/cogvideox-controlnet

@zRzRzRzRzRzRzR

**Comment by zRzRzRzRzRzRzR** [comment]
We have noticed, we are trying, thank you!
