### ISSUE TITLE
Question about learnable position embedding in I2V model

### ISSUE THREAD

**Issue by xvjiarui** [THUDM/CogVideo#323]
Hi Team,

Great job on releasing I2v model. Congratulations!

While reading the code, I noticed that learnable position embedding is not properly used in the current SAT implementation. 
In https://github.com/THUDM/CogVideo/blob/1e5dd975e234dd8dc7683993f5e1d8dedb4cc747/sat/dit_video_concat.py#L311 we always forward a `None` position embedding instead of `self.pos_embedding`. Did I miss something or it's intended?

**Comment by zRzRzRzRzRzRzR** [comment]
This is problematic, the new code has already been attached today

**Comment by xvjiarui** [comment]
Thank you so much for your prompt reply!

**Comment by jacobswan1** [comment]
Hi @zRzRzRzRzRzRzR , quick question: 

when I check the CogVideoX5B's checkpoint, I noticed that in the checkpoint there's no pre-trained weight for "pos_embed" but only model.diffusion_model.mixins.pos_embed.freqs_sin and model.diffusion_model.mixins.pos_embed.freqs_cos. Does that mean the T2V 5B is not pre-trained with ROPE positional embedding? 

Though it might not be obviously affecting the performance, but is it intended?
