### ISSUE TITLE
How to do batch inference on CogVLM2-Caption?

### ISSUE THREAD

**Issue by Yuancheng-Xu** [THUDM/CogVideo#327]
I have a dataset of videos with different lengths of videos, so the number of frames fed into CogVLM2-Caption are different.

How to do batch inference of CogVLM2-Caption (several videos at a time), especially considering that every video may require different number of frames?  Are there any reference code on this? Thank you a lot!

**Comment by glide-the** [comment]
@Yuancheng-Xu  Hi boy, I obtained this dataset by judging the scene in the original 22-frame video and extracting the best clustered shot description of the scene and the first and last frame description of each chunk video in the scene through the model. Here is a more detailed dataset processing method in our Feishu application document. This is public information.

It contains the entire dataset preprocessing process and ablation experiment information of lora fine-tuning, 
but it is in Chinese. I'm sorry that I haven't had time to translate it into English.

script: https://zhipu-ai.feishu.cn/wiki/Ln9dw9ohpiFymekjeabc8TTinRd

Ablation experiment：https://zhipu-ai.feishu.cn/wiki/OjIDwMEKniIby1kHQa4cMKibnhP

**Comment by Yuancheng-Xu** [comment]
Thanks for the response! The documentation is very helpful.

I wonder if there is codebase for doing batch inference using the latest [cogvlm2-llama3-caption](https://huggingface.co/THUDM/cogvlm2-llama3-caption). I looks like the document is processing the captions (that comes with the videos), not re-caption the videos using a video-to-text models. 

I am asking since I really want to try out this amazing video-to-text models for large scale video captioning tasks, and batch inference is important for efficiency.

**Comment by glide-the** [comment]
We used the THUDM/cogvlm2-llama3-caption model for annotation, and of course, MiniCPM-V-2.6 is also very good. Although it’s a general-purpose model, the annotation results are still quite decent. If your hardware is limited, you might want to try using this model.
Regarding the T&J dataset, I think it could serve as a good reference, although I didn’t create it. You can find it here:
https://huggingface.co/datasets/Wild-Heart/Tom-and-Jerry-VideoGeneration-Dataset.

**Comment by wr0124** [comment]
> We used the THUDM/cogvlm2-llama3-caption model for annotation, and of course, MiniCPM-V-2.6 is also very good. Although it’s a general-purpose model, the annotation results are still quite decent. If your hardware is limited, you might want to try using this model. Regarding the T&J dataset, I think it could serve as a good reference, although I didn’t create it. You can find it here: https://huggingface.co/datasets/Wild-Heart/Tom-and-Jerry-VideoGeneration-Dataset.

Hi! It is nice to hear this topic, what is the VRAM requirement for THUDM/cogvlm2-llama3-caption model?  can it being used on  A5000(24G) ?
