### ISSUE TITLE
Do not hard code num_frames=49

### ISSUE THREAD

**Issue by SoftologyPro** [THUDM/CogVideo#340]
### Feature request  / 功能建议

In cli_demo.py can 49 for numframes be an argument to be set by the user?
Other CogVideoX systems allow more frames to create longer videos.

### Motivation / 动机

Longer length videos.

### Your contribution / 您的贡献

N/A

**Comment by zRzRzRzRzRzRzR** [comment]
The original model does not possess this capability; to be precise, it must be a number in the form of 8 * N + 1 (where N ≤ 6). Currently, we can apply it to 33, 41, 49

**Comment by SoftologyPro** [comment]
OK. Thanks for the clarification.
