### ISSUE TITLE
导出lora模型为什么报错“lora_state_dict length is not 240”

### ISSUE THREAD

**Issue by schhaohao** [THUDM/CogVideo#344]
### System Info / 系統信息

![image](https://github.com/user-attachments/assets/aaf3e810-41fe-4c9f-b6fe-ec27d5807f7e)

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1

### Expected behavior / 期待表现

1

**Comment by wenqsun** [comment]
The 240 is for 2B models, which is 8*30=240. If you are using the 5B model, the number should be 336, which is 8*42=336. I hope this will help you.
