### ISSUE TITLE
Frame Interpolation is causing an error

### ISSUE THREAD

**Issue by Enchante503** [THUDM/CogVideo#345]
### System Info / 系統信息

Windows11Pro WSL2 Ubuntu 22.04.4 LTS
CUDA12
RTX4090

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

I tried to make a video from the sample image at `https://huggingface.co/spaces/THUDM/CogVideoX-5B-Space`
using I2V + Frame Interpolation (8fps -> 16fps), but I got an error.

When I tried it locally (gradio_composite_demo)
I got the following error:
`RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 480 but got size 496 for tensor number 1 in the list.`

In the local environment, add the following code:
```
pipe_image.enable_sequential_cpu_offload()
pipe_image.vae.enable_tiling()
```

### Expected behavior / 期待表现

The video is created successfully.

**Comment by zRzRzRzRzRzRzR** [comment]
@glide-the
