### ISSUE TITLE
Is there a plan to release CogVideoX-2B-I2V

### ISSUE THREAD

**Issue by JH-Xie** [THUDM/CogVideo#347]
### Feature request  / 功能建议

open CogVideoX-2B-I2V

### Motivation / 动机

release CogVideoX-2B-I2V for resource limited finetuning

### Your contribution / 您的贡献

.

**Comment by zRzRzRzRzRzRzR** [comment]
The model weights have been open-sourced and can be found in the readme. They are free to use for academic research.

**Comment by zhou-linpeng** [comment]
> The model weights have been open-sourced and can be found in the readme. They are free to use for academic research.

It's CogVideoX-5B-I2V, not CogVideoX-2B-I2V ?

**Comment by zRzRzRzRzRzRzR** [comment]
We did not create CogVideoX-2B-I2V (we did not train this model); we only trained the 5B version, because the 5B version has better performance

**Comment by JH-Xie** [comment]
> We did not create CogVideoX-2B-I2V (we did not train this model); we only trained the 5B version, because the 5B version has better performance

thanks for your reply.
