### ISSUE TITLE
Model weights fine-tuned on UCF and kinetics

### ISSUE THREAD

**Issue by YuhanLiu11** [THUDM/CogVideo#35]
Dear Authors,

Thanks a lot for the awesome work on CogVideo! 

I was wondering do you plan to release the model weights fine-tuned on UCF or kinetics? 

Thanks a lot!

**Comment by wenyihong** [comment]
Hi Yuhan, 
The finetuning details have been listed in our paper,  which can be found at https://openreview.net/forum?id=rB6TpjAuSRy . (This is our ICLR version, which may cover a bit more details. ) Currently we're not able to fetch the finetuned weights.
