### ISSUE TITLE
AttributeError: 'CogVideoXPipeline' object has no attribute 'load_lora_weights',已经是最新版本的diffusers了0.30.3

### ISSUE THREAD

**Issue by schhaohao** [THUDM/CogVideo#350]
### System Info / 系統信息

![image](https://github.com/user-attachments/assets/f60253b5-9528-4590-86e6-55ad414cc382)

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1

### Expected behavior / 期待表现

1

**Comment by zRzRzRzRzRzRzR** [comment]
This needs to be in the main branch, not in any released version
