### ISSUE TITLE
ValueError: text_encoder is not found in self._lora_loadable_modules=['transformer'].使用load_cogvideo_lora.py加载lora并推理报这个错误

### ISSUE THREAD

**Issue by schhaohao** [THUDM/CogVideo#352]
### System Info / 系統信息

![Uploading image.png…]()

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1

### Expected behavior / 期待表现

1

**Comment by cdalinghaus** [comment]
@schhaohao, please provide further information how you fixed this, I am running into the same error.

**Comment by haofengl** [comment]
please provide further information how you fixed this, I am running into the same error.

**Comment by chenshuo20** [comment]
You can skip the text encoder part in fuse_lora() in src/diffusers/loaders/lora_base.py like:     
```
for fuse_component in components:
    if fuse_component == 'text_encoder':
    continue
```
But they should fix their tools/export_sat_lora_weight.py to skip text encoder.

**Comment by cdalinghaus** [comment]
I just commented out the line that throws the error and it seemed to work also
