### ISSUE TITLE
load_cogvideo_lora.py加载lora和sat中的inference.sh是有什么gap吗。为什么sat推的没问题，load_cogvideo_lora.py推理的直接崩掉了

### ISSUE THREAD

**Issue by schhaohao** [THUDM/CogVideo#353]
### System Info / 系統信息

1

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1

### Expected behavior / 期待表现

1

**Comment by zRzRzRzRzRzRzR** [comment]
@glide-the

**Comment by glide-the** [comment]
https://zhipu-ai.feishu.cn/wiki/Ln9dw9ohpiFymekjeabc8TTinRd#L8bwd6kO0ogwCwxNeEHcfhJCn7f
