### ISSUE TITLE
Improved convenience of prompt input

### ISSUE THREAD

**Issue by Enchante503** [THUDM/CogVideo#354]
### Feature request  / 功能建议

This is not a feature of CogVideo, but it is a Tips to improve the convenience of prompt input.
By including the example below in the examples for the AI, it will translate multilingual input into English and complete the prompt.

Here is an example for Japanese:
```
User Input: "日本語の文章"
Response: "A Japanese text input is automatically translated into English for further processing. For example, '犬が浜辺にいる' becomes 'A dog is on the beach.' Then the same detailed description process applies."
```

### Motivation / 动机

-

### Your contribution / 您的贡献

-

**Comment by zRzRzRzRzRzRzR** [comment]
Yes, to be precise, this refinement is necessary, not just for translation, but in the convert_demo.py we provide, you can see that we use LLM for refinement prompts
