### ISSUE TITLE
SAT Finetuning I2V model

### ISSUE THREAD

**Issue by Yuancheng-Xu** [THUDM/CogVideo#355]
Hello!

I wonder if there is instructions on how to finetune the I2V model. Does the current`train_video.py` work? It seems that it does not handle the image input in the code. Also, do we need to specify that we are using an I2V, instead of an T2V model in the training configuration file?

I am current using `torchrun --standalone --nproc_per_node=8 train_video.py --base configs/cogvideox_5b_i2v_lora.yaml configs/sft.yaml --seed $RANDOM ` but it shows the following error

```
RuntimeError: Error(s) in loading state_dict for SATVideoDiffusionEngine:
size mismatch for model.diffusion_model.mixins.patch_embed.proj.weight: copying a param with shape torch.Size([3072, 16, 2, 2]) from checkpoint, the shape in current model is torch.Size([3072, 32, 2, 
2])
```

Thanks!

**Comment by zRzRzRzRzRzRzR** [comment]
你是否重新更新过我们的main分支，I2V发布后，main分支有一定的修改。你能更新到
628f7366280da57af84c6e1ee60fa180a16c61f1 方便查看吗

**Comment by Yuancheng-Xu** [comment]
嗯我用的就是[628f736](https://github.com/THUDM/CogVideo/commit/628f7366280da57af84c6e1ee60fa180a16c61f1)
 
* 我用的`configs/sft.yaml` 和5B-t2V是一样的，除了路径指向了t2V
* 我用了 `configs/cogvideox_5b_i2v_lora.yaml`

**Comment by Yuancheng-Xu** [comment]
Oh that's right. Updating to the latest codebase and it works now. Thanks!

**Comment by NickPan7779** [comment]
你好，我用11月7号的main分支跑i2v  @lora微调还是出现了这个问题，麻烦帮忙看看，感谢！
untimeError: Error(s) in loading state_dict for SATVideoDiffusionEngine:
        size mismatch for model.diffusion_model.mixins.patch_embed.proj.weight: copying a param with shape torch.Size([3072, 16, 2, 2]) from checkpoint, the shape in current model is torch.Size([3072, 32, 2, 2])

@zRzRzRzRzRzRzR

**Comment by NickPan7779** [comment]
> Oh that's right. Updating to the latest codebase and it works now. Thanks!

请问你修改了什么地方解决了这个问题，感谢！ @Yuancheng-Xu
