### ISSUE TITLE
CogVideoX里的3d-rope是在哪里实现的呀

### ISSUE THREAD

**Issue by HeShiLie** [THUDM/CogVideo#359]
2.2 Expert Transformer 里的3D-RoPE说到“independently apply 1D-RoPE to each dimension of the coordinates, each occupying 3/8, 3/8, and 2/8 of the hidden states’ channel”，但是在diffusers里的CogVideoXTransformer3DModel里我只看到了全量rope的实现啊

**Comment by zRzRzRzRzRzRzR** [comment]
try find `get_3d_rotary_pos_embed` in cogvideox_transformer_3d.py

**Comment by HeShiLie** [comment]
thanks alot
