### ISSUE TITLE
4090显卡CUDA out of memory

### ISSUE THREAD

**Issue by chenyf2022** [THUDM/CogVideo#36]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.56 GiB (GPU 0; 23.68 GiB total capacity; 18.96 GiB already allocated; 2.84 GiB free; 18.97 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.

**Comment by chenyf2022** [comment]
您好，在使用4090显卡尝试生成视频的时候出现了这个问题，请问有什么解决的方法吗？

**Comment by wenyihong** [comment]
生成视频需要25G左右的显存。我们正在修复huggingface的demo，之后可以去Huggingface上尝试生成
