### ISSUE TITLE
learnable_pos_embed in cogvideox_5b_i2v.yaml vs cogvideox_5b.yaml

### ISSUE THREAD

**Issue by hw-liang** [THUDM/CogVideo#367]
### System Info / 系統信息

NA.

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Great work! I noticed in the model config files, the 5B and 2B are using different pos_embed_config. The 5Bs use dit_video_concat.Rotary3DPositionEmbeddingMixin. However, the 5B-t2v and 5B-i2v are using different settings for learnable_pos_embed. 5B-t2v sets learnable_pos_embed=False while 5B-i2v sets learnable_pos_embed=True. Is there any special consideration?

Thank you!

### Expected behavior / 期待表现

 5B-t2v sets learnable_pos_embed=False (default value) while 5B-i2v sets learnable_pos_embed=True. Is there any special consideration?

**Comment by zRzRzRzRzRzRzR** [comment]
There are, you can find in our paper, at the same time, in this code, only the I2V model has learnable_pos_embed. Using this part allows the model to better capture positional information.
