### ISSUE TITLE
Generated video with third-party watermarks

### ISSUE THREAD

**Issue by yclin925** [THUDM/CogVideo#378]
### System Info / 系統信息

As tile, The generated videos appears as a "pond5" watermark.
Is this normal?

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. Deployment of CogVideo 2B models on the cloud
2. The generated videos by text appears as a "pond5" watermark

### Expected behavior / 期待表现

I hope the officials can explain and provide solutions as much as possible.

**Comment by zRzRzRzRzRzRzR** [comment]
I believe this should be the 2B model, not the 5B model. The 2B model has a slight issue during the SFT stage, which causes it to have a pond5 watermark under certain prompts. We haven't maintained this version of the model much. Our focus of research is on the 5B model, which does not have this issue.
Currently, the issue with the 2B model cannot be resolved.

**Comment by TemporalLabsLLC-SOL** [comment]
I can confirm 5b does do it rarely. I'm cataloging out every gs and steps combination possible on my hardware to see if there's any pattern or reason to it.

Hopefully we can just avoid certain maths.
