### ISSUE TITLE
How to use I2V fine-tuned lora weight in the diffusers?

### ISSUE THREAD

**Issue by asdnjadsn** [THUDM/CogVideo#381]
### System Info / 系統信息

as title

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. have success fine-tuned 5b-i2v lora model
2. and,change the lora sat weight to diffusers by export_sat_lora_weight.py
3. get a lora safetensors: pytorch_lora_weights.safetensors
4. i don't know how to use it in the i2v module, load_cogvideox_lora.py is suit for t2v

### Expected behavior / 期待表现

great job ! ! ! wish your reply

**Comment by chenshuo20** [comment]
In this [issue](https://github.com/THUDM/CogVideo/issues/306), they mention that their experiment using the diffuser resulted in an OOM.

**Comment by zRzRzRzRzRzRzR** [comment]
Now the lora of diffusers is working try it at dev branch

**Comment by asdnjadsn** [comment]
> Now the lora of diffusers is working try it at cogvideox-dev branch of our repo

seem that i2v lora part is not work in cogvideox-dev, i try cli_demo.py, and have updated the diffusers to main branch(0.31.0.dev0)
![image](https://github.com/user-attachments/assets/a02f6518-70b4-4dd4-8390-b2143c187dce)
