### ISSUE TITLE
[Q] About train dataset (amount, resolution, video length, etc...)

### ISSUE THREAD

**Issue by KihongK** [THUDM/CogVideo#385]
I already read [finetune ReadMe](https://github.com/THUDM/CogVideo/blob/main/finetune/README.md) docs

but I wonder about train dataset detail information

for example) 
- each video should be atleast 4s (Limit screen transitions to no more than once.)
- each video fps is 30
- each video should be 720 * 480 resolution or upper (automatically resize video to 720*480)
- more than 49 frames videos are automatically skip rest frames (train only 0~48 frames)
- recommend more than 25 video for new style training
- prompt should be less than 100 english words 
- etc..

Please let me know if there are any mistakes or if there's anything you think should be added.

**Comment by chenshuo20** [comment]
You can check this [dataset](https://huggingface.co/datasets/Wild-Heart/Disney-VideoGeneration-Dataset) as an example. Also you can check the data file in sat/data_video.py

**Comment by zRzRzRzRzRzRzR** [comment]
The frame rate for each video should be 8; videos with a frame rate higher than 8 should be sampled at an average of 8 frames. Otherwise, slow-motion videos of less than 1 second will appear (48 frames in a 30-frame video is less than 2 seconds).
It is recommended that the video duration be between 4-6 seconds.

**Comment by zRzRzRzRzRzRzR** [comment]
If you have a 180-frame video (30fps * 6 seconds), and you sample at an interval of 3.75 (180 / 48), the sampling process will proceed as follows:
	•	The 1st sampled frame: select the original 1st frame.
	•	The 2nd sampled frame: skip 3 frames, select the 4th frame.
	•	The 3rd sampled frame: skip 4 frames, select the 8th frame.
	•	And so on, alternating between skipping 3 and 4 frames, ultimately sampling 48 frames from the original 180 frames.
	
Alternatively, you can directly sample every 4th frame from the original video, but this may result in some duplicate frames toward the end. On the other hand, if you sample every 3rd frame, the final few frames of the video might not be captured properly.

**Comment by chenshuo20** [comment]
Currently they only support 480,720. But you can try this [repo](https://github.com/aigc-apps/CogVideoX-Fun) for multi resolution. They use PE Interpolation trick mentioned by Pixart-sigma.

**Comment by zRzRzRzRzRzRzR** [comment]
https://github.com/a-r-r-o-w/cogvideox-factory You might also want to try this; it can train videos at any resolution on its own.
