### ISSUE TITLE
gradio UI for finetuning T2V AND I2V - CogVideoX 5B 

### ISSUE THREAD

**Issue by GeeveGeorge** [THUDM/CogVideo#386]
### Feature request  / 功能建议

gradio UI for finetuning T2V AND I2V - CogVideoX 5B @zRzRzRzRzRzRzR @LittleNyima , with multi gpu and single gpu options.
also script for captioning videos the users have. 

### Motivation / 动机

a gradio UI will be easy to use. for videos, include a path url textbox where the user can specify the path to their video dataset.

### Your contribution / 您的贡献

if there is a good well tested fine-tuning script, then i could help contribute to the developement of the gradio UI.

**Comment by zRzRzRzRzRzRzR** [comment]
We are still testing the relevant code together with the Huggingface team, such as
https://github.com/huggingface/diffusers/pull/9482
Currently, the fine-tuned videos include both normal and faulty ones, and we are verifying the faulty videos
