### ISSUE TITLE
I2V diffusers SFT finetune OOM

### ISSUE THREAD

**Issue by Verg-Avesta** [THUDM/CogVideo#393]
### System Info / 系統信息

A100-SXM 80GB

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

I modified the provided **train_cogvideox_image_to_video_lora.py** to fine-tune the entire **attn1** layers instead of just the **LoRA** layers. Since the dataset is a little large, I extract VAE and text encoder features online. However, even if I enabled bfloat16, the task ran out of memory on 80GB A100 GPU. Could this be due to the memory used by the VAE and text encoder？Or SFT finetuning with diffusers will certainly lead to OOM?

### Expected behavior / 期待表现

NO OOM.

**Comment by zRzRzRzRzRzRzR** [comment]
The current solution is to prepare the data in advance, then unload the vae and T5 after encoding, which saves a lot of space; otherwise, multiple H100s (not just one) are needed to run under the condition of a batch size of 1. We have completed a part of it and plan to set up a separate repository in the future dedicated to fine-tuning. There are still many parts to optimize, as I said, it will be completed by October.

**Comment by Nojahhh** [comment]
I apologize in advance for my lack of sufficent knowledge, but I just can't figure out what I need to modify in the train_cogvideox_image_to_video_lora.py script to utilize a multi-GPU setup with two H100s. I've set up accelerator through accelerate config to make use of a multi-GPU setup with all that comes with it, but it still only utilizes one GPU and I keep getting OOM errors.

**Comment by Verg-Avesta** [comment]
Thank you for the detailed response. By the way, can I reduce the spatial resolution or temporal length during fine-tuning to lower the memory usage and avoid OOM?

**Comment by trouble-maker007** [comment]
@zRzRzRzRzRzRzR In order to increase the batch size and reduce the memory consumption, will it affect the training speed of the model?

**Comment by a-r-r-o-w** [comment]
Gradient checkpointing with DDP/DeepSpeed are necessary to make it run under 80 GB for LoRA. For full finetuning, you additionally might also require low-bit optimizers or CPU offloading optimizers. There is a plan to release some scripts by Friday to support these cases, while being able to run > 1 batch size.

**Comment by Verg-Avesta** [comment]
Thank you for your advice. But when I use gradient checkpointing with DDP, I met some problems.

When I finetune all 'attn1' layers or the whole transformer with _"use_reentrant": False_ , the gradients of all parameters are none. But if I set _"use_reentrant": True_ , there will be error: "_RuntimeError: Expected to mark a variable ready only once._".

Could you please tell me how to use gradient checkpointing with DDP correctly?

**Comment by a-r-r-o-w** [comment]
Oh, I'm not sure why you get that error with Diffusers script... I don't when trying to replicate. Could you share your environment details?

We released [cogvideox-factory](https://github.com/a-r-r-o-w/cogvideox-factory) today btw, and have tested for compatibility with DeepSpeed/DDP and gradient checkpointing seems to be working without problems. Maybe you could try those scripts with diffusers:main to see if you get the same error?
