### ISSUE TITLE
Why do color blocks appear in the video after changing num_frame to 25?

### ISSUE THREAD

**Issue by pyoliu** [THUDM/CogVideo#396]
### System Info / 系統信息

无

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![584f32901c9152baeaf5bdf65be4d33](https://github.com/user-attachments/assets/433ac192-b2ac-489f-8c09-a1a9d8dccc8b)

### Expected behavior / 期待表现

生成3s清晰视频

**Comment by kijai** [comment]
I2V model only supports 49 frames.

**Comment by GallonDeng** [comment]
Is there a way to reduce the frames to get output faster?
