### ISSUE TITLE
lora推理报错

### ISSUE THREAD

**Issue by syyxsxx** [THUDM/CogVideo#399]
### System Info / 系統信息

diffusers:通过源码安装
transformers:4.45.2

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

通过diffusers训练的自己的lora之后报了下面的错误
运行命令：
python cli_demo.py  --prompt "A classic black and white animated scene unfolds, featuring two cartoon characters: a large, exaggerated creature with an open mouth and numerous teeth, and a small, anthropomorphic figure with oversized ears. The smaller character exhibits various expressions and gestures, initially reaching into the creature's mouth, then raising its arms, and finally offering a lollipop or candy. The scene captures a moment of interaction, suggesting communication, negotiation, or playful engagement between the two characters in a whimsical, animated world" --model_path THUDM/CogVideoX-5b --generate_type "t2v" --lora_path ../pytorch_lora_weights.safetensors

Traceback (most recent call last):
  File "/root/wsy/CogVideo/inference/cli_demo.py", line 177, in <module>
    generate_video(
  File "/root/wsy/CogVideo/inference/cli_demo.py", line 85, in generate_video
    pipe.fuse_lora(lora_scale=1 / lora_rank)
  File "/root/wsy/CogVideo/diffusers/src/diffusers/loaders/lora_pipeline.py", line 2586, in fuse_lora
    super().fuse_lora(
  File "/root/wsy/CogVideo/diffusers/src/diffusers/loaders/lora_base.py", line 445, in fuse_lora
    raise ValueError(f"{fuse_component} is not found in {self._lora_loadable_modules=}.")
ValueError: text_encoder is not found in self._lora_loadable_modules=['transformer'].

### Expected behavior / 期待表现

希望能解决问题

**Comment by chenshuo20** [comment]
You can check this [issue](https://github.com/THUDM/CogVideo/issues/352).
