### ISSUE TITLE
encode_video() uses pure noise as image_latent_dist？

### ISSUE THREAD

**Issue by Verg-Avesta** [THUDM/CogVideo#405]
### System Info / 系統信息

A100-SXM 80GB

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

In **train_cogvideox_image_to_video_lora.py**, function **encode_video()** appears to use a pure noise as the **image_latent_dist** between Line [1277](https://github.com/THUDM/CogVideo/blob/7fe6d820baf39edd88f7e1041d914a7c0eff8f15/finetune/train_cogvideox_image_to_video_lora.py#L1277) to Line [1280](https://github.com/THUDM/CogVideo/blob/7fe6d820baf39edd88f7e1041d914a7c0eff8f15/finetune/train_cogvideox_image_to_video_lora.py#L1280). 

This behavior seems unintended, as the image_latent_dist is being generated from randomly sampled noise rather than meaningful input. Could this be a mistake?

### Expected behavior / 期待表现

Use VAE to compress the first frame of the video, not pure noise.

**Comment by a-r-r-o-w** [comment]
You're correct, it should be `image + noisy_image`. We made the updates to the diffusers script [here](https://github.com/huggingface/diffusers/pull/9482/commits/d519d7553fdf85c4aadf0f668e3680d6896444ec) and it will be reflected here too. cc @zRzRzRzRzRzRzR

**Comment by Verg-Avesta** [comment]
Thank you for your attention, but why do we need to add noise to the image condition here? In the pipeline.py, we directly concatenate the original image latent without any noise to the video latent, so maybe we should also use the image latent without noise during training?

**Comment by a-r-r-o-w** [comment]
You can choose to do it without noise too. I think it's just a regularization strategy that the authors found helpful for better generalization

**Comment by Verg-Avesta** [comment]
Thanks for your careful explanation!
