### ISSUE TITLE
prepare_rotary_positional_embeddings

### ISSUE THREAD

**Issue by HaoZhang990127** [THUDM/CogVideo#406]
### Feature request  / 功能建议

train video with different resolution

### Motivation / 动机

train video with different resolution

### Your contribution / 您的贡献

Hi,

Thank you for your nice work again. I am confuse about the prepare_rotary_positional_embeddings function, https://github.com/THUDM/CogVideo/blob/da5fc1c1cab3b1451c866b1f9111eeec9d0410e4/finetune/train_cogvideox_lora.py#L822, in here you use base_height: int = 480, base_width: int = 720 for your fix resolution training. Could you explain **the meaning of the base_height and base_width**? If i want to train a video with height=720 and width=480, what base_height and base_width should be set in here? And if I want to train the video with random resolution, what base_height and base_width should be set in here? 
![image](https://github.com/user-attachments/assets/90d7a088-8429-41a6-9061-87d956916d1b)

Thank you

**Comment by foreverpiano** [comment]
same problem

**Comment by lijain** [comment]
same problem
