### ISSUE TITLE
Multi gpu inference for image to video

### ISSUE THREAD

**Issue by sumitmamoria** [THUDM/CogVideo#408]
I am trying to use the gradio web interface for image to video, on a dual 3090 setup. I am getting OOM errors as it tries to fill only one GPU over 24G. How do we utilize both GPUs for this case?

**Comment by zRzRzRzRzRzRzR** [comment]
what is your code? did you follow our cli_demo.py

**Comment by sumitmamoria** [comment]
> what is your code? did you follow our cli_demo.py

I am using the unmodified, gradio web demo code.

**Comment by zRzRzRzRzRzRzR** [comment]
That's definitely not possible, you refer to cli_demo and copy these three lines
```
pipe.enable_sequential_cpu_offload()
pipe.vae.enable_slicing()
pipe.vae.enable_tiling()
''
This is helpful.
