### ISSUE TITLE
 index 144 is out of bounds for dimension 0 with size 144

### ISSUE THREAD

**Issue by mercywang111** [THUDM/CogVideo#409]
### System Info / 系統信息

![Uploading 2.png…]()

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![1](https://github.com/user-attachments/assets/1ce28416-9ee5-4c98-9436-a785611763e7)
训练到第360个迭代的时候报错超出index范围

### Expected behavior / 期待表现

之前微调过一次没有问题，这次补充了数据集就报这个错了。是数据集长度还是什么问题吗？

**Comment by zRzRzRzRzRzRzR** [comment]
如果想查看数据集问题，或许应该单独试一下新补充的数据集是否有问题？先只训练新的数据集
