### ISSUE TITLE
推理只能49帧吗

### ISSUE THREAD

**Issue by Amuseum-WHR** [THUDM/CogVideo#414]
如题，inference的时候，num_frames只能设置为49吗，能否选择更短的帧数呢？我尝试的生成结果会有些问题

**Comment by zRzRzRzRzRzRzR** [comment]
33 41 49

**Comment by tedfeng424** [comment]
为什么帧数必须得是 8*N+1 这种格式的呢？4*N+1可以么？

**Comment by DidiD1** [comment]
> 如题，inference的时候，num_frames只能设置为49吗，能否选择更短的帧数呢？我尝试的生成结果会有些问题

好像t2v可以换帧数，但是i2v就不行，我猜可能跟i2v的learnable_pos_embed有关系？
