### ISSUE TITLE
Question help - Is it possible to clone the trasformer using copy.deepcopy ?

### ISSUE THREAD

**Issue by rodjjo** [THUDM/CogVideo#415]
### Feature request  / 功能建议

I had an idea that I'm not sure if it's going to work.

I was trying to copy the transformer (duplicate the module with copy.deepcopy), with no success yet.

If duplicating the transformer were possible, maybe I would be able to offload the inference during the training and updating the loss on the cloned one at RAM, then clone again and sequence offload the copy after the loss being updated.

I do no if It's possible (did not investigate blocking points yet), it was just an idea I was having.

### Motivation / 动机

If possible, there was a chance of using less VRAM during the training, however we would have two transformers at RAM (one sequential offloaded and other in pure RAM).

### Your contribution / 您的贡献

.

**Comment by zRzRzRzRzRzRzR** [comment]
Haven't tried it, but it seems that the I/O loss would be very high with such an operation.
Regarding training, perhaps one could use https://github.com/a-r-r-o-w/cogvideox-factory.
Encoding the dataset in advance saves more video memory.

**Comment by rodjjo** [comment]
@zRzRzRzRzRzRzR Thanks!

I did the hacking in other way.  I'm not sure if it works I need to train the Disney dataset and validate the result first (to check if the weights are getting updated correctly during the train).

There's a 30% success in my hacking here and If I have success I'll open a pull request to let us to train 5B under 10GB VRAM.

No promise, as I'm trying to hack accelerate and cpu_offloading.

I'm crossing the fingers here.

**Comment by rodjjo** [comment]
It was not possible, there's an issue with deepspeed and `deepspeed.zero.Init`, never mind
