### ISSUE TITLE
Question about cfg of I2V

### ISSUE THREAD

**Issue by luyvlei** [THUDM/CogVideo#422]
In the diffusers I2V pipeline, I found that cfg only dropped the text prompt. However, in train_cogvideox_image_to_video_lora.py, I found that only image_latents were dropped without text prompt. What kind of drop mode is used in I2V pre-training of cogvideox？

**Comment by RitianYu** [comment]
Hi, I also confused with the cfg used in CogVideoX-I2V. Do you have some insights for this question now？
