### ISSUE TITLE
开源的i2v模型是否可以支持 768× 1360 pixels 高分辨率？

### ISSUE THREAD

**Issue by QingQingS** [THUDM/CogVideo#424]
你好，看最新的技术报告里面提到 能支持768 * 1360高分辨的 视频生成，想了解下之前开源的i2v模型 也能支持高分辨率? 在之前放出的代码里 是480 * 720大小的？

**Comment by zRzRzRzRzRzRzR** [comment]
不能，只支持 480 * 720。 你可以参考首页的factory仓库自己微调。
