### ISSUE TITLE
Image to video is not utilising full capacity of GPU

### ISSUE THREAD

**Issue by iaindian** [THUDM/CogVideo#429]
### System Info / 系統信息

Hi,

I am using cli [script ](https://github.com/THUDM/CogVideo/blob/main/inference/cli_demo.py) to try image to video, I have RTX 3060 and 24 GB RAM. The problem is that only 3.6 GB of VRAM is getting utilised causing huge delay in generation. I tried commenting lines
pipe.enable_sequential_cpu_offload()

but then it is using 12GB of VRAM causing the PC to hang. So my question is how can I tweak the setting to use at least 10GB of VRAM with sequential CPU offload enabled. Attaching the screesnshot as well

===Translation in Chinese----
你好，

我正在使用 cli [script ](https://github.com/THUDM/CogVideo/blob/main/inference/cli_demo.py) 尝试图像到视频，我有 RTX 3060 和 24 GB RAM。问题是只有 3.6 GB 的 VRAM 得到利用，导致生成出现巨大延迟。我尝试评论行
pipeline.enable_sequential_cpu_offload()

但随后它使用 12GB VRAM 导致 PC 挂起。所以我的问题是如何调整设置以使用至少 10GB 的 VRAM 并启用顺序 CPU 卸载。还附上屏幕截图

![gpu](https://github.com/user-attachments/assets/de0c8683-47b6-49ff-8364-15a9d8cb6f5e)

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. Take any image
2. Use cli script for image to video
3. Make sure  you have not commented this
 pipe.enable_sequential_cpu_offload()
 pipe.vae.enable_slicing()
 pipe.vae.enable_tiling()
 
 4. GPU 12GB utilisation is only 3.6GB

### Expected behavior / 期待表现

你好，

我正在使用 cli [script ](https://github.com/THUDM/CogVideo/blob/main/inference/cli_demo.py) 尝试图像到视频，我有 RTX 3060 和 24 GB RAM。问题是只有 3.6 GB 的 VRAM 得到利用，导致生成出现巨大延迟。我尝试评论行
pipeline.enable_sequential_cpu_offload()

但随后它使用 12GB VRAM 导致 PC 挂起。所以我的问题是如何调整设置以使用至少 10GB 的 VRAM 并启用顺序 CPU 卸载。还附上屏幕截图

**Comment by zRzRzRzRzRzRzR** [comment]
pipeline.enable_model_cpu_offload()

Try this
If you only have 3060 and 24 GB of RAM, it might be struggling, or you can directly try commenting out `pipeline.enable_sequential_cpu_offload()`
And set `pipe.to("cuda")` Running this model with 24GB of video memory

**Comment by iaindian** [comment]
Thanks, I did applied dynamic quant with pipeline.enable_sequential_cpu_offload(), it is the best possible outcome for my config
