### ISSUE TITLE
图生视频模式报错

### ISSUE THREAD

**Issue by SUN-zx** [THUDM/CogVideo#430]
### System Info / 系統信息

调用cli_demo，输入prompt和一张图像；会提示如下错误，看起来是通道维度没有对齐；应该怎么修改可以保证通道对齐
``` bash
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/cogvideo/pipeline_cogvideox_image2video.py", line 727, in __call__
    latents, image_latents = self.prepare_latents(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/cogvideo/pipeline_cogvideox_image2video.py", line 388, in prepare_latents
    image_latents = torch.cat([image_latents, latent_padding], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 16 but got size 8 for tensor number 1 in the list.
```

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. 运行cli_demo脚本

### Expected behavior / 期待表现

给出解决方案

**Comment by zRzRzRzRzRzRzR** [comment]
安装的是图生视频的模型么

**Comment by lichenyu20** [comment]
我也遇到了一样的问题。输入图片的尺度是720x480。

**Comment by henbucuoshanghai** [comment]
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 16 but got size 8 for tensor number 1 in the list.
same error!  why

**Comment by zRzRzRzRzRzRzR** [comment]
How does this inference work, which model have you installed?

**Comment by SUN-zx** [comment]
乌龙，用错了模型，改成I2V的模型就好了

**Comment by SuperMaximus1984** [comment]
What is the correct path for location of the I2V model when running Gradio (aka Huggingface) interface?
