### ISSUE TITLE
Support for multy GPUs

### ISSUE THREAD

**Issue by jumbo-q** [THUDM/CogVideo#436]
### System Info / 系統信息

AWS EC2
V100 x 4

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/31f461da-a087-44da-9fc8-4997bbebd2d4)
![image](https://github.com/user-attachments/assets/553f751a-8e45-44ad-b28c-883827773f0f)
The code has been modified 
but it still says
![image](https://github.com/user-attachments/assets/3924f8f9-cbcf-4d73-9b12-0e699148c046)

### Expected behavior / 期待表现

Fixed the bug

**Comment by jumbo-q** [comment]
the cli_demo.py

**Comment by zRzRzRzRzRzRzR** [comment]
check the comment in this code,remove cpu_offload,
