### ISSUE TITLE
使用官方的v2v功能，但视频迁移效果不好，稚嫩回事

### ISSUE THREAD

**Issue by henbucuoshanghai** [THUDM/CogVideo#437]
### System Info / 系統信息

ubuntu

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

resout of v2v  is bad,why?input mp4 is 3s,25fps.

### Expected behavior / 期待表现

resout of v2v  is bad,why?input mp4 is 3s,25fps.

**Comment by zRzRzRzRzRzRzR** [comment]
官方没有v2v功能，这个v2v是社区的，我们本身没有v2v模型，这个应该是根据我们T2V改的 720 * 480 8帧

**Comment by henbucuoshanghai** [comment]
官方没有v2v的代码和模型？那预计官方什么时候出呢？

**Comment by henbucuoshanghai** [comment]
hf的代码是哪个呢 感谢
