### ISSUE TITLE
How to SFT cogvideo-5b-i2v

### ISSUE THREAD

**Issue by adamas-fsw** [THUDM/CogVideo#441]
### System Info / 系統信息

Nvidia A100
CUDA 12.1

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

非常感谢您的贡献。我想要针对自己的数据集对cogvideo i2v版本进行sat图生视频完全微调，但我并未找到相关的技术文档，仅找到Text2video相关的文档。请问i2v的数据该如何存放，以及通过哪个代码进行训练。可否在未来提供一些技术文档

### Expected behavior / 期待表现

None

**Comment by zRzRzRzRzRzRzR** [comment]
"Can you check CogVideoX-Factory? This repository can fine-tune I2V at a lower cost."
