### ISSUE TITLE
I2V 为什么很慢 10分钟生成一个视频

### ISSUE THREAD

**Issue by THEBEST-cloud** [THUDM/CogVideo#443]
### System Info / 系統信息

cuda_version: cuda_11.8.r11.8/compiler.31833905_0
diffusers_version: 0.30.3
python_version: 3.10.0
operating_system: Linux-5.15.0-92-generic-x86_64-with-glibc2.35

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

# 用于图像生成视频
import torch
from diffusers import CogVideoXImageToVideoPipeline
from diffusers.utils import export_to_video, load_image
from time import time
import cv2
import imageio

start = time()
prompt = "A woman picks up a pair of sunglasses and smiles."
image = load_image(image="old1.jpg")
original_size = image.size
pipe = CogVideoXImageToVideoPipeline.from_pretrained(
    "CogVideoX-5b-I2V",
    torch_dtype=torch.bfloat16
)

pipe.enable_sequential_cpu_offload()
pipe.vae.enable_tiling()
pipe.vae.enable_slicing()

video = pipe(
    prompt=prompt,
    image=image,
    num_videos_per_prompt=1,
    num_inference_steps=50,
    num_frames=49,
    guidance_scale=6,
    generator=torch.Generator(device="cuda").manual_seed(42),
).frames[0]

export_to_video(video, "output.mp4", fps=8)

尝试过禁用其中的优化，速度会更慢或者相当
pipe.enable_sequential_cpu_offload()
pipe.vae.enable_tiling()
pipe.vae.enable_slicing()

### Expected behavior / 期待表现

有方法可以加速吗？

**Comment by zRzRzRzRzRzRzR** [comment]
pipe.enable_sequential_cpu_offload()
这个命令开启会很慢，如果你显存超过30G左右，直接pipe.to(“cuda")
