### ISSUE TITLE
生成视频后半段静止不动

### ISSUE THREAD

**Issue by gobigrassland** [THUDM/CogVideo#444]
### System Info / 系統信息

与环境无关

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

自己运行发现生成的视频，发现存在一个现象：前半段是运动的，后半段静止不动。在最近的https://ailab-cvc.github.io/VideoGen-Eval/#text-to-video 多个模型测评中也发现类似现象。

### Expected behavior / 期待表现

期待生成的整个视频都是合理的运动

**Comment by tengjiayan20** [comment]
这个评测集里感觉明显是对cogvideox生成的视频进行了加速播放

**Comment by hrcheng98** [comment]
后半段不动是因为cogv只有49帧，比其他sota模型短一半

**Comment by zRzRzRzRzRzRzR** [comment]
可以试一下新的模型，帧率应该不止49了
