### ISSUE TITLE
img2video output noise video

### ISSUE THREAD

**Issue by abc8350712** [THUDM/CogVideo#446]
### System Info / 系統信息

RTX4090, windows,python3.10, torch2.4.0+cuda12.4 diffusers==0.31.0

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

```python
import torch
from diffusers import CogVideoXImageToVideoPipeline
from diffusers.utils import export_to_video, load_image

pipe = CogVideoXImageToVideoPipeline.from_pretrained("THUDM/CogVideoX-5b-I2V", torch_dtype=torch.bfloat16)
pipe.to("cuda")
pipe.enable_model_cpu_offload()

prompt = "An astronaut hatching from an egg, on the surface of the moon, the darkness and depth of space realised in the background. High quality, ultrarealistic detail and breath-taking movie-like camera shot."
image = load_image(
    "https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/astronaut.jpg"
)
video = pipe(image, prompt, use_dynamic_cfg=True)
export_to_video(video.frames[0], "output.mp4", fps=8)
``` 
上面是代码，生成的效果如下所示

https://github.com/user-attachments/assets/8af7e501-956d-422b-b5a4-e851d3f4f010

### Expected behavior / 期待表现

I hope the algorithm can output correct video.

**Comment by zRzRzRzRzRzRzR** [comment]
Try setting the inference step explicitly to 50 steps, for details, check out cli_demo.

**Comment by abc8350712** [comment]
> Try setting the inference step explicitly to 50 steps, for details, check out cli_demo.
 python cli_demo.py --prompt "A female basketball player is standing in a basketball court, her body leaning forward towards the camera. She is wearing a vibrant blue basketball jersey with the number 3 prominently displayed. The person's head is tilted back, and her hands are clasped together in front of her legs. She is reaching for the viewpoint and waving at it closely. The court beneath her is a rich brown color with green wall in the background and a basketball hoop stands against the wall." --model_path "E:\work\img2video\cogvideo_model" --generate_type "i2v" --output_path ./output.mp4 --image_or_video_path "E:\work\img2video\astronaut.jpg" --dtype float16
 
 and I also try the inference step explicitly to 50 steps.The result is the same.

**Comment by abc8350712** [comment]
> Try setting the inference step explicitly to 50 steps, for details, check out cli_demo.

**Comment by abc8350712** [comment]
> Try setting the inference step explicitly to 50 steps, for details, check out cli_demo.

I try cli_demo
```python
python cli_demo.py --prompt "A female basketball player is standing in a basketball court, her body leaning forward towards the camera. She is wearing a vibrant blue basketball jersey with the number 3 prominently displayed. The person's head is tilted back, and her hands are clasped together in front of her legs. She is reaching for the viewpoint and waving at it closely. The court beneath her is a rich brown color with green wall in the background and a basketball hoop stands against the wall." --model_path "E:\work\img2video\cogvideo_model" --generate_type "i2v" --output_path ./output.mp4 --image_or_video_path "E:\work\img2video\astronaut.jpg" --dtype float16
``` 

and i also try setting the inference step explicitly to 50 steps.

the result is the same

**Comment by abc8350712** [comment]
> Try setting the inference step explicitly to 50 steps, for details, check out cli_demo.

work well. The problem may be corrupted weight.
