### ISSUE TITLE
请问下lora微调中，为什么数据处理不放在collate_fn中

### ISSUE THREAD

**Issue by tscvividly** [THUDM/CogVideo#449]
我看代码中文本和图片编码全部放在了训练之前，不是边训练边编码，这是处于什么考虑呢

**Comment by zRzRzRzRzRzRzR** [comment]
编码是作为输入的，先生成批量的输入，然后再载入，进行训练。
在cogvideox-factory中，你可以直接先保存编码好的结果，然后在多卡训练，这样就不用每次都编码了。直接使用编码后的pt数据文件作为输入

**Comment by zishen-ucap** [comment]
> 编码是作为输入的，先生成批量的输入，然后再载入，进行训练。 在cogvideox-factory中，你可以直接先保存编码好的结果，然后在多卡训练，这样就不用每次都编码了。直接使用编码后的pt数据文件作为输入

可是将视频先放进列表里面，猫和老鼠那个数据集有6000个视频，还没开始训练，2t的ram就先爆了。。。
