### ISSUE TITLE
generating multiple videos

### ISSUE THREAD

**Issue by Jamil-Palma** [THUDM/CogVideo#450]
### System Info / 系統信息

Hello! I had a question about generating multiple videos for the same prompt. I tried this input, but it only generates 1 video. I tried changing the output directory format, but it doesn’t save the 2 videos. What else should I change?  

`python inference/cli_demo.py --prompt "A gathering of friends celebrating the release of a video game very joyfully!" --model_path "THUDM/CogVideoX-2b" --output_path "./video_2/output1.mp4" --dtype "float16" --num_inference_steps 50 --guidance_scale 5.0 --num_videos_per_prompt 2`

my output
.../CogVideo/video_2$ ls
output1.mp4

Best regards

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

`python inference/cli_demo.py --prompt "A gathering of friends celebrating the release of a video game very joyfully!" --model_path "THUDM/CogVideoX-2b" --output_path "./video_2/output1.mp4" --dtype "float16" --num_inference_steps 50 --guidance_scale 5.0 --num_videos_per_prompt 2`

### Expected behavior / 期待表现

.../CogVideo/video_2$ ls
output1.mp4 output1_2.mp4 

or similar
2 videos generated by model

**Comment by zRzRzRzRzRzRzR** [comment]
If you want to save multiple videos, you should not just export videos[0]
You should use a for loop, and each produced video needs to be exported
