### ISSUE TITLE
卡数增加，loss逐渐变大

### ISSUE THREAD

**Issue by CCchenxiaoxue** [THUDM/CogVideo#451]
超级棒的工作！！！在finetune的时候遇到一些问题，想请教下，在训练的时候使用1e-5学习率，40卡训练还正常，loss比较稳定；但是换成100卡就开始loss增大，逐渐发散，想问下这种情况可以怎么改善吗？

**Comment by zRzRzRzRzRzRzR** [comment]
loss开始增大是什么地方，需要具体复现一下，一开始就一直在增大么

**Comment by CCchenxiaoxue** [comment]
在其他配置都不变的情况下，loss大概在迭代1～2k steps之后开始增大，是逐渐变大的，没有突变，尝试了改变学习率，也没有什么明显的改善

**Comment by zRzRzRzRzRzRzR** [comment]
你这个开始变大的地方loss具体数字多少

**Comment by CCchenxiaoxue** [comment]
大概在0.13以内，上下波动，后面逐步增加到0.8甚至更高

**Comment by zRzRzRzRzRzRzR** [comment]
估计已经达到了拟合的极限，如果你在0.13左右的这个loss的到的视频符合预期，则已经训练好
