### ISSUE TITLE
请教下16:9的模型怎么finetune呢

### ISSUE THREAD

**Issue by syyxsxx** [THUDM/CogVideo#452]
### System Info / 系統信息

.

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

使用了16:9的数据（1920*1080）在设置w=1024 h=576来finetune lora，结果出来效果很差
https://storage.googleapis.com/trimed_data/16/3.mp4（prompt:A girl riding a bike)
请教下如果要finetune 16:9的模型 应该怎么做呢

### Expected behavior / 期待表现

期待能获得帮助

**Comment by zRzRzRzRzRzRzR** [comment]
如果分辨率不是720 * 480 ，则无法使用官方的脚本进行微调，可以使用 cogvideox-factory
