### ISSUE TITLE
What is the difference between DDIMScheduler and CogVideoXDDIMScheduler from diffusers?

### ISSUE THREAD

**Issue by RahulSajnani** [THUDM/CogVideo#454]
What is the difference between DDIMScheduler and CogVideoXDDIMScheduler from diffusers? I have tried some experiments with both and this model seems to work only with CogVideoXDDIMScheduler. From initial glance of the code it seems like an algebraic manipulation of v prediction. But when I switch the schedulers with the same configs it does not seem to generate accurate videos.

**Comment by RahulSajnani** [comment]
I found it. For others wondering about the same. The difference is the snr_scale_shift [here](https://github.com/huggingface/diffusers/blob/89e4d6219805975bd7d253a267e1951badc9f1c0/src/diffusers/schedulers/scheduling_ddim_cogvideox.py#L211-L220).

**Comment by DanahYatim** [comment]
There is also this difference - 
```
 a_t = ((1 - alpha_prod_t_prev) / (1 - alpha_prod_t)) ** 0.5
 b_t = alpha_prod_t_prev**0.5 - alpha_prod_t**0.5 * a_t
 prev_sample = a_t * sample + b_t * pred_original_sample
```

in line 391 - [https://github.com/huggingface/diffusers/blob/89e4d6219805975bd7d253a267e1951badc9f1c0/src/diffusers/schedulers/scheduling_ddim_cogvideox.py#L391](url)

Do yo know why this difference appears?

**Comment by RahulSajnani** [comment]
This is just an algebraic change of the DDIM scheduler equation. Its the same. I have tried to make the changes in snr_scale and used it with the regular ddim scheduler and it worked fine.
