### ISSUE TITLE
注入可控条件

### ISSUE THREAD

**Issue by linwenzhao1** [THUDM/CogVideo#456]
### System Info / 系統信息

ubuntu20.04/python3.10

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

none

### Expected behavior / 期待表现

你好，问下cogvdeo能对前几帧加mask，根据前几帧和文本生成后续的帧吗？以及有没尝试过加入controlnet等一些控制条件？

**Comment by zRzRzRzRzRzRzR** [comment]
没有试过诶，人员都在做模型训练
