### ISSUE TITLE
ModuleNotFoundError: No module named 'yuki_builder'

### ISSUE THREAD

**Issue by gobigrassland** [THUDM/CogVideo#457]
### System Info / 系統信息

Unrelated to system information

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

when run Keyframe-Extraction-for-video-summarization-caption/src/04-1-batch_catption_csv.py,  I encounter the following error:
```
ModuleNotFoundError: No module named 'yuki_builder'.
```

### Expected behavior / 期待表现

where can I download and install this Python library?

**Comment by gobigrassland** [comment]
https://github.com/LC1332/Chat-Haruhi-Suzumiya/tree/main/yuki_builder.   Is it this project?

**Comment by zRzRzRzRzRzRzR** [comment]
yuki_builder 这个是哪个代码中运行的，没有看到这个代码

**Comment by gobigrassland** [comment]
1、本项目README.md 中 [technical documentation](https://zhipu-ai.feishu.cn/wiki/DHCjw1TrJiTyeukfc9RceoSRnCh)  中提到的。应该需要https://github.com/LC1332/Chat-Haruhi-Suzumiya/tree/main/yuki_builder
2、看了论文有关数据构建这部分，通过6个视频分类器、计算美学分数/光流分数来实现。 （1）看视频分类的TP指标也不算高，如果使用20000条数据来训练，这个视频过滤效果是不是还有较大提升空间。（2）论文没有提到原始视频可能包含多个转场镜头，视频中重复的内容或者主题分布不均的视频等。不知是否有更详细的数据构建说明，感觉这个数据构建的质量和数据规模对视频生成任务是相当重要的。

**Comment by zRzRzRzRzRzRzR** [comment]
@glide-the 能看一下吗

**Comment by glide-the** [comment]
> 1、本项目README.md 中 [technical documentation](https://zhipu-ai.feishu.cn/wiki/DHCjw1TrJiTyeukfc9RceoSRnCh) 这个数据处理文档中提到的。应该需要https://github.com/LC1332/Chat-Haruhi-Suzumiya/tree/main/yuki_builder
> 
> 2、看了论文有关数据构建这部分，通过6个视频分类器、计算美学分数/光流分数来实现。 （1）看视频分类的TP指标也不算高，如果使用20000条数据来训练，这个视频过滤效果是不是还有较大提升空间。（2）论文没有提到原始视频可能包含多个转场镜头，视频中重复的内容或者主题分布不均的视频等。不知是否有更详细的数据构建说明，感觉这个数据构建的质量和数据规模对视频生成任务是相当重要的。


这个脚本确实是凉宫春日的封装，用来抽取视频字幕的，用于1.0版本在部分指令维度上的数据收集工作，比如：人类动作、空间关系、多个对象这几个维度

关于论文的说明的脚本实际上是一个庞大的工程，我们不准备开源，也许opensora仓库有一些你想要的内容

后续有什么问题请继续沟通
