### ISSUE TITLE
[Q]: Question about the training compute scale

### ISSUE THREAD

**Issue by rlsu9** [THUDM/CogVideo#46]
Hi, thanks for your impressive works, could you please give more details about how many compute you used to train this model? Thanks a lot!

**Comment by zRzRzRzRzRzRzR** [comment]
We apologize, but due to the involvement of our company’s commercial models, we are unable to disclose these details at this time. We sincerely regret any inconvenience this may cause.

**Comment by rlsu9** [comment]
Understand, Thank for your feedback.
