### ISSUE TITLE
关于 sat 中 guider 的疑问

### ISSUE THREAD

**Issue by zhaohm14** [THUDM/CogVideo#463]
您好！

我注意到在配置文件中<https://github.com/THUDM/CogVideo/blob/3710a612d8760f5cdb1741befeebb65b9e0f2fe0/sat/configs/cogvideox_5b.yaml#L140> VPSDEDPMPP2MSampler 和 DynamicCFG 的 num_steps 都设置为 50。

而在调用 guider 时<https://github.com/THUDM/CogVideo/blob/3710a612d8760f5cdb1741befeebb65b9e0f2fe0/sat/sgm/modules/diffusionmodules/sampling.py#L518>使用了`self.num_steps - timestep`来计算`step_index`，其中`self.num_steps = 50`，而`timestep`取值范围是 999 到 19，使得`step_index`的范围是 -949 到 31。这导致 scale 在 1 到 7 之间以“无规律”的方式波动。

我认为，这里似乎应考虑使用`self.num_steps - idx`来代替，以确保`scale_value`沿着`scale_scaduler`平滑取值？

**Comment by yzy-thu** [comment]
issue #267  has explained this question.
