### ISSUE TITLE
How do you perform image-video joint training?

### ISSUE THREAD

**Issue by shiyi-zh0408** [THUDM/CogVideo#467]
### System Info / 系統信息

N/A

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

N/A

### Expected behavior / 期待表现

非常棒的工作！
我有几个问题：
1. 如何进行图片训练？paper中提到采用了联合训练方式，但是图片的T维度为1，要如何通过3D Encoder？
2. 代码中似乎没有paper中的Frame Pack方案，那么在训练的时候只能设置batch size为1吗？
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/93ecbf05-ca96-4af6-a666-eb83000efd83">
3. 目前main branch中i2v的代码在concat image condition的部分cat的是一个纯噪声

**Comment by songyang86** [comment]
+1

**Comment by yzy-thu** [comment]
1. CogVideoX encoder support encoding image 
2. We will release an open-source training framework based on Megatron in the future, supporting Frame pack training, as well as context parallel and tensor parallel.

**Comment by yzy-thu** [comment]
You can use bucketed training now, for example, using a larger batch size for images and a smaller batch size for videos on different GPU at the same time.

**Comment by shiyi-zh0408** [comment]
好的，感谢解答～

**Comment by wenqixu99** [comment]
> 1. CogVideoX encoder support encoding image, we do a special process for the first frame of the video
> 2. We will release a training framework based on Megatron in the future, supporting Frame pack training, as well as context parallel and tensor parallel.

@yzy-thu Hi, could you please let me know if the training framework based on Megatron in the second point, "including Frame pack training, as well as context parallel and tensor parallel", is still planned to be open-sourced? Thank you.

**Comment by johnren-code** [comment]
Same question, frame pack seems not open-sourced now.
