### ISSUE TITLE
How to image to video?

### ISSUE THREAD

**Issue by MrsZ** [THUDM/CogVideo#47]

**Comment by trouble-maker007** [comment]
@zRzRzRzRzRzRzR any plan to release checkpoint on image to video still have to improve, or does CogVideo support finetune method like [this](https://github.com/aigc-apps/EasyAnimate/issues/58)

**Comment by zRzRzRzRzRzRzR** [comment]
It seems this model cannot support generating videos from images.

The structure is somewhat different, so it cannot be resolved through fine-tuning either. So sad.

**Comment by trouble-maker007** [comment]
@zRzRzRzRzRzRzR Thank you for the answer, I will carefully read the official technical report.
