### ISSUE TITLE
Collaboration with xDiT, where xDiT is a DiT parallel inference framework

### ISSUE THREAD

**Issue by feifeibear** [THUDM/CogVideo#48]
We greatly appreciate the open-source efforts of CogVideo, which have been very helpful in advancing the field of video generation.

To achieve real-time generation, the DiT model must be deployed in parallel across multiple devices, and xDiT is designed to address this challenge.

https://github.com/xdit-project/xDiT

We plan to use xDiT to enable parallel inference for CogVideo. After applying xDiT, this project can explore larger models and more computationally intensive innovations to achieve better generation performance.

We look forward to receiving feedback from your team!

**Comment by zRzRzRzRzRzRzR** [comment]
Delighted to hear about your support! We also look forward to optimizations in parallel processing and welcome any exchanges. We eagerly anticipate faster and more cost-effective deployments in the future. ❤️
