### ISSUE TITLE
模型报错

### ISSUE THREAD

**Issue by anmingan** [THUDM/CogVideo#481]
### System Info / 系統信息

python 3.11 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

ValueError: /home/CogVideo/models/CogVideoX-5b/transformer/ does not appear to have a file named /home/CogVideo/models/CogVideoX-5b/transformer/diffusion_pytorch_model-00001-of-00002.safetensors which is required according to the checkpoint index.

### Expected behavior / 期待表现

正常运行

**Comment by anmingan** [comment]
1

**Comment by anmingan** [comment]
![image](https://github.com/user-attachments/assets/0edec0b5-3c4a-4f98-87bf-06438546b422)

**Comment by zRzRzRzRzRzRzR** [comment]
模型没下全吧
