### ISSUE TITLE
comfyui使用时报错models\CogVideo\CogVideo2B路径下需要config.json文件

### ISSUE THREAD

**Issue by Siwenyutou** [THUDM/CogVideo#483]
### System Info / 系統信息

Python 3.10.11

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

# ComfyUI Error Report
## Error Details
- **Node Type:** DownloadAndLoadCogVideoModel
- **Exception Type:** OSError
- **Exception Message:** Error no file named config.json found in directory E:\ComfyUI-aki-v1.4\ComfyUI-aki-v1.4\models\CogVideo\CogVideo2B.

### Expected behavior / 期待表现

正常运行

**Comment by zRzRzRzRzRzRzR** [comment]
这个是不是应该到对应的仓库提一下PR。主分支没有维护到这个部分。

**Comment by Siwenyutou** [comment]
@zRzRzRzRzRzRzR 
> 这个不是应该到对应的仓库提一下PR。主分支没有维护到这个部分。
不好意思，我没明白你的意思。
我确保所有东西都与库里的对应，且使用5b-I2V的模型就不会出现这个问题。
