### ISSUE TITLE
Preparing dataset for training CogVideo1.5 I2V 

### ISSUE THREAD

**Issue by Closertodeath** [THUDM/CogVideo#486]
### System Info / 系統信息

Linux, otherwise N/A

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

[Here](https://github.com/THUDM/CogVideo/tree/main/sat#fine-tuning-the-model) it only provides information on how to prepare the dataset for text to video. There is no information for I2V.

### Expected behavior / 期待表现

Information on how to prepare a dataset for image to video.

**Comment by Closertodeath** [comment]
> Similarly, I2V means that the first frame of the video is the Image. The code will automatically capture it.

Does any resolution work similarly to how i2v currently works or does it need to be a set resolution?

**Comment by zRzRzRzRzRzRzR** [comment]
Need fixed, for example, CogVideoX1.0 is 720 * 480
Regarding CogVideoX1.5, it supports 768-1360 (long edge) and 768 short edge. However, there is currently no manpower available to invest in writing the specific fine-tuning code, and it is expected to continue using CogVideoX-Factory as the fine-tuning framework for open-source models.

**Comment by aikitoria** [comment]
> Regarding CogVideoX1.5, it supports 768-1360 (long edge) and 768 short edge

Is vertical video (i.e. 768x1360) meant to be supported? It always becomes blurry when I try.

**Comment by zRzRzRzRzRzRzR** [comment]
No, only CogVideoX1.5-I2V is supported; other models must strictly adhere to the resolution mentioned in the readme and cannot use portrait orientation.
