### ISSUE TITLE
请问如何开启公网监听呢

### ISSUE THREAD

**Issue by anmingan** [THUDM/CogVideo#487]
### System Info / 系統信息

python 3.11

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/b7938493-9b71-4729-bb7b-46dde3042adb)

### Expected behavior / 期待表现

开启公网监听，同一局域网下能访问

**Comment by zRzRzRzRzRzRzR** [comment]
share=True 并且内网穿透
