### ISSUE TITLE
Where is the BaseModel?

### ISSUE THREAD

**Issue by xesdiny** [THUDM/CogVideo#49]
In [dit_video_concat.py](https://github.com/THUDM/CogVideo/blob/f9655e78bd96434f58f6639362eaa42fac8a73ed/sat/dit_video_concat.py#L9) line:9
```
...
from sat.model.base_model import BaseModel, non_conflict
from sat.model.mixins import BaseMixin
...
```
Can I find the relevant structure in [diffusers](https://github.com/huggingface/diffusers.git)? From the [paper](https://github.com/THUDM/CogVideo/blob/main/resources/CogVideoX.pdf), I see that the whole Framework is basically based on open-sora-plan 3d causal VAE + SD3.0 with Temporal Block added?

**Comment by zRzRzRzRzRzRzR** [comment]
we added the pr here
https://github.com/huggingface/diffusers/pull/9082/
with unsample downsample Our VAE and other block
