### ISSUE TITLE
V1.5版本生成视频闪烁

### ISSUE THREAD

**Issue by DidiD1** [THUDM/CogVideo#492]
### System Info / 系統信息

None

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

https://github.com/user-attachments/assets/b996a3d3-3994-41cd-8f20-dd836255fdb0

A panda, dressed in a small, red jacket and a tiny hat, sits on a wooden stool in a serene bamboo forest. The panda's fluffy paws strum a miniature acoustic guitar, producing soft, melodic tunes. Nearby, a few other pandas gather, watching curiously and some clapping in rhythm. Sunlight filters through the tall bamboo, casting a gentle glow on the scene. The panda's face is expressive, showing concentration and joy as it plays. The background includes a small, flowing stream and vibrant green foliage, enhancing the peaceful and magical atmosphere of this unique musical performance.
测试了几个case，发现1.5版本的文本following强很多，但是为什么会出现闪烁，已经上面的case里，周围的熊猫很奇怪，V1版本好像没有这个问题。

### Expected behavior / 期待表现

如何改善生成质量

**Comment by zRzRzRzRzRzRzR** [comment]
1.5版本在发布第一个版本可能配置没有正确，但是模型权重是正确的，确保使用diffusers最新的依赖和最新的HF模型仓库来进行使用。
