### ISSUE TITLE
音频支持

### ISSUE THREAD

**Issue by anmingan** [THUDM/CogVideo#495]
### System Info / 系統信息

python3.11

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

请问 CogVideo 支持输出带有音频的视频吗

### Expected behavior / 期待表现

视频带有声音

**Comment by zRzRzRzRzRzRzR** [comment]
没有，CogVideoX没训练音频。这是视频生成
