### ISSUE TITLE
size mismatch of cogvideox_2b

### ISSUE THREAD

**Issue by whycoming** [THUDM/CogVideo#497]
### System Info / 系統信息

  sd = torch.load(checkpoint_name, map_location='cpu')
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data1/CogVideo-sat/train_video.py", line 223, in <module>
[rank0]:     training_main(
[rank0]:   File "/usr/local/lib/python3.10/site-packages/sat/training/deepspeed_training.py", line 98, in training_main
[rank0]:     args.iteration = load_checkpoint(model, args)
[rank0]:   File "/usr/local/lib/python3.10/site-packages/sat/training/model_io.py", line 304, in load_checkpoint
[rank0]:     missing_keys, unexpected_keys = module.load_state_dict(sd['module'], strict=False)
[rank0]:   File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
[rank0]:     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
[rank0]: RuntimeError: Error(s) in loading state_dict for SATVideoDiffusionEngine:
[rank0]:        size mismatch for model.diffusion_model.mixins.patch_embed.proj.weight: copying a param with shape torch.Size([1920, 16, 2, 2]) from checkpoint, the shape in current model is torch.Size([1920, 128]).
[rank0]:        size mismatch for model.diffusion_model.mixins.final_layer.linear.weight: copying a param with shape torch.Size([64, 1920]) from checkpoint, the shape in current model is torch.Size([128, 1920]).
[rank0]:        size mismatch for model.diffusion_model.mixins.final_layer.linear.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

I try to run_cmd="$environs python train_video.py --base configs/cogvideox_2b.yaml configs/sft.yaml --seed 123456".
I change "patch_size: 2" to "patch_size: [2,2,2]" in cogvideox_2b.yaml
finally ,I meet this bug

### Expected behavior / 期待表现

11111111111

**Comment by jh-ops** [comment]
It's a version problem. Change dit_video_concat.py to this one "https://github.com/bertjiazheng/CogVideo/blob/dev/sat/dit_video_concat.py"
