### ISSUE TITLE
Details about training data?

### ISSUE THREAD

**Issue by hkunzhe** [THUDM/CogVideo#50]
In the report, I did not see the source and scale of the training data. Could you please provide more details?

**Comment by zRzRzRzRzRzRzR** [comment]
This part of the information involves our partner organizations and commercialization models, so it is not convenient to disclose it at this time. Thank you for your support and understanding.

**Comment by yzy-thu** [comment]
We use approximately 35M single-shot clips after filtering, which each clip averaging about 6 seconds.

**Comment by ethanhe42** [comment]
hi, in the report, image-video joint training is performed. would you mind sharing how many images are used?

**Comment by yzy-thu** [comment]
@ethanhe42 We used the aes-filtered LAION-5b for training
