### ISSUE TITLE
CogvideX-Interpolation with CogVideoX1.5-5B-SAT or CogVideoX-5b-I2V

### ISSUE THREAD

**Issue by Suprhimp** [THUDM/CogVideo#504]
### Feature request  / 功能建议

Hi, first of all thanks for the amazing model. :)

I'm just qurious is there any way to use CogVideoX-5B model on CogvideoX-Interpolation method.

It seems similar model structure but it is little bit different to me.

Is there any manual to use CogVideoX-5B model or sat model for interpolation only?

### Motivation / 动机

Actually, image to video is my own purpose but it seems not perfect that what I prompt it. Now I'm testing with interpolation. 
img2video but last frame is generated by imagegeneration.

### Your contribution / 您的贡献

If i get an hint, Maby I can make an example code or manual. :)

**Comment by zRzRzRzRzRzRzR** [comment]
这个项目是不是基于diffusers版本的，我们马上就推出了。

**Comment by nitinmukesh** [comment]
I am also interested in video interpolation project.
Is the placeholder github created so I can watch.

**Comment by zRzRzRzRzRzRzR** [comment]
We have released the version of diffusers, now you can give it a try, please download the diffusers library from the source code and run the diffusers model we open-sourced on Hugging Face.

**Comment by Suprhimp** [comment]
Where can I find the diffusers model of interpolation? I can't find it..

**Comment by Suprhimp** [comment]
@zRzRzRzRzRzRzR 
I tried to load CogVideoX1.5-5B diffusers in interpolation pipeline but it failed
`assert len(timesteps.shape) == 1, "Timesteps should be a 1d-array"`

Is there any way to use CogVideoX1.5-5B with interpolation method?
