### ISSUE TITLE
'CogVideoXTransformer3DModel' object has no attribute 'ofs_embedding'

### ISSUE THREAD

**Issue by JWargrave** [THUDM/CogVideo#512]
### System Info / 系統信息

已经安装(from source)了最新的diffusers（`0.32.0.dev0`）

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

根据[这里](https://huggingface.co/THUDM/CogVideoX1.5-5B-I2V#getting-started-quickly-%F0%9F%A4%97)的提示，运行以下代码时遇到了报错`AttributeError: 'CogVideoXTransformer3DModel' object has no attribute 'ofs_embedding'`
```python
import torch
from diffusers import CogVideoXImageToVideoPipeline
from diffusers.utils import export_to_video, load_image

pipe = CogVideoXImageToVideoPipeline.from_pretrained(
    "./pretrained_weights/CogVideoX1.5-5B-I2V",
    torch_dtype=torch.bfloat16
)
```

### Expected behavior / 期待表现

`ofs_embedding`是什么？

**Comment by jinqiupeter** [comment]
Same error. I've already installed diffusers from https://github.com/huggingface/diffusers/pull/9877

**Comment by a-r-r-o-w** [comment]
cc @zRzRzRzRzRzRzR 

Could you try using the official weights from [here](https://huggingface.co/THUDM/CogVideoX1.5-5B-I2V)? I see that ofs_embedding does exist in the safetensors as well as Diffusers PR, and verified it works on my end.

![image](https://github.com/user-attachments/assets/39da5f3f-3ebd-4a21-b740-82ab76bf9154)

We just merged the PR to main branch, so could you also try reinstalling it?

**Comment by JWargrave** [comment]
> cc @zRzRzRzRzRzRzR
> 
> Could you try using the official weights from [here](https://huggingface.co/THUDM/CogVideoX1.5-5B-I2V)? I see that ofs_embedding does exist in the safetensors as well as Diffusers PR, and verified it works on my end.
> 
> ![image](https://private-user-images.githubusercontent.com/72266394/387360337-39da5f3f-3ebd-4a21-b740-82ab76bf9154.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5ODU5MDcsIm5iZiI6MTczMTk4NTYwNywicGF0aCI6Ii83MjI2NjM5NC8zODczNjAzMzctMzlkYTVmM2YtM2ViZC00YTIxLWI3NDAtODJhYjc2YmY5MTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDAzMDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMTQ0ZjgxYzE0OGZhZWFkMzY3ZWQ0ZmRmM2IxOTQ2ZjcwNGZiNTc0OTZlNmNiNzA3ZDZiZmExNzJiOTgyMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JPMQGCoeTfEgml1rzmqr-giFE1IzbckmGnV7RvhwFrk)
> 
> We just merged the PR to main branch, so could you also try reinstalling it?

I reinstalled the latest diffusers and the problem was solved. Because the CogVideoX code in the diffusers has just been [updated](https://github.com/huggingface/diffusers/commit/3b2830618ddff967a1f3a1307a15e24a75c7ae6e)

**Comment by gulucaptain** [comment]
This issue is due to the version of diffusers. I tried an off-line way to solve this problem:
1) download the source file from: https://github.com/zRzRzRzRzRzRzR/diffusers; you will get a zip file "diffusers-main.zip".
2) directly run: pip install diffusers-main.zip.

**Comment by ChilloKing1992** [comment]
> This issue is due to the version of diffusers. I tried an off-line way to solve this problem:
> 
> 1. download the source file from: https://github.com/zRzRzRzRzRzRzR/diffusers; you will get a zip file "diffusers-main.zip".
> 2. directly run: pip install diffusers-main.zip.

Hey, can u explain to me where i have to run this? i have the same issue and i am a complete beginner. Do i run this in python? or in a adress bar with cmd? An answer as detailed as possible would be very appreciated :D

**Comment by gulucaptain** [comment]
> > This issue is due to the version of diffusers. I tried an off-line way to solve this problem:
> > 
> > 1. download the source file from: https://github.com/zRzRzRzRzRzRzR/diffusers; you will get a zip file "diffusers-main.zip".
> > 2. directly run: pip install diffusers-main.zip.
> 
> Hey, can u explain to me where i have to run this? i have the same issue and i am a complete beginner. Do i run this in python? or in a adress bar with cmd? An answer as detailed as possible would be very appreciated :D

Hi, when u have activated your python envs, please directly run "pip install diffusers-main.zip" in cmd.

**Comment by kejie7243** [comment]
What is ofs embedding? what does OFS stand for? Thanks! : )
