### ISSUE TITLE
T2V inference getting bad results

### ISSUE THREAD

**Issue by YanzuoLu** [THUDM/CogVideo#520]
### System Info / 系統信息

Diffusers install from source, latest huggingface weight with fixed transformer sample size

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

default inference code in [huggingface repo](https://huggingface.co/THUDM/CogVideoX1.5-5B)

### Expected behavior / 期待表现

clear videos, the following is the bad results I get of 81 frames (8 fps, 4 videos concated)

https://github.com/user-attachments/assets/340506b5-b3d8-4ac2-a496-7020d6dad30f

**Comment by nitinmukesh** [comment]
Post pip list here.

Also try this and post result (you can change prompt)
python inference\cli_demo.py --prompt "A butterfly flying over flowers." --num_inference_steps 50 --model_path THUDM/CogVideoX1.5-5b --generate_type "t2v"

**Comment by YanzuoLu** [comment]
Hi @nitinmukesh 
I'm sure the current inference code on t2v repo is problematic without specifying sample size (height and width) since this script now takes more than 200s for one step on H100...

16%|███████████████▎                                                                                | 8/50 [31:45<2:46:44, 238.21s/it]

**Comment by YanzuoLu** [comment]
I'm wondering what this [fix](https://huggingface.co/THUDM/CogVideoX1.5-5B/commit/6b80d8556f820bf58e4e9719ec71450aff55c246) means actually...
This make the target sample video to be 300 x 8(vae temporal upsample)=2400p

**Comment by lbwang2006** [comment]
I have met the same problem with diffusers==0.32.0

**Comment by YanzuoLu** [comment]
Here is the results after setting height and width...

https://github.com/user-attachments/assets/10a24c42-7db0-4138-9149-fea01dcc047d

**Comment by YanzuoLu** [comment]
Hi @a-r-r-o-w 
It looks to be working well now. Thank you so much.
Don't apologize haha~ I really love to read codes from diffusers team : )
One thing to note is the max_sequence_length, it seems to be maximum at 224 in CogVideoX-1.5, maybe it is helpful to change that default parameters for pipeline and [huggingface model repo](https://huggingface.co/THUDM/CogVideoX1.5-5B/blob/main/transformer/config.json#L11).
And I see both **use_dynamic_cfg** and **CogVideoXDPMScheduler** enabled in the [original repo cli demo](https://github.com/THUDM/CogVideo/blob/main/inference/cli_demo.py), I'm wondering are they suggested settings for 1.5 model since this behavior is also different from the [huggingface model repo](https://huggingface.co/THUDM/CogVideoX1.5-5B/blob/main/scheduler/scheduler_config.json).
I'm now running inference to see how these parameters affect the results...

**Comment by a-r-r-o-w** [comment]
> One thing to note is the max_sequence_length, it seems to be maximum at 224 in CogVideoX-1.5, maybe it is helpful to change that default parameters for pipeline and [huggingface model repo](https://huggingface.co/THUDM/CogVideoX1.5-5B/blob/main/transformer/config.json#L11).

This was done in SAT codebase to support context-parallel (so that can be distributed evenly across multiple GPUs more easily) based on my discussion with @zRzRzRzRzRzRzR. The correct max sequence length is 226 I think for all the Cog models.

Thanks for understanding and the kind words!

**Comment by zigchang** [comment]
@YanzuoLu Have your solved this problem? 
I have met the same situation,  As the project owner@zRzRzRzRzRzRzR  mentioned, a few places that need to be revised:
1 Update huggingface's CogVideoX1.5-5B latest commit regarding the T2V model (Yes, have revised the "sample_height" and "sample_width" to 300)
2 Update the source code and install the diffusers library (Done)
3 Since it's A100, you can use pipe.to("cuda"). (Done)

I have done all these three steps, but still have very slow inference speed like followings:
![image](https://github.com/user-attachments/assets/e4ba755a-41ff-4cf1-813f-dbcd40ac5ea9)
![image](https://github.com/user-attachments/assets/89eae39e-4c9b-4387-ac71-1d63f0ba12fc)

**Comment by YanzuoLu** [comment]
@zigchang You need to use the api from_pretrained with torch_dtype=torch.bfloat16

**Comment by YanzuoLu** [comment]
One more thing, you need to set up height and width to 768 and 1360 yourself.

**Comment by zigchang** [comment]
> One more thing, you need to set up height and width to 768 and 1360 yourself.

I have run it in bf16, but I still don't know the meaning of changes in transformer config:
https://github.com/THUDM/CogVideo/issues/520#issuecomment-2490281689

**Comment by YanzuoLu** [comment]
No, the fix here is about positional embedding.
You still need to set the height and width in pipeline call.

**Comment by a-r-r-o-w** [comment]
The change to 300 is so that both the SAT and Diffusers implementation match exactly when creating the RoPE embeddings. When generating with Diffusers, please make sure to pass the `height` and `width` parameters so as to not use the defaults (which would be `spatial_scale_factor` * 300 -> 8 * 300 -> 2400 as the resolution)

**Comment by YanzuoLu** [comment]
Hi @a-r-r-o-w 
Thanks to have you here.
Could you plz take a look at this [issue](https://github.com/THUDM/CogVideo/issues/527)?
I'm going to close the current issue since it has been solved.

**Comment by zigchang** [comment]
OK,  I see. Thank you all. 
<img width="738" alt="image" src="https://github.com/user-attachments/assets/6c4a79a3-94c9-4c09-9f7a-87da49e352dc">
The cli_demo.py does not set the he height and width in pipeline call, this may be a little bit confusing.

**Comment by a-r-r-o-w** [comment]
Gentle ping @zRzRzRzRzRzRzR to set the height and width in the script for the 1.5 models because we can't determine default height and width from config due to different RoPE implementation. Not passing height and width will work as expected only for the 1.0 models 😅

**Comment by sunshinewhy** [comment]
> Here is the results after setting height and width...
> 
>  output.mp4

Hi~I occur the same problem, can you tell me how to fix it? Thanks!

**Comment by lbwang2006** [comment]
> > Here is the results after setting height and width...
> > output.mp4
> 
> Hi~I occur the same problem, can you tell me how to fix it? Thanks!

update the latest diffusers==0.32.0.dev

**Comment by huge123** [comment]
I encounter a similar problem. I have already updated the diffusers to 0.32.0.dev, set width and height to 1360 and 768 respectively, and set the number of frames as 49, but I got results similar to 

> Here is the results after setting height and width...
> 
>  output.mp4

Any suggestions I can try?
