### ISSUE TITLE
1.5版本的I2v模型如何支持768*1360

### ISSUE THREAD

**Issue by gongleii** [THUDM/CogVideo#521]
/CogVideo/inference# python cli_demo.py --width 768 --height 1360会出错   1360*768正常
Traceback (most recent call last):
  File "/CogVideo/inference/cli_demo.py", line 183, in <module>
    generate_video(
  File "/CogVideo/inference/cli_demo.py", line 115, in generate_video
    video_generate = pipe(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/CogVideo/diffusers/pipelines/cogvideo/pipeline_cogvideox_image2video.py", line 795, in __call__
    self._prepare_rotary_positional_embeddings(height, width, latents.size(1), device)
  File "/CogVideo/diffusers/pipelines/cogvideo/pipeline_cogvideox_image2video.py", line 564, in _prepare_rotary_positional_embeddings
    freqs_cos, freqs_sin = get_3d_rotary_pos_embed(
  File "/CogVideo/diffusers/models/embeddings.py", line 608, in get_3d_rotary_pos_embed
    cos = combine_time_height_width(t_cos, h_cos, w_cos)
  File "/CogVideo/diffusers/models/embeddings.py", line 591, in combine_time_height_width
    freqs = torch.cat(
RuntimeError: Sizes of tensors must match except in dimension 3. Expected size 85 but got size 48 for tensor number 1 in the list.

**Comment by gongleii** [comment]
diffusers 使用的是 ：https://github.com/zRzRzRzRzRzRzR/diffusers/tree/cogvideox1.1-5b
Try installing diffusers from here, as the PR has not been merged yet.

**Comment by nitinmukesh** [comment]
I think the model is trained on --width 1360 --height 768 dataset. You are trying reverse (portrait).

**Comment by CheWang1110** [comment]
一样的问题，cogvideox-1.5-5b只能生成横向视频吗？

**Comment by nitinmukesh** [comment]
@gongleii @CheWang1110 

You can request in this topic if you want support for vertical resolution.
https://github.com/THUDM/CogVideo/issues/194

**Comment by jinqiupeter** [comment]
But `--width 480 --height 720` works fine.

**Comment by zRzRzRzRzRzRzR** [comment]
已经支持了，请源代码安装最新的diffusers库和我在HF的最新一个commit

**Comment by MikeAiJF** [comment]
你好我运行app.py出现AttributeError: 'CogVideoXTransformer3DModel' object has no attribute 'ofs_embedding'这个错误应该怎么解决，希望得到帮助

**Comment by LettleCreator** [comment]
> 你好我运行app.py出现AttributeError: 'CogVideoXTransformer3DModel' object has no attribute 'ofs_embedding'这个错误应该怎么解决，希望得到帮助

用这个命令更新diffusers
pip install git+https://github.com/huggingface/diffusers.git

**Comment by MikeAiJF** [comment]
> > 你好我运行app.py出现AttributeError: 'CogVideoXTransformer3DModel' object has no attribute 'ofs_embedding' 这个错误应该怎么解决，希望得到帮助
> 
> 使用此命令更新diffusers pip install git+ https://github.com/huggingface/diffusers.git
这个错误我解决了，谢谢你的回答。
![image](https://github.com/user-attachments/assets/c9b17456-19bd-4a35-8f65-13f9ba80b6a9)
这个错误什么意思

**Comment by zRzRzRzRzRzRzR** [comment]
你是I2V吗，那需呀输入图像的

**Comment by MikeAiJF** [comment]
> 你是I2V吗，那需呀输入图像的

t2v

**Comment by MikeAiJF** [comment]
![image](https://github.com/user-attachments/assets/84df5cf4-b640-49d7-871a-4ec4c03dbd36)

**Comment by zRzRzRzRzRzRzR** [comment]
But did you use the I2V model? The T2V model doesn't have this ofs, are you sure you installed the latest diffusers source code?

**Comment by MikeAiJF** [comment]
你好，我想再问一下文生图的模型也能用新发布的模型吗，还是只能用2b和5b

**Comment by zRzRzRzRzRzRzR** [comment]
这个模型是文生视频的，文生图是cogview

**Comment by MikeAiJF** [comment]
> 这个模型是文生视频的，文生图是cogview

抱歉，我想再问一下现在的gradio是不是不能使用最新的模型进行生成

**Comment by zRzRzRzRzRzRzR** [comment]
不能 gradio是老的，新的没有做，通常这个相应时间已经超过gradio了，可能会掉线

**Comment by JunyaoHu** [comment]
> 已经支持了，请源代码安装最新的diffusers库和我在HF的最新一个commit

@zRzRzRzRzRzRzR 作者您好，请问“HF的最新一个commit”具体是哪一个？我想使用1.5x-5b-I2V模型生成宽768高1360的竖屏视频，但我现在遇到与题主描述完全一致的问题。谢谢！

@gongleii 题主您好，请问您解决这个问题了吗？我的遇到和你一样的问题，希望得到解决。

我使用宽768高1360的图像作为I2V输入

## 参考代码

```
model_path="...../CogVideoX1.5-5B-I2V"
image_or_video_path="...../myimage.jpg"
output_path="...../output.mp4"
python inference/cli_demo.py \
    --generate_type "i2v" \
    --model_path $model_path \
    --prompt "a woman, smiling" \
    --output_path $output_path \
    --image_or_video_path $image_or_video_path \
    --width xxx \
    --height xxx \
    --num_inference_steps 50 \
    --guidance_scale 3.5 \
    --seed 1000
```

## 实现效果

输入图像

![Image](https://github.com/user-attachments/assets/aaf98b12-107b-415c-ad89-a3d8972aa673)

使用三种参数进行生成：

`--width 768 --height 1360`

**不能实现**，报错同一内容，`RuntimeError: Sizes of tensors must match except in dimension 3. Expected size **85** but got size 48 for tensor number 1 in the list.` 数字一模一样

`--width 768 --height 1080`

**不能实现**，报错同一内容，`RuntimeError: Sizes of tensors must match except in dimension 3. Expected size **67** but got size 48 for tensor number 1 in the list.` **数字不一样**

`--width 768 --height 960`

**不能实现**，报错同一内容，`RuntimeError: Sizes of tensors must match except in dimension 3. Expected size **60** but got size 48 for tensor number 1 in the list.` **数字不一样**

`--width 1360 --height 768`

可以实现，画面也比较稳定，**图像经过拉伸**

https://github.com/user-attachments/assets/efd0c000-9ab8-4ddf-a712-fac5813d8fc3

`--width 480 --height 720`

可以实现，**画面很不稳定**，**图像经过拉伸**

https://github.com/user-attachments/assets/b4940a07-3c23-41e9-a2fc-e81e5d7aa7fc

`--width 720 --height 720`

可以实现，画面也比较稳定，**图像经过拉伸**

https://github.com/user-attachments/assets/9f426504-327c-4916-a6bc-81c4d21166d5

## 环境配置

环境中diffusers使用`pip install git+https://github.com/huggingface/diffusers.git`安装，版本为0.33.0.dev0

**Comment by JunyaoHu** [comment]
https://github.com/THUDM/CogVideo/issues/758

这里所提及的修改方法可能有帮助，在我修改后可以推理`--width 768 --height 1360`的视频，并且看起来很正常

https://github.com/user-attachments/assets/14009a1b-3dfa-4e10-a471-1aaa6df4c656
