### ISSUE TITLE
Question about 3d patchify

### ISSUE THREAD

**Issue by Blueskyvvvvv** [THUDM/CogVideo#524]
It's an excellent open-source work. Since it's found that the 1.5 model uses patchify in the temporal, Then it is required that the length of the latents in the time dimension should be divisible by the patch size.
 As I haven't found the update of the training dataset part, I'm not quite sure how to specifically ensure that the length of the latents is divisible by the patch size（2）. In addition, when looking at the code of the decoder, it will skip the first frame for decoding. So, was zero padding done at the position of the first frame or were other operations carried out? Thanks for answering.
![image](https://github.com/user-attachments/assets/7035fbc4-83c5-4117-8b01-8128f00ddd63)

**Comment by zRzRzRzRzRzRzR** [comment]
The first and second frames (ID 0 and 1) are the same, so the first frame should be discarded.

**Comment by Blueskyvvvvv** [comment]
> The first and second frames (ID 0 and 1) are the same, so the first frame should be discarded.

That mean, during training, does the first frame also need to be repeated once to ensure that the length of the latents is a multiple of 2?

**Comment by zRzRzRzRzRzRzR** [comment]
During training, the first frame is copied once to ensure that the length can be evenly divided by t_patch (2).

**Comment by Blueskyvvvvv** [comment]
> During training, the first frame is copied once to ensure that the length can be evenly divided by t_patch (2).

Thank you very much for your reply.
