### ISSUE TITLE
CogVideoX1.5-5B-I2V how to finetune

### ISSUE THREAD

**Issue by YLongJin** [THUDM/CogVideo#525]
can finetune CogVideoX1.5-5B-I2V？

**Comment by Florenyci** [comment]
same here, it's always OOM even in 80GB GPU...

**Comment by JWargrave** [comment]
> We are still preparing and testing, please use cogvideox-factry first.

Does cogvideox-factory support fully fine-tuning CogVideoX1.5-5B-I2V on image-to-video task?

**Comment by lijain** [comment]
> > We are still preparing and testing, please use cogvideox-factry first.
> 
> Does cogvideox-factory support fully fine-tuning CogVideoX1.5-5B-I2V on image-to-video task?

你好，请问你现在实现了cogvideox1.5的ft？

**Comment by Vincentyua** [comment]
同问，请问支持了全量微调吗？无论SAT还是cogvideox-factory @zRzRzRzRzRzRzR ，看到了lora的finetune

**Comment by zRzRzRzRzRzRzR** [comment]
全亮微调的实现和lora有一定区别，但是目前全量微调一定OOM，目前所有仓库都提供lora而非全量

**Comment by royvelich** [comment]
is there any way to finetune CogVideoX1.5-5B-I2V? is there a simple example that show how to make it work?

**Comment by lijain** [comment]
https://github.com/a-r-r-o-w/finetrainers
