### ISSUE TITLE
如何设置使得GPU显存为固定值

### ISSUE THREAD

**Issue by Ttttttttyj** [THUDM/CogVideo#528]
纯训练不做验证，显存波动特别大，sft模式下从20多G到接近80G，波动范围特别大，如何设置能实现持续保持在最大显存占用呢？

**Comment by zRzRzRzRzRzRzR** [comment]
你是不是sat跑的，diffusers版本由于提前encode了，所以占用是固定，sat没办法因为是边编码边训练的，速度很慢，推荐cogvideox-factory

**Comment by Ttttttttyj** [comment]
非常感谢您的解答。

不好意思，我没太理解边解码边训练的意思？为什么能做到编解码边训练呢？这样导致40G左右的显存波动吗？还有一个问题就是我在SATVideoDiffusionEngine.shared_step中，注释掉了torch.cuda.empty_cache()，实现了显存固定，这样做是否会有其他相关影响呢？

如果您能解答，将不胜感激！期待您的回复！

-----原始邮件-----
发件人:"Yuxuan.Zhang" ***@***.***>
发送时间:2024-11-20 18:06:34 (星期三)
收件人: THUDM/CogVideo ***@***.***>
抄送: Ttttttttyj ***@***.***>, Author ***@***.***>
主题: Re: [THUDM/CogVideo] 如何设置使得GPU显存为固定值 (Issue #528)






你是不是sat跑的，diffusers版本由于提前encode了，所以占用是固定，sat没办法因为是边编码边训练的，速度很慢，推荐cogvideox-factory

**Comment by zRzRzRzRzRzRzR** [comment]
因为你要先载入T5进行编码，这个是要显存的，接着你还要调用VAE进行编码。这俩的显存占用差不多是40G显存。

**Comment by Ttttttttyj** [comment]
哦哦哦，好的。感谢~

**Comment by Ttttttttyj** [comment]
> 因为你要先载入T5进行编码，这个是要显存的，接着你还要调用VAE进行编码。这俩的显存占用差不多是40G显存。

那这两部分训练过程相当于在编码结束后被移到cpu上了？不然的话，应该不会引起显存变化？我在训练代码里目前还没有明确看到相关代码

**Comment by Ttttttttyj** [comment]
非常感谢您的解答。
不好意思，我没太理解边解码边训练的意思？为什么能做到编解码边训练呢？这样导致40G左右的显存波动吗？还有一个问题就是我在SATVideoDiffusionEngine.shared_step中，注释掉了torch.cuda.empty_cache()，实现了显存固定，这样做是否会有其他相关影响呢？
如果您能解答，将不胜感激！期待您的回复！

发件人: Yuxuan.Zhang
发送时间: 2024年11月20日 18:06
收件人: THUDM/CogVideo
抄送: Ttttttttyj; Author
主题: Re: [THUDM/CogVideo] 如何设置使得GPU显存为固定值 (Issue #528)

你是不是sat跑的，diffusers版本由于提前encode了，所以占用是固定，sat没办法因为是边编码边训练的，速度很慢，推荐cogvideox-factory
