### ISSUE TITLE
Forward error for CogVidX-5B-I2V model

### ISSUE THREAD

**Issue by weihualiuhupituzi** [THUDM/CogVideo#529]
### System Info / 系統信息

Hi, when I run the code on CogVidX-5B-I2V model, I got the error as below in cogvideox_transformer_3d.py file:
```
output = hidden_states.reshape(batch_size, num_frames, height // p, width // p, channels, p, p)
RuntimeError: shape '[2, 13, 30, 45, 32, 2, 2]' is invalid for input of size 2246400
```
Would you please give me some support? thanks!

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

none

### Expected behavior / 期待表现

solve the prolbem

**Comment by crj1998** [comment]
保证视频宽高都能被16整除

**Comment by MikeAiJF** [comment]
> 保证视频宽高被16整除
![image](https://github.com/user-attachments/assets/2119a7d6-6315-4f58-a25b-68ab0dad437c)
哥们，这个错误什么原因

**Comment by zRzRzRzRzRzRzR** [comment]
长 宽 需要被16整除

**Comment by weihualiuhupituzi** [comment]
> 长 宽 需要被16整除

sure, the input of the image we setted as 720*480, however, it still get such error.  the shape[2, 13, 30, 45, 32, 2, 2], if you multiply each value toghter, it is twice larger than the input of the size 2246400.  It quite confuse.
