### ISSUE TITLE
CogVideoX1.5-5B t2v takes 6 hours to generate a video

### ISSUE THREAD

**Issue by zyx0328** [THUDM/CogVideo#530]
### System Info / 系統信息

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
accelerate                1.1.1                    pypi_0    pypi
aiofiles                  23.2.1                   pypi_0    pypi
aiohttp                   3.9.5                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
altair                    5.3.0                    pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     4.4.0                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
av                        12.3.0                   pypi_0    pypi
bert-score                0.3.13                   pypi_0    pypi
bitsandbytes              0.41.0                   pypi_0    pypi
boto3                     1.35.65                  pypi_0    pypi
botocore                  1.35.65                  pypi_0    pypi
braceexpand               0.1.7                    pypi_0    pypi
bzip2                     1.0.8                h5eee18b_6  
ca-certificates           2024.7.2             h06a4308_0  
certifi                   2024.2.2                 pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
contourpy                 1.2.1                    pypi_0    pypi
cpm-kernels               1.0.11                   pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
datasets                  2.16.1                   pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
decord                    0.6.0                    pypi_0    pypi
deepspeed                 0.12.2                   pypi_0    pypi
diffusers                 0.32.0.dev0              pypi_0    pypi
dill                      0.3.7                    pypi_0    pypi
distro                    1.9.0                    pypi_0    pypi
dnspython                 2.6.1                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
docstring-parser          0.16                     pypi_0    pypi
dropout-layer-norm        0.1                      pypi_0    pypi
einops                    0.6.1                    pypi_0    pypi
einops-exts               0.0.4                    pypi_0    pypi
email-validator           2.2.0                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
fastapi                   0.115.5                  pypi_0    pypi
fastapi-cli               0.0.4                    pypi_0    pypi
ffmpy                     0.3.2                    pypi_0    pypi
filelock                  3.14.0                   pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2023.10.0                pypi_0    pypi
ftfy                      6.2.0                    pypi_0    pypi
fused-dense-lib           0.0.0                    pypi_0    pypi
fvcore                    0.1.5.post20221221          pypi_0    pypi
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.43                   pypi_0    pypi
gradio                    5.6.0                    pypi_0    pypi
gradio-client             1.4.3                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
hf-transfer               0.1.8                    pypi_0    pypi
hjson                     3.1.0                    pypi_0    pypi
httpcore                  1.0.7                    pypi_0    pypi
httptools                 0.6.1                    pypi_0    pypi
httpx                     0.27.2                   pypi_0    pypi
huggingface-hub           0.26.2                   pypi_0    pypi
idna                      3.7                      pypi_0    pypi
imageio                   2.36.0                   pypi_0    pypi
imageio-ffmpeg            0.5.1                    pypi_0    pypi
iopath                    0.1.10                   pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
jiter                     0.7.1                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
latex2mathml              3.77.0                   pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
linkify-it-py             2.0.3                    pypi_0    pypi
llava                     1.7.0.dev0               pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markdown2                 2.5.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.9.1                    pypi_0    pypi
mdit-py-plugins           0.3.3                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
moviepy                   2.0.0                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.5                    pypi_0    pypi
multiprocess              0.70.15                  pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
networkx                  3.3                      pypi_0    pypi
ninja                     1.11.1.1                 pypi_0    pypi
numpy                     1.26.0                   pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.21.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.4.127                 pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
open-clip-torch           2.26.1                   pypi_0    pypi
openai                    1.54.5                   pypi_0    pypi
opencv-python-headless    4.10.0.84                pypi_0    pypi
openssl                   3.0.14               h5eee18b_0  
orjson                    3.10.6                   pypi_0    pypi
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
parameterized             0.9.0                    pypi_0    pypi
peft                      0.13.2                   pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.1.2                   pypi_0    pypi
portalocker               2.10.1                   pypi_0    pypi
proglog                   0.1.10                   pypi_0    pypi
protobuf                  4.25.3                   pypi_0    pypi
psutil                    6.0.0                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pyarrow                   17.0.0                   pypi_0    pypi
pyarrow-hotfix            0.6                      pypi_0    pypi
pycocoevalcap             1.2                      pypi_0    pypi
pycocotools               2.0.8                    pypi_0    pypi
pydantic                  2.9.2                    pypi_0    pypi
pydantic-core             2.23.4                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pynvml                    11.5.3                   pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
python                    3.10.14              h955ad1f_1  
python-dateutil           2.9.0.post0              pypi_0    pypi
python-dotenv             1.0.1                    pypi_0    pypi
python-multipart          0.0.12                   pypi_0    pypi
pytorchvideo              0.1.5                    pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
referencing               0.35.1                   pypi_0    pypi
regex                     2024.5.15                pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
rich                      13.7.1                   pypi_0    pypi
rouge                     1.0.1                    pypi_0    pypi
rpds-py                   0.19.0                   pypi_0    pypi
ruff                      0.7.4                    pypi_0    pypi
s3transfer                0.10.3                   pypi_0    pypi
safehttpx                 0.1.1                    pypi_0    pypi
safetensors               0.4.3                    pypi_0    pypi
scikit-learn              1.2.2                    pypi_0    pypi
scikit-video              1.1.11                   pypi_0    pypi
scipy                     1.14.0                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
sentencepiece             0.2.0                    pypi_0    pypi
sentry-sdk                2.10.0                   pypi_0    pypi
setproctitle              1.3.3                    pypi_0    pypi
setuptools                71.1.0                   pypi_0    pypi
shellingham               1.5.4                    pypi_0    pypi
shortuuid                 1.0.13                   pypi_0    pypi
shtab                     1.7.1                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.1                    pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0  
starlette                 0.41.3                   pypi_0    pypi
svgwrite                  1.4.3                    pypi_0    pypi
swissarmytransformer      0.4.12                   pypi_0    pypi
sympy                     1.13.1                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tensorboardx              2.6.2.2                  pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
timm                      1.0.7                    pypi_0    pypi
tk                        8.6.14               h39e8969_0  
tokenizers                0.20.3                   pypi_0    pypi
tomlkit                   0.12.0                   pypi_0    pypi
toolz                     0.12.1                   pypi_0    pypi
torch                     2.5.0+cu121              pypi_0    pypi
torch-geometric           2.5.3                    pypi_0    pypi
torchaudio                2.5.0+cu121              pypi_0    pypi
torchvision               0.20.0+cu121             pypi_0    pypi
tqdm                      4.66.4                   pypi_0    pypi
transformers              4.46.2                   pypi_0    pypi
triton                    3.1.0                    pypi_0    pypi
typer                     0.12.3                   pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tyro                      0.8.5                    pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
uc-micro-py               1.0.3                    pypi_0    pypi
urllib3                   1.26.19                  pypi_0    pypi
uvicorn                   0.30.3                   pypi_0    pypi
uvloop                    0.19.0                   pypi_0    pypi
wandb                     0.16.5                   pypi_0    pypi
watchfiles                0.22.0                   pypi_0    pypi
wavedrom                  2.0.3.post3              pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
webdataset                0.2.100                  pypi_0    pypi
websockets                12.0                     pypi_0    pypi
wheel                     0.43.0          py310h06a4308_0  
xentropy-cuda-lib         0.1                      pypi_0    pypi
xxhash                    3.4.1                    pypi_0    pypi
xz                        5.4.6                h5eee18b_1  
yacs                      0.1.8                    pypi_0    pypi
yarl                      1.9.4                    pypi_0    pypi
zlib                      1.2.13               h5eee18b_1  

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![1732096403121](https://github.com/user-attachments/assets/54e2578c-73c8-4382-af49-7f3d7d60b17d)

### Expected behavior / 期待表现

The readme says it only takes about 1000s to generate a video. What is the reason?

**Comment by zyx0328** [comment]
PS: I am running the code on A100 and it takes about 80GB memory. Maybe there is something wrong? tks!

**Comment by zRzRzRzRzRzRzR** [comment]
I believe there are a few places that need to be revised

1 Update huggingface's CogVideoX1.5-5B latest commit regarding the T2V model
2 Update the source code and install the diffusers library
3 Since it's A100, you can use pipe.to("cuda"), and it takes 15 minutes.

**Comment by MikeAiJF** [comment]
> 我认为有几个地方需要修改
> 
> 1 更新 huggingface 的 CogVideoX1.5-5B 关于 T2V 模型的最新提交 2 更新源代码并安装扩散器库 3 因为是 A100，所以可以使用 pipe.to("cuda")，需要 15 分钟。

![image](https://github.com/user-attachments/assets/933bbcd4-e4c0-4ae6-b26b-44ee147e554b)
你好，这个原因导致的，我重新安装的diffusers

**Comment by zyx0328** [comment]
I installed diffusers according to this: https://github.com/zRzRzRzRzRzRzR/diffusers/tree/cogvideox1.1-5b. I switched to the cogvideox1.1-5b branch first and then use "pip install -e .". Is that ok?

**Comment by zRzRzRzRzRzRzR** [comment]
No, it is the clone of the main branch, https://github.com/huggingface/diffusers and then pip install -e .

**Comment by zyx0328** [comment]
> No, it is the clone of the main branch, https://github.com/huggingface/diffusers and then pip install -e .

Actually I installed from the main branch at first but it has a problem: 
![1732097970328](https://github.com/user-attachments/assets/88e4beda-0b96-4cb5-be57-09c282a540c6)

**Comment by zRzRzRzRzRzRzR** [comment]
emm, is your model self-converted or are you using the CogVideoX1.5-5B model that we have converted, because if it's the latter, this issue wouldn't occur, right? If it's to be self-converted, first use the conversion code provided by the diffusers main branch: https://github.com/huggingface/diffusers/blob/main/scripts/convert_cogvideox_to_diffusers.py

**Comment by zyx0328** [comment]
My model is downloaded from this link: https://huggingface.co/THUDM/CogVideoX1.5-5B. Is that right? You think the problem is about the model not the environment?

**Comment by zyx0328** [comment]
> emm, is your model self-converted or are you using the CogVideoX1.5-5B model that we have converted, because if it's the latter, this issue wouldn't occur, right? If it's to be self-converted, first use the conversion code provided by the diffusers main branch: https://github.com/huggingface/diffusers/blob/main/scripts/convert_cogvideox_to_diffusers.py
My model is downloaded from this link: https://huggingface.co/THUDM/CogVideoX1.5-5B. Is that right? You think the problem is about the model not the environment?

**Comment by zRzRzRzRzRzRzR** [comment]
很明显不是模型的问题，你下载的路径是正确的。我在这个环境下是正常运行的。
```
CUDA_VISIBLE_DEVICES=1 python cli_demo.py --prompt "Leaves gently cascade from the rooftop of a quaint, rustic cottage, their vibrant hues contrasting with the weathered wood. Below, a crystal-clear stream meanders lazily, its tranquil waters reflecting the serene autumn sky. The scene is imbued with a sense of peace and tranquility, as the soft rustling of leaves and the gentle murmur of the stream create a harmonious symphony. The landscape, bathed in the warm, golden light of the setting sun, exudes a timeless beauty, inviting viewers to immerse themselves in this idyllic, pastoral haven." --model_path /share/home/zyx/Models/CogVideoX1.5-5B --generate_type "t2v"   --num_inference_steps 50 --num_frames 81 --height 768 --width 1360
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:04<00:00,  1.09s/it]
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:05<00:00,  1.04s/it]
 12%|████████████████████▍                                                                                                                                                     | 6/50 [01:46<13:01, 17.76s/it]
```
Ruining in this code 
```
https://github.com/THUDM/CogVideo/blob/main/inference/cli_demo.py
```

**Comment by zyx0328** [comment]
> It’s clearly not an issue with the model. The path you downloaded is correct. It runs normally in this environment.
> 
> ```
> CUDA_VISIBLE_DEVICES=1 python cli_demo.py --prompt "Leaves gently cascade from the rooftop of a quaint, rustic cottage, their vibrant hues contrasting with the weathered wood. Below, a crystal-clear stream meanders lazily, its tranquil waters reflecting the serene autumn sky. The scene is imbued with a sense of peace and tranquility, as the soft rustling of leaves and the gentle murmur of the stream create a harmonious symphony. The landscape, bathed in the warm, golden light of the setting sun, exudes a timeless beauty, inviting viewers to immerse themselves in this idyllic, pastoral haven." --model_path /share/home/zyx/Models/CogVideoX1.5-5B --generate_type "t2v"   --num_inference_steps 50 --num_frames 81 --height 768 --width 1360
> Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:04<00:00,  1.09s/it]
> Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:05<00:00,  1.04s/it]
>  12%|████████████████████▍                                                                                                                                                     | 6/50 [01:46<13:01, 17.76s/it]
> ```
> 
> Ruining in this code
> 
> ```
> https://github.com/THUDM/CogVideo/blob/main/inference/cli_demo.py
> ```

Maybe there is something wrong with my environment? I tried downloading the model again but the problem still appears.
![1732100689960](https://github.com/user-attachments/assets/860f1dd9-5b0d-45bb-9ea3-669955b91ead)
But I am confused, when I installed diffusers under the wrong branch, the code could run.

**Comment by Songyuanwei** [comment]
> It’s clearly not an issue with the model. The path you downloaded is correct. It runs normally in this environment.
> 
> ```
> CUDA_VISIBLE_DEVICES=1 python cli_demo.py --prompt "Leaves gently cascade from the rooftop of a quaint, rustic cottage, their vibrant hues contrasting with the weathered wood. Below, a crystal-clear stream meanders lazily, its tranquil waters reflecting the serene autumn sky. The scene is imbued with a sense of peace and tranquility, as the soft rustling of leaves and the gentle murmur of the stream create a harmonious symphony. The landscape, bathed in the warm, golden light of the setting sun, exudes a timeless beauty, inviting viewers to immerse themselves in this idyllic, pastoral haven." --model_path /share/home/zyx/Models/CogVideoX1.5-5B --generate_type "t2v"   --num_inference_steps 50 --num_frames 81 --height 768 --width 1360
> Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:04<00:00,  1.09s/it]
> Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:05<00:00,  1.04s/it]
>  12%|████████████████████▍                                                                                                                                                     | 6/50 [01:46<13:01, 17.76s/it]
> ```
> 
> Ruining in this code
> 
> ```
> https://github.com/THUDM/CogVideo/blob/main/inference/cli_demo.py
> ```

我使用这个命令运行代码，仍然需要6小时生成视频。同样的环境，运行
CogVideoX2B t2v 生成视频时间正常， CogVideoX1.5-5B t2v时间不正常

**Comment by zigchang** [comment]
I am the one who met the OOM in SAT version of CogVideoX-V1.5 last few days, I still have the problem with the renewed Diffusers version.  As you mentioned above, a few places that need to be revised:
1 Update huggingface's CogVideoX1.5-5B latest commit regarding the T2V model

【Yes, I have revised the "sample_height" and "sample_width" to 300, like following:】
![image](https://github.com/user-attachments/assets/032ff955-fcb1-44ad-b0d4-9ee5acaefd0a)

2 Update the source code and install the diffusers library
【Yes, I have re-installed the new-released diffusers libary】
![image](https://github.com/user-attachments/assets/0adc341c-b7bf-4799-aaa9-04f57fcb1188)

3 Since it's A100, you can use pipe.to("cuda"), and it takes 15 minutes.
【Yes, but the speed is rather slow, each step costs around 170s in one A100 gpu】
![image](https://github.com/user-attachments/assets/aed07e6a-24d2-456d-a60e-5743ca7210ac)

![image](https://github.com/user-attachments/assets/1e9ebb69-8e79-4fd4-954c-1f0a115b8253)

What is problem with my operation, how to realize the speed of "it takes 15 minutes"?

**Comment by zRzRzRzRzRzRzR** [comment]
<img width="358" alt="image" src="https://github.com/user-attachments/assets/1b8aba23-7f5e-48fd-a040-f7408ed48831">
Please comment out this sentence.

**Comment by zigchang** [comment]
![image](https://github.com/user-attachments/assets/4f2f31c4-6f96-4285-af91-bd0036425b8f)
Yes, I originally comment out the sentence, however, the speed is even 2X times slower than before,  like following:
![image](https://github.com/user-attachments/assets/7d995a5a-4876-4377-9365-5bac502da2fe)

**Comment by zigchang** [comment]
Another try, 
![image](https://github.com/user-attachments/assets/db882392-177b-405f-a04a-1ea2f34d0612)

**Comment by zigchang** [comment]
Thanks @zRzRzRzRzRzRzR , problems are solved as https://github.com/THUDM/CogVideo/issues/520

**Comment by Songyuanwei** [comment]
> > It’s clearly not an issue with the model. The path you downloaded is correct. It runs normally in this environment.
> > ```
> > CUDA_VISIBLE_DEVICES=1 python cli_demo.py --prompt "Leaves gently cascade from the rooftop of a quaint, rustic cottage, their vibrant hues contrasting with the weathered wood. Below, a crystal-clear stream meanders lazily, its tranquil waters reflecting the serene autumn sky. The scene is imbued with a sense of peace and tranquility, as the soft rustling of leaves and the gentle murmur of the stream create a harmonious symphony. The landscape, bathed in the warm, golden light of the setting sun, exudes a timeless beauty, inviting viewers to immerse themselves in this idyllic, pastoral haven." --model_path /share/home/zyx/Models/CogVideoX1.5-5B --generate_type "t2v"   --num_inference_steps 50 --num_frames 81 --height 768 --width 1360
> > Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:04<00:00,  1.09s/it]
> > Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:05<00:00,  1.04s/it]
> >  12%|████████████████████▍                                                                                                                                                     | 6/50 [01:46<13:01, 17.76s/it]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Ruining in this code
> > ```
> > https://github.com/THUDM/CogVideo/blob/main/inference/cli_demo.py
> > ```
> 
> 我使用这个命令运行代码，仍然需要6小时生成视频。同样的环境，运行 CogVideoX2B t2v 生成视频时间正常， CogVideoX1.5-5B t2v时间不正常

感谢，设置height和width后就好了

**Comment by sunshinewhy** [comment]
> Thanks @zRzRzRzRzRzRzR , problems are solved as #520

How do you solve the low speed inference problem? I meet the same problem
