### ISSUE TITLE
v1.5-5b-i2v 模型的参数有啥需要特别设定的吗

### ISSUE THREAD

**Issue by tangdong1994** [THUDM/CogVideo#542]
我用图生视频模型，85帧，宽和高都是768，但是为啥动起来的效果是这样的。我的prompt是：The foreground features a person performing an action, while the background consists of various random scenes.

https://github.com/user-attachments/assets/f62bcee1-f61d-4df3-86b6-2b5367d10aa0

https://github.com/user-attachments/assets/efbdb668-894f-43ff-9c09-0348ce652ce5

**Comment by tangdong1994** [comment]
那问一下，我这个生成85帧的设定，是不是也是缘由之一

**Comment by zRzRzRzRzRzRzR** [comment]
不是重点，但是确实影响，因为我们训练的长度是81帧

**Comment by tangdong1994** [comment]
> 不是重点，但是确实影响，因为我们训练的长度是81帧

好的，谢谢🙏
