### ISSUE TITLE
Why does the result of t2v model so terrible？

### ISSUE THREAD

**Issue by sunshinewhy** [THUDM/CogVideo#546]
### System Info / 系統信息

Package                  Version       Editable project location
------------------------ ------------- -----------------------------------------------
accelerate               1.1.1
aiofiles                 23.2.1
aiohappyeyeballs         2.4.3
aiohttp                  3.11.6
aiosignal                1.3.1
annotated-types          0.7.0
antlr4-python3-runtime   4.9.3
anyio                    4.6.2.post1
async-timeout            5.0.1
attrs                    21.2.0
Babel                    2.8.0
beartype                 0.19.0
blinker                  1.4
boto3                    1.35.66
botocore                 1.35.66
braceexpand              0.1.7
certifi                  2020.6.20
chardet                  4.0.0
charset-normalizer       3.4.0
click                    8.0.3
cloud-init               23.4.4
colorama                 0.4.4
configobj                5.0.6
cpm-kernels              1.0.11
cryptography             3.4.8
datasets                 3.1.0
dbus-python              1.2.18
decorator                5.1.1
decord                   0.6.0
deepspeed                0.15.4
diffusers                0.32.0.dev0   diffusers-cogvideox1.1-5b/src
dill                     0.3.8
distro                   1.7.0
distro-info              1.1+ubuntu0.2
docker-pycreds           0.4.0
einops                   0.8.0
exceptiongroup           1.2.2
fastapi                  0.115.5
ffmpy                    0.4.0
filelock                 3.16.1
frozenlist               1.5.0
fsspec                   2024.9.0
gitdb                    4.0.11
GitPython                3.1.43
gradio                   5.6.0
gradio_client            1.4.3
h11                      0.14.0
hjson                    3.1.0
httpcore                 1.0.7
httplib2                 0.20.2
httpx                    0.27.2
huggingface-hub          0.26.2
idna                     3.3
imageio                  2.36.0
imageio-ffmpeg           0.5.1
importlib-metadata       4.6.4
jeepney                  0.7.1
Jinja2                   3.0.3
jiter                    0.7.1
jmespath                 1.0.1
jsonpatch                1.32
jsonpointer              2.0
jsonschema               3.2.0
keyring                  23.5.0
kornia                   0.7.4
kornia_rs                0.1.7
launchpadlib             1.10.16
lazr.restfulclient       0.14.4
lazr.uri                 1.0.6
lightning-utilities      0.11.9
markdown-it-py           3.0.0
MarkupSafe               2.0.1
mdurl                    0.1.2
more-itertools           8.10.0
moviepy                  2.0.0
mpmath                   1.3.0
msgpack                  1.1.0
multidict                6.1.0
multiprocess             0.70.16
netifaces                0.11.0
networkx                 3.4.2
ninja                    1.11.1.1
numpy                    1.26.0
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.6.85
nvidia-nvtx-cu12         12.1.105
oauthlib                 3.2.0
omegaconf                2.3.0
openai                   1.55.0
opencv-python            4.10.0.84
orjson                   3.10.11
packaging                24.2
pandas                   2.2.3
Pillow                   9.5.0
pip                      22.0.2
platformdirs             4.3.6
proglog                  0.1.10
propcache                0.2.0
protobuf                 5.28.3
psutil                   5.9.8
py-cpuinfo               9.0.0
pyarrow                  18.0.0
pydantic                 2.10.0
pydantic_core            2.27.0
pydub                    0.25.1
Pygments                 2.18.0
PyGObject                3.42.1
PyJWT                    2.3.0
pyparsing                2.4.7
pyrsistent               0.18.1
pyserial                 3.5
python-apt               2.4.0+ubuntu3
python-dateutil          2.9.0.post0
python-dotenv            1.0.1
python-multipart         0.0.12
pytorch-lightning        2.4.0
pytz                     2022.1
PyYAML                   5.4.1
regex                    2024.11.6
requests                 2.32.3
rich                     13.9.4
ruff                     0.7.4
s3transfer               0.10.4
safehttpx                0.1.1
safetensors              0.4.5
scikit-video             1.1.11
scipy                    1.14.1
SecretStorage            3.3.1
semantic-version         2.10.0
sentencepiece            0.2.0
sentry-sdk               2.19.0
setproctitle             1.3.4
setuptools               59.6.0
shellingham              1.5.4
six                      1.16.0
smmap                    5.0.1
sniffio                  1.3.1
spaces                   0.30.4
spandrel                 0.4.0
ssh-import-id            5.11
starlette                0.41.3
SwissArmyTransformer     0.4.12
sympy                    1.13.3
systemd-python           234
tensorboardX             2.6.2.2
tokenizers               0.20.3
tomlkit                  0.12.0
torch                    2.4.0+cu121
torchaudio               2.4.0+cu121
torchmetrics             1.6.0
torchvision              0.19.0+cu121
tqdm                     4.67.0
transformers             4.46.3
triton                   3.0.0
typer                    0.13.1
typing_extensions        4.12.2
tzdata                   2024.2
ubuntu-drivers-common    0.0.0
unattended-upgrades      0.1
urllib3                  2.2.3
uvicorn                  0.32.1
wadllib                  1.3.6
wandb                    0.18.7
webdataset               0.2.100
websockets               12.0
wheel                    0.37.1
xkit                     0.0.0
xxhash                   3.5.0
yarl                     1.17.2
zipp                     1.0.0

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

python inference/cli_demo.py --prompt "A girl riding a bike." --model_path CogVideo/CogVideoX1.5-5B --generate_type "t2v" --width 1360 --height 768 --num_frames 49

### Expected behavior / 期待表现

normal output Video

**Comment by sunshinewhy** [comment]
The output video is abnormal, how to fix it?

**Comment by zRzRzRzRzRzRzR** [comment]
A girl riding a bike. This needs to be polished with a large model. Too short prompts do not work well in this version of the model. The convert demo includes the few-shot prompt words we provided, allowing the large model to refine the user's input with more details.

**Comment by sunshinewhy** [comment]
> A girl riding a bike. This needs to be polished with a large model. Too short prompts do not work well in this version of the model. The convert demo includes the few-shot prompt words we provided, allowing the large model to refine the user's input with more details.

This problem may not caused by prompt, I can't see anything from the generated video. Can you help me?

https://github.com/user-attachments/assets/21cfd740-e3f7-45be-badc-a5e655130674

**Comment by zRzRzRzRzRzRzR** [comment]
Oh, this issue is likely because you haven't installed the latest main branch of the diffusers library, please pull the latest diffusers and install it.
