### ISSUE TITLE
1.5-I2V训练首帧复制问题

### ISSUE THREAD

**Issue by hjrPhoebus** [THUDM/CogVideo#551]
非常感谢您的工作！
我在1.5I2V版本的推理代码中发现，noise latents是22帧，然后image latents在第0帧处与noise在特征维度拼接。
想确认一下，在训练过程中的操作，是否是将81帧的视频经过vae编码为21帧，复制首帧放在最前面得到22帧（即第0和第1帧latents是相同的？），然后image latents拼接在0帧处？计算loss的时候是使用22帧一起计算还是取[1:]后面21帧计算呢？
期待您的答复！

**Comment by zRzRzRzRzRzRzR** [comment]
是，22帧算 和21帧算都可以，用22帧算吧

**Comment by hjrPhoebus** [comment]
> 是，22帧算 和21帧算都可以，用22帧算吧

非常感谢！另外还有一个小疑问，训练代码中

noisy_images = images + torch.randn_like(images) * image_noise_sigma[:, None, None, None, None]

image_latent_dist = vae.encode(noisy_images).latent_dist

对图像加噪后编码的作用是什么呢？推理的pipeline中似乎没有对image加噪就直接编码拼接

**Comment by zRzRzRzRzRzRzR** [comment]
By adding noise to images during the training process, the model is able to learn how to handle noisy data. This data augmentation strategy can enhance the model's adaptability to different input distributions and prevent the model from overfitting to specific features of the training data. In the inference phase, the model generates clear images through a reverse diffusion process.
In simple terms, the role of adding noise is to train the model to extract valid information from noisy images, thereby enhancing the model's denoising ability and robustness.
