### ISSUE TITLE
video to video fine tune

### ISSUE THREAD

**Issue by TangZhengxu** [THUDM/CogVideo#552]
### Feature request  / 功能建议

Hi authors, thanks for open-sourcing such an amazing project! I've carefully read through your paper and the GitHub repository.
I noticed there's a notebook called `CogVideoX-5B-V2V-Colab.ipynb` in the repo, which shows that CogVideoX supports video-to-video generation during inference. 
I'm wondering if it's possible to fine-tune CogVideoX for video-to-video generation tasks?

### Motivation / 动机

fine-tune model

### Your contribution / 您的贡献

none

**Comment by zRzRzRzRzRzRzR** [comment]
Yes, but this was not done using the native capabilities of our CogVideoX model; it used our T2V capabilities. This should be an engineering operation, not a function of the model's original structure. I'm not sure if fine-tuning can work on this. It probably can't.

**Comment by TangZhengxu** [comment]
got it. thank you so much!
