### ISSUE TITLE
Using gradio_web_demo.py script to inference t2v model is very slowly

### ISSUE THREAD

**Issue by sunshinewhy** [THUDM/CogVideo#553]
### System Info / 系統信息

ubuntu 22.0

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

python gradio_web_demo.py

### Expected behavior / 期待表现

the model can inference faster

**Comment by sunshinewhy** [comment]
I find the size of the out put video is set to adapt 1.0 version model, not 1.5 version model.

**Comment by zRzRzRzRzRzRzR** [comment]
The gradio demo has not been upgraded to 1.5 because the 1.5 model itself is very slow in inference, and it takes 15 minutes even without using any memory-saving work (please check our readme).
