### ISSUE TITLE
通过“I2V”模型进行图片到视频推理出现大量噪声

### ISSUE THREAD

**Issue by liuyifan123123** [THUDM/CogVideo#557]
### System Info / 系統信息

使用cli_demo.py文件
通过“I2V”模型进行图片到视频推理出现大量噪声

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

这是我的shell
![image](https://github.com/user-attachments/assets/6f09a035-56af-4e1e-9d9d-2d1d3a63afbb)
![output](https://github.com/user-attachmen
这是output.jpg，其中分辨率为720x480
https://github.com/user-attachments/assets/1a06e88c-f785-497c-8fa7-0fe0ea782f78
这个是我推理出的视频
ts/assets/127e1acf-2a8f-4fc0-a4aa-1896d438e899)
希望能得到答复，谢谢

### Expected behavior / 期待表现

希望得到的视频能够清晰

**Comment by zRzRzRzRzRzRzR** [comment]
emm，我想知道你的diffusers版本是不是源代码安装，且你的模型仓库是否是最新的HF权重，sample height 和width是300吗。

**Comment by lovejing0306** [comment]
> sample height 和width是300
sample height 和width是300 必须设置成 300 吗？如果直接设置成 300 的话，推理速度非常非常的慢

**Comment by zRzRzRzRzRzRzR** [comment]
这个大量噪声估计是版本没对吧，源代码安装的diffusers并把生成的参数从1.0版本修改成1.5试试，更多的问题，请重新提一个带有具体报错或者复线脚本的issue，感谢理解

**Comment by ZhiXinChasingLight** [comment]
Is it solved? I'm having the same issue @zRzRzRzRzRzRzR @lovejing0306
