### ISSUE TITLE
The conditional image does not seem to be effective in your image-to-video fine-tuning

### ISSUE THREAD

**Issue by changsn** [THUDM/CogVideo#558]
Thank you for your excellent work! 
I have a question about your image-to-video finetuning.
I think you adopt method [encode_video](https://github.com/THUDM/CogVideo/blob/main/finetune/train_cogvideox_image_to_video_lora.py#L1276) to generation the latent of ground-truth video and conditional image. You first split the video into ground-truth video and conditional image. The ground-truth video is correctly converted to "latent_dist" by vae, while ["image_latent_dist"](https://github.com/THUDM/CogVideo/blob/main/finetune/train_cogvideox_image_to_video_lora.py#L1287C9-L1287C26).latent_dist) looks not have relationship with "image" where only the shape, device, and type of "image" are used. 
**Could you help me understand this issue?
Additionally, I have a question regarding the function of image_noise_sigma and the rationale behind selecting a mean of -3 and a std of 0.5. Are there any relevant references or literature on this topic?** 
Thank you! I am looking forward to your reply!

**Comment by DidiD1** [comment]
i tried directly use the image_latent of first frame to train the lora, it seems work well.

**Comment by changsn** [comment]
> i tried directly use the image_latent of first frame to train the lora, it seems work well.

I have not run this code, just review it. However, I think it is a bug in the code. They fixed it in [cogvideox-factory](https://github.com/a-r-r-o-w/cogvideox-factory/blob/main/training/cogvideox_image_to_video_lora.py#L731).

However, I still do not know the principle behind image_noise_sigma and its values of hyperparameters.

**Comment by lovejing0306** [comment]
> i tried directly use the image_latent of first frame to train the lora, it seems work well.

Do you use the cogvideo1.5 weights as pretrained model ?

**Comment by DidiD1** [comment]
> > i tried directly use the image_latent of first frame to train the lora, it seems work well.
> 
> Do you use the cogvideo1.5 weights as pretrained model ?

no, i train it on V1, but if you want to train V1.5, you can use the code in cogvideox-factory.

**Comment by changsn** [comment]
They have repaired this bug I mentioned in Commit a46d762, although they did not respond anything in my issue.
