### ISSUE TITLE
在V100下使用FP16推理只得到全黑图像

### ISSUE THREAD

**Issue by SambyCAT** [THUDM/CogVideo#559]
### System Info / 系統信息

显卡：V100-32GB，其余环境按requirements.txt安装，diffusers库从源码安装

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

使用最新模型(t2v, i2v均可)，将cli_demo.py的数据类型从bf16改成float16
prompt: a girl riding a bike

会得到：
/opt/conda/lib/python3.11/site-packages/diffusers/image_processor.py:147: RuntimeWarning: invalid value encountered in cast
  images = (images * 255).round().astype("uint8")

看起来并不是转换出了问题而是生成的结果有nan
不使用fp16而是使用bf16的话会OOM，所以只能使用fp16

### Expected behavior / 期待表现

正常生成图像

**Comment by zRzRzRzRzRzRzR** [comment]
这个模型不太支持FP16，因此在readme中，我们强烈推荐使用BF16，FP32肯定没问题，如果显存够并且能接受更慢的时间
