### ISSUE TITLE
sat 模式依赖下载失败

### ISSUE THREAD

**Issue by dmzlingyin** [THUDM/CogVideo#56]
`
pip install -r requirements.txt
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting git+https://github.com/THUDM/SwissArmyTransformer.git (from -r requirements.txt (line 1))
  Cloning https://github.com/THUDM/SwissArmyTransformer.git to /tmp/pip-req-build-jv0txfra
  Running command git clone --filter=blob:none --quiet https://github.com/THUDM/SwissArmyTransformer.git /tmp/pip-req-build-jv0txfra
  Resolved https://github.com/THUDM/SwissArmyTransformer.git to commit ad1a8e7a77819a83e747ee793847fa307df9b11b
  Running command git submodule update --init --recursive -q
  git@github.com: Permission denied (publickey).
  fatal: 无法读取远程仓库。

  请确认您有正确的访问权限并且仓库存在。
  fatal: 无法克隆 'git@github.com:THUDM/CogView2.git' 到子模组路径 '/tmp/pip-req-build-jv0txfra/examples/CogView2'
  克隆 'examples/CogView2' 失败。按计划重试
  git@github.com: Permission denied (publickey).
  fatal: 无法读取远程仓库。

  请确认您有正确的访问权限并且仓库存在。
  fatal: 无法克隆 'git@github.com:THUDM/CogView2.git' 到子模组路径 '/tmp/pip-req-build-jv0txfra/examples/CogView2'
  第二次尝试克隆 'examples/CogView2' 失败，退出
`

**Comment by zRzRzRzRzRzRzR** [comment]
要不直接clone main分支 pip install -e .
