### ISSUE TITLE
CogVideoX1.5-5B-I2V 生成图片效果和网页差别很大

### ISSUE THREAD

**Issue by lijain** [THUDM/CogVideo#564]
我这边使用A100 80g   diffusers= 0.32.0.dev0
![企业微信截图_1732871601904](https://github.com/user-attachments/assets/7c41ca5c-2824-4682-8388-83ba6922fa87)
生成的结果

https://github.com/user-attachments/assets/db5e873c-14d1-44f8-ac69-daeae715a533
我在网页上测的
https://github.com/user-attachments/assets/74d1b95e-453f-4d5b-9d98-c83064dcd02e
疑问猜测：1 我给的分辨率太小，不适合你们大分辨的
                  2 prompt=“The train moves slowly from left to right, and the nebula rotates slowly clockwise”  比较短
                 3 code中是768x1360为何网页版出来时1080x1800?
麻烦你有时间解答下，感谢！

**Comment by zRzRzRzRzRzRzR** [comment]
我想知道网页版的是哪个？
1. 这个分辨率确实太小了，我们的readme表格表明了分辨率的范围
2. 与 pipe是否在cuda无关

**Comment by lijain** [comment]
网页版https://chatglm.cn/video?lang=zh

**Comment by zRzRzRzRzRzRzR** [comment]
emm网页的模型和这个不一样的，网页的是商业的模型

**Comment by lijain** [comment]
感谢你的解答，还有个疑问。
按照之前的设置，我在I2V生成的视频中前面曝光度跟高，我将每帧可视化出来发现前面4张图的曝光很高，后面图像基本还行。请问下是什么原因

**Comment by liuxiaoyu1104** [comment]
我和你遇到相同的问题 ，开始帧颜色深，后来我发现 问题是在，https://github.com/huggingface/diffusers/blob/8eb73c872afbe59abab4580aaa591a9851a42e6d/src/diffusers/pipelines/cogvideo/pipeline_cogvideox_image2video.py#L385C9-L390C78        ，在训练cogvideo1.5的时候 ，忘记乘self.vae_scaling_factor_image，但是它除以了self.vae_scaling_factor_image，但是正确的应该是 if not self.vae.config.invert_scale_latents:
            image_latents = self.vae_scaling_factor_image * image_latents
        else:
            # This is awkward but required because the CogVideoX team forgot to multiply the
            # scaling factor during training :)
            image_latents = 1.0* image_latents，我修改这个地方后，cogvideo1.5生成的就正常了
