### ISSUE TITLE
Potential mistake in CogVideoX Paper's Figure 2(a) Regarding 3D VAE Sampling

### ISSUE THREAD

**Issue by rayleichenxi** [THUDM/CogVideo#57]
hi~ thank you for your opensource, it's a great work. 
I am currently reading the CogVideoX paper download from resources/ folder of this repo. I wounder, if there is a mistake in Figure 2 (a), as encoder of 3d VAE should compress the video with 2x DownSample instead of 2x Upsample, and similarly, the decoder should perform a 2x upsample？

![image](https://github.com/user-attachments/assets/066b6b8a-90a9-4f25-a0e7-82248a4239bb)

**Comment by tengjiayan20** [comment]
Thank you for your careful reminder for the typo, you are right, we will correct it.

**Comment by kyrie111** [comment]
![截屏2024-08-07 18 01 56](https://github.com/user-attachments/assets/cee32d75-840b-481e-a6a5-fc347aa481d8)
Additionally, the sentence in the second paragraph of Section 2.1 of the paper (highlighted in blue) seems to be inconsistent with the description of Figure 2.
Should "the first two rounds of downsampling and upsampling" correspond to the top two in the blue box and the bottom two in the yellow box?

**Comment by tengjiayan20** [comment]
> ![截屏2024-08-07 18 01 56](https://private-user-images.githubusercontent.com/52854894/355769803-cee32d75-840b-481e-a6a5-fc347aa481d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzQwMjksIm5iZiI6MTcyMzAzMzcyOSwicGF0aCI6Ii81Mjg1NDg5NC8zNTU3Njk4MDMtY2VlMzJkNzUtODQwYi00ODFlLWE2YTUtZmMzNDdhYTQ4MWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDEyMjg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2M2JhNDZiYWQ2ZjVlOTg4ZjM5MmI1OWExM2I4MmU5N2Y2M2EzNGU5Y2FjZjk1NWE4ZGEzMzgxNGJkNjNlYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AilWxQ14jQjEPtz0qBZp3uX1lY2ytO-ElU-0N-1caDg) Additionally, the sentence in the second paragraph of Section 2.1 of the paper (highlighted in blue) seems to be inconsistent with the description of Figure 2. Should "the first two rounds of downsampling and upsampling" correspond to the top two in the blue box and the bottom two in the yellow box?

You are right, we will update the wording in the official version of the paper to avoid ambiguity.
