### ISSUE TITLE
Video prompting

### ISSUE THREAD

**Issue by danchern97** [THUDM/CogVideo#584]
### Feature request  / 功能建议

Hi, and thanks for the nice work @zRzRzRzRzRzRzR!

I was wondering whether it is possible to prompt the model (CogVideoX-1.5) with multiple images (e.g. part of the video)? It seems like Causal 3D VAE allows it, but our efforts to produce the video weren't successful, the rest of the video just collapsed to a blue screen.

### Motivation / 动机

It would be beneficial to be able to prompt with video to study the autoregressive video generation setting for comparing the generated videos with the ground truth one and provide more control over generation (e.g. control over the initial movement of objects).

### Your contribution / 您的贡献

An attempt has been made to do that with SAT (Swiss Army Transformer) implementation, and with Diffusors library. The encoder-decoder part works fine, however the diffusion corrupts the video and the continuation is collapsed (blue screen).

**Comment by zRzRzRzRzRzRzR** [comment]
I didn't understand, do you want to use multiple images instead of a single image to complete this task? I haven't tried this before, and I believe the current structure is unable to accomplish such a task. @tengjiayan20 Can you take a look? Maybe it's possible?

**Comment by tengjiayan20** [comment]
This function needs additional fine-tuning of cogvideox

**Comment by danchern97** [comment]
Ok, thanks for the clarification!
