### ISSUE TITLE
value error in cogvideox1.5-5b t2v inference

### ISSUE THREAD

**Issue by quantumiracle** [THUDM/CogVideo#587]
### System Info / 系統信息

python 3.11

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

I run the diffusers version inference with:
```
python cli_demo.py --prompt "A girl riding a bike." --model_path THUDM/CogVideoX1.5-5b --generate_type "t2v"
```

### Expected behavior / 期待表现

I got error:
```
ValueError: Trying to set a tensor of shape torch.Size([3072, 128]) in "weight" (which has shape torch.Size([3072, 16, 2, 2])), this looks incorrect.
```
Thanks

**Comment by quantumiracle** [comment]
solved by reinstall latest diffusers:
```
pip install git+https://github.com/huggingface/diffusers.git
```

**Comment by guankaisi** [comment]
I have another question, when I upgrade diffusers the cogvideox1.5-5b t2v is working well but cogvideox-5b and cogvideox-2b have the similar value error.
`ValueError: Trying to set a tensor of shape torch.Size([3072, 16, 2, 2]) in "weight" (which has shape torch.Size([3072, 128])), this looks incorrect.`
If I use diffuser==0.31.0, cogvideox-5b and cogvideox-2b will work well but cogvideox1.5-5b will have the similar problem. Do you know the reason?
