### ISSUE TITLE
About setting of VAE

### ISSUE THREAD

**Issue by txytju** [THUDM/CogVideo#589]
### Feature request  / 功能建议

Not a feature request, but question about vae setting in the tech report. As mentioned in Table1 of tech report, increasing latent channel lead to better PSNR. So why you choose 8x8x4x16 rather than 8x8x4x32?

### Motivation / 动机

NA

### Your contribution / 您的贡献

NA

**Comment by zRzRzRzRzRzRzR** [comment]
Can you provide detailed explanations, thank you.

**Comment by txytju** [comment]
<img width="1191" alt="截屏2024-12-08 11 23 37" src="https://github.com/user-attachments/assets/582292ed-698f-46c8-9f94-7405d76569ec">
As shown in Table 1 in your paper, Variants-C(Compression8×8×4, Latent channel32) show better reconstruction quality than Variants-B(Compression8×8×4, Latent channel16), Why do you choose Variants-B for DiT training rather than Variants-C?

**Comment by yzy-thu** [comment]
Based on experience with text2image, increasing the latent channel raises the learning difficulty and slows the convergence, often requiring larger model sizes to accommodate the larger latent channel. We believe that 16 channels are more suitable for a 5B model. However, this part has not been rigorously validated through ablation studies.
