### ISSUE TITLE
how to reproduce the demo's generated video quality?

### ISSUE THREAD

**Issue by codeplay0000** [THUDM/CogVideo#59]
testing the model on my machine ,the quality of the generated video is much worse than demo show case.

**Comment by zRzRzRzRzRzRzR** [comment]
Do you using GLM-4 or GPT-4 to enhance the prompt? maybe can check web_demo.py

**Comment by tengjiayan20** [comment]
In today's various generative models, prompt polishing is very important for the generated results.

**Comment by user425846** [comment]
I can maybe get to like 50-70% of quality to their examples, even with the same prompts. Are the examples really of this model or of their next "Pro" model?

**Comment by zRzRzRzRzRzRzR** [comment]
It is this model and we will update pro model demo video when it is release.
did you using with 50 step DDIM sampler and gs 6

**Comment by JHLEE17** [comment]
I have the same problem. The quality of the reproduced example seems to be only around 50-70% in exactly same condition.

**Comment by tengjiayan20** [comment]
May there is a little performance loss when converting from sat version to hf version. You can try sat version for inference or wait for our better model soon.
