### ISSUE TITLE
About value error about Cogvideox-t2v and the version of diffusers

### ISSUE THREAD

**Issue by guankaisi** [THUDM/CogVideo#592]
### System Info / 系統信息

I have meet the same problem as  [#587](https://github.com/THUDM/CogVideo/issues/587) I upgrade diffusers to 0.32.0.dev the cogvideox1.5-5b t2v is working well but cogvideox-5b and cogvideox-2b have the similar value error. ValueError: Trying to set a tensor of shape torch.Size([3072, 16, 2, 2]) in "weight" (which has shape torch.Size([3072, 128])), this looks incorrect.
If I use diffuser==0.31.0, cogvideox-5b and cogvideox-2b will work well but cogvideox1.5-5b will have the similar problem. Do you know the reason?

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. Set diffusers==0.31.0, CogVideox-2b and CogVideox-5b work well but CogVideox1.5-5b has value error.
2. Set diffusers==0.32.0.dev. CogVideox1.5-5b works well but CogVideox-2b and CogVideox-5b have value error.

### Expected behavior / 期待表现

All the models will work well.

**Comment by OleehyO** [comment]
When using diffusers==0.32.0.dev, all three models are working correctly on my machine. Could you please provide more detailed information?

**Comment by guankaisi** [comment]
Hello, I use the script
```
torchrun --nproc_per_node=4 parallel_inference_xdit.py \
    --THUDM/CogVideoX-2b --ulysses_degree 1 --ring_degree 2 \
    --use_cfg_parallel --height 480 --width 720 --num_frames 49 \
    --prompt 'A leaf turns from green to red.' --seed 42  \
    --num_inference_steps 50  \
```

It reports the value error
```
ValueError: Cannot load /fs/fast/share/aimind_files/video_eval/VideoTuna/checkpoints/cogvideo/CogVideoX-2b/transformer  because patch_embed.proj.weight expected shape tensor(..., device='meta', size=(1920, 128)), but got torch.Size([1920, 16, 2, 2]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.
```

For my conda env packages, we use
```
transformers              4.39.3 
flash-attn                2.6.3  
xfuser                    0.4.0  
diffusers                 0.32.0.dev0 
```
But if I use `THUDM/CogVideoX1.5-5B`, it will work well.

**Comment by guankaisi** [comment]
The strange thing is that in the same environment when I use Videosys to accelerate inference Cogvideox-2b and Cogvideox-5b, can run normally.
I run this script `https://github.com/NUS-HPC-AI-Lab/VideoSys/blob/master/examples/inference/cogvideox/sample.py`

**Comment by OleehyO** [comment]
You can try updating the `transformers` to a newer version (e.g., 4.47). Also, I recommend using CogVideoX-5b or CogVideoX1.5-5b with xdit. Currently, CogVideoX-2b has some issues when sequence parallelism is enabled in xdit (If you need to use CogVideoX-2b, stick to CFG parallelism only)

**Comment by guankaisi** [comment]
Sorry, I updated the `transformers` version but still have the value error problem with cogvideox-5b (it works well with cogvideox-1.5).  I will use `Videosys` to inference cogvideox-5b.
