### ISSUE TITLE
CogVideoX-1.5 t2v使用sat权重，进行fp16精度推理，生成视频黑屏

### ISSUE THREAD

**Issue by wmm-coding** [THUDM/CogVideo#593]
### System Info / 系統信息

 NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     python 3.10

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. 修改cogvideox1.5_5b.yaml中的权重路径为本地sat权重路径
2. 修改inference.yaml中的权重路径为sat权重路径，修改精度为 fp16: True
args:
  latent_channels: 16
  mode: inference
  load: "CogVideoX1.5-5B-SAT/transformer_t2v" # This is for Full model without lora adapter
  batch_size: 1
  input_type: txt
  input_file: configs/test.txt
  sampling_image_size: [768, 1360] # remove this for I2V
  sampling_num_frames: 22  # 42 for 10 seconds and 22 for 5 seconds
  sampling_fps: 16
  fp16: True
  output_dir: outputs/
  force_inference: True
3. 执行推理脚本
4. 推理结果

https://github.com/user-attachments/assets/01e3e121-36d8-4547-af40-601f63512e84

### Expected behavior / 期待表现

readme中表示支持fp16推理，但实际生成视频错误，请问原因是什么

**Comment by OleehyO** [comment]
所有CogVideo的5B模型权重都是用bf16存的，建议使用bf16而不是fp16对5B的模型进行推理。
