### ISSUE TITLE
How to use multi GPUs at inference 

### ISSUE THREAD

**Issue by KasenYoung** [THUDM/CogVideo#594]
I met OOM problem when I did inference while turning off all optimization:
pipe.enable_sequential_cpu_offload()
pipe.vae.enable_slicing()
pipe.vae.enable_tiling()

However, when I didn't turn off cpu optimization, it was very slow on loading components. I wonder if I can use multi GPU to accelarate inference while avoiding OOM. If I can, how can I implement it? I have found no scripts.

**Comment by OleehyO** [comment]
You can use XDIT for multi-GPU inference, as CogVideo has been integrated into it. Check out the code for parallel inference [here](https://github.com/THUDM/CogVideo/tree/main/tools/parallel_inference).

**Comment by BASSEM45325** [comment]
does it support i2v ?

> You can use XDIT for multi-GPU inference, as CogVideo has been integrated into it. Check out the code for parallel inference [here](https://github.com/THUDM/CogVideo/tree/main/tools/parallel_inference).
