### ISSUE TITLE
Could you also provide a guide related to CogVideoX-I2V Finetune?

### ISSUE THREAD

**Issue by JINSUBY** [THUDM/CogVideo#600]
### Feature request  / 功能建议

Thank you for sharing such an excellent work. Could you also provide a guide related to CogVideoX-I2V Finetune?

### Motivation / 动机

NA

### Your contribution / 您的贡献

NA

**Comment by OleehyO** [comment]
Yes, we have prepared a detailed guide for CogVideoX-I2V finetune [here](https://github.com/THUDM/CogVideo/blob/main/finetune/train_cogvideox_image_to_video_lora.py).
