### ISSUE TITLE
cogvideox-1.5-5b微调报错

### ISSUE THREAD

**Issue by linwenzhao1** [THUDM/CogVideo#604]
### System Info / 系統信息

diffuser: 0.32.0.dev0
python: 3.11
cuda: 12.0

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

你好，请问这个是什么问题？
image
einops.EinopsError: Error while processing rearrange-reduction pattern "b (t o h p w q) c -> b (t h w) (c o p q)".
Input tensor shape: torch.Size([2, 1036800, 49]). Additional info: {'t': 1, 'h': 240, 'w': 360, 'o': 2, 'p': 2, 'q': 2}.
Shape mismatch, 1036800 != 691200

### Expected behavior / 期待表现

python参数: --base configs/cogvideox1.5_5b.yaml configs/sft_5b_t2v.yaml --seed 17796
模型是：CogVideoX1.5-5B-SAT/transformer_t2v ， CogVideoX1.5-5B-SAT/t5-v1_1-xxl， CogVideoX1.5-5B-SAT/vae/3d-vae.pt

**Comment by linwenzhao1** [comment]
![image](https://github.com/user-attachments/assets/a65e3b46-ba97-4496-98a9-02c3ab64676a)

**Comment by zRzRzRzRzRzRzR** [comment]
我们SAT的微调代码没有适配CogVideoX1.5，你需要使用diffusers的模型和实现来微调哦

**Comment by lovejing0306** [comment]
> 我们SAT的微调代码没有适配CogVideoX1.5，你需要使用diffusers的模型和实现来微调哦



> ![image](https://private-user-images.githubusercontent.com/51796215/395953657-a65e3b46-ba97-4496-98a9-02c3ab64676a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NjA1NTYsIm5iZiI6MTczNDY2MDI1NiwicGF0aCI6Ii81MTc5NjIxNS8zOTU5NTM2NTctYTY1ZTNiNDYtYmE5Ny00NDk2LTk4YTktMDJjM2FiNjQ2NzZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDAyMDQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMzY0NTVjNTEwZTA3MWVlMjZiYzAyNTVjODQxNGYxM2M2MjNjN2I5MjU2ZTg4NDcxYzgxZmU5ZTUyMjFkOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rGYlmKRwUWHDTD-MoRjUD8VshwCCwVdG5DKj2_HW4qs)

diffusers 版本的训练的代码对 vae 做了 切片处理，如果只是单纯的训练 lora 模型，可以永远都训练不出来一个好的模型

**Comment by AmazDeng** [comment]
> 我们SAT的微调代码没有适配CogVideoX1.5，你需要使用diffusers的模型和实现来微调哦
@zRzRzRzRzRzRzR 

sat可以用来多卡训练，需要高配版显卡，显存高，卡多，可以全量从零开始训练。目前只支持CogVideoX-5B和CogVideoX-5B-I2V
diffusers可以支持单卡微调，需要的显存低，支持低端显卡。目前支持CogVideoX-5B，CogVideoX-5B-I2V，CogVideoX1.5-5B，CogVideoX1.5-5B-I2V
我这样理解，对吗？

**Comment by Beijia11** [comment]
> ![image](https://private-user-images.githubusercontent.com/51796215/395953657-a65e3b46-ba97-4496-98a9-02c3ab64676a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NjY3MDEsIm5iZiI6MTczNDc2NjQwMSwicGF0aCI6Ii81MTc5NjIxNS8zOTU5NTM2NTctYTY1ZTNiNDYtYmE5Ny00NDk2LTk4YTktMDJjM2FiNjQ2NzZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA3MzMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYzdjOTI4MjliMDZjODgzNDZkNDg2ODlmMGY2YjAzODc3YTQzMGNjODRiY2FlZDc5NzMyZWM2YTYwNWNlYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TQmX1IrDQfH7h7rrVpoTV1ymire7gnUsPDLQFv5yTOM)

请问解决这个问题了吗
