### ISSUE TITLE
Question about the context parallel setting in Video VAE

### ISSUE THREAD

**Issue by Chester-CS** [THUDM/CogVideo#609]
Dear Developers of CogVideo:

Hello! Thank you for your contributions to the field of video generation. I have recently been trying to reproduce the training part of Causal Video VAE based on your code repository and paper. I would like to ask about the settings of the three values in the forward function: input_cp, latent_cp, and output_cp when training on long videos. Specifically, during training, do you gather the outputs from different workers within a group and then compute the loss, or do you compute the loss for different segments of the video separately, and finally let the training framework gather the gradients? I would greatly appreciate your guidance.

CogVideo的开发者们：
    你们好~ 感谢你们为视频生成领域做出的贡献。我最近在根据你们的代码仓库和论文复现Causal Video VAE的训练部分。我想请教一下在实际训练长视频的时候，forward函数的这三个值input_cp， latent_cp和output_cp的设置是什么样的？即在训练的时候是否会gather组内不同worker的输出然后计算loss。还是分开计算不同视频段的loss最后由训练框架来gather梯度呢。望不吝赐教。
<img width="971" alt="image" src="https://github.com/user-attachments/assets/0385360a-daf1-4d4b-aaf3-05e86a332d54" />

**Comment by OleehyO** [comment]
Can you provide detailed explanations, thank you. @yzy-thu

**Comment by Chester-CS** [comment]
> Can you provide detailed explanations, thank you. @yzy-thu

感谢你的回复。我理解视频Causal VAE使用了Context Parallel在集群上训练。例如一个81帧的视频对10个worker组成的Causal Group就是 [9, 8 ,8 ... 8] 这样的tiling方式，每一张卡负责一部分，在CausalConv前向的时候进行通讯。我现在比较困惑的是训练时与之搭配使用的VAE的Encode和Decode方法，和loss计算的方式。例如长度为9的第一块儿视频，编码结束的latent长度是3。 长度为8的一块儿视频，编码结束的latent长度是2。81帧编码成latent就是[3, 2, 2... 2]这样的分块儿。Decode重建完成后也同样是[9, 8, ... 8]这样的分块儿。我比较好奇在计算loss（kl loss， disc loss， rec loss）的时候，会先将latent/rec video拼在一起再计算还是每个worker单独计算它负责的那部分（例如其中一个worker负责长度为8的视频分块儿，它可以单独计算它这部分的loss，也可以先gather其他worker的结果拼成完整的rec video然后再计算loss）。不知道这两者是否等价，还是其中一种本就不正确。

**Comment by yzy-thu** [comment]
我们是每个当做一个独立的video分开算的，这样实现比较方便

**Comment by Chester-CS** [comment]
谢谢你们的帮助，感激不尽~
