### ISSUE TITLE
咨询下1.5的帧数问题

### ISSUE THREAD

**Issue by wmm-coding** [THUDM/CogVideo#614]
### System Info / 系統信息

python 3.10

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

使用sat推理
1. sampling_num_frames为22，cogvideox1.5_5b.yaml配置文件中num_frames为什么是81不是85？，
![image](https://github.com/user-attachments/assets/1a36dc85-47c1-49a9-9926-2d6c287e9626)
2. 为什么decode的时候，最后的end_frame到21不是22？
![image](https://github.com/user-attachments/assets/4fbe6f5a-aeb6-4a89-85be-d0daab48b4cf)
3. decode后的shape，为什么是([1, 84, 768, 1360, 3])，不是81或85？

帧数这块有点晕，求解答

### Expected behavior / 期待表现

求解帧数在流程中的变化

**Comment by OleehyO** [comment]
输入81帧，vae在帧数会压缩4倍，去噪模型在patchify的时候以2帧为单位（所以需要padding一帧），因此在去噪时采样的帧数是22（88/4），解码前会把padding的1帧取出来（21帧），21帧给vae decode时会出来81帧(9+8+8+8+8+8+8+8+8+8，第一次decode 3帧，之后每次decode 2帧)。

sat框架的推理代码即将弃用，建议使用[cli_demo.py](https://github.com/THUDM/CogVideo/blob/main/inference/cli_demo.py)中的代码运行推理。

**Comment by wmm-coding** [comment]
> 输入81帧，vae在帧数会压缩4倍，去噪模型在patchify的时候以2帧为单位（所以需要padding一帧），因此在去噪时采样的帧数是22（88/4），解码前会把padding的1帧取出来（21帧），21帧给vae decode时会出来81帧(9+8+8+8+8+8+8+8+8+8，第一次decode 3帧，之后每次decode 2帧)。
> 
> sat框架的推理代码即将弃用，建议使用[cli_demo.py](https://github.com/THUDM/CogVideo/blob/main/inference/cli_demo.py)中的代码运行推理。

那请问sat框架的推理代码弃用后，后续的模式是，使用sat微调完后，对训练出的权重进行转换，转换为huggingface格式的权重，然后再用diffusers进行推理吗？

**Comment by wmm-coding** [comment]
群侠CogVideoX1.5   diffusers的推理现在支持了吗

**Comment by wmm-coding** [comment]
![image](https://github.com/user-attachments/assets/6d3255f2-1f2f-4500-8171-d231a1178e4b)
请问，readme中提示1.5的文本长度为224tokens，为何推理时cli_demo.py以及配置文件中，均设置226长度？

**Comment by OleehyO** [comment]
> ![image](https://private-user-images.githubusercontent.com/191336202/397372687-040102f7-98b9-4a22-9e8a-2cd95a0cca97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2ODMyNzksIm5iZiI6MTczNDY4Mjk3OSwicGF0aCI6Ii8xOTEzMzYyMDIvMzk3MzcyNjg3LTA0MDEwMmY3LTk4YjktNGEyMi05ZThhLTJjZDk1YTBjY2E5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQwODIyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMWZmMTkxYzQyMjUwZGI0MDRlYTEwYTRiMDM3ZGZkYjhlMzRjNmNkOWM3ZjU5OGZiZWRlYjg2MzlhYjE5NDgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zoaiJ_z3zJara9X9I_C8GkRcg5GGYbCyqhtz7MVmUbY) 你好，请问padding这一帧大约是在代码什么位置？

https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/cogvideo/pipeline_cogvideox.py#L663

**Comment by wmm-coding** [comment]
> > ![image](https://private-user-images.githubusercontent.com/191336202/397372687-040102f7-98b9-4a22-9e8a-2cd95a0cca97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2ODMyNzksIm5iZiI6MTczNDY4Mjk3OSwicGF0aCI6Ii8xOTEzMzYyMDIvMzk3MzcyNjg3LTA0MDEwMmY3LTk4YjktNGEyMi05ZThhLTJjZDk1YTBjY2E5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQwODIyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMWZmMTkxYzQyMjUwZGI0MDRlYTEwYTRiMDM3ZGZkYjhlMzRjNmNkOWM3ZjU5OGZiZWRlYjg2MzlhYjE5NDgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zoaiJ_z3zJara9X9I_C8GkRcg5GGYbCyqhtz7MVmUbY) 你好，请问padding这一帧大约是在代码什么位置？
> 
> https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/cogvideo/pipeline_cogvideox.py#L663

抱歉，是我描述的不够清晰，我想请问的是sat框架中，大约在什么位置padding的

**Comment by wmm-coding** [comment]
另外，我想请教下，我在使用cli_demo.py进行推理时，我发现相比于1.0，rotary_positional_embeddings涉及到比较大的变动，但是在sat框架推理中，位置编码rotary函数没什么变动，这点是由于上面说的sat框架推理代码要弃用的原因吗？

**Comment by wmm-coding** [comment]
另外，我想请教下，我在使用cli_demo.py进行推理时，我发现相比于1.0，rotary_positional_embeddings涉及到比较大的变动，但是在sat框架推理中，位置编码rotary函数没什么变动，这点是由于上面说的sat框架推理代码要弃用的原因吗？

rotary_positional_embeddings相关的变动训练流程不会涉及吗？（目前我们在用sat框架进行训练）

**Comment by wmm-coding** [comment]
另外，我想请教下，我在使用cli_demo.py进行推理时，我发现相比于1.0，rotary_positional_embeddings涉及到比较大的变动，但是在sat框架推理中，位置编码rotary函数没什么变动，这点是由于上面说的sat框架推理代码要弃用的原因吗？

rotary_positional_embeddings相关的变动训练流程不会涉及吗？（目前我们在用sat框架进行1.5的训练）

**Comment by wmm-coding** [comment]
@OleehyO  作者你好，请再帮忙确认下上述疑问谢谢，（我已咨询过，在1.5版本使用sat框架训练和推理是完全支持的）

**Comment by jacobswan1** [comment]
@wmm-coding 这个只是在inference做了padding。其实是一个trick处理非偶数帧。

sat的代码他们没有更新维护，我理解你推理的时候照着改进去是一样的。

1.5他们把t5的context从224改到226，对结果应该没有影响。

sat代码非常混乱，强烈建议全部重新维护重写。。。

**Comment by wmm-coding** [comment]
> @wmm-coding 这个只是在inference做了padding。其实是一个trick处理非偶数帧。
> 
> sat的代码他们没有更新维护，我理解你推理的时候照着改进去是一样的。
> 
> 1.5他们把t5的context从224改到226，对结果应该没有影响。
> 
> rotary_positional_embeddings sat和diffusers写法不一样有略微差别，一个是写死的，一个是实时计算。我对比过，数值上有略微差距，可能对结果影响不大，但是我注意到sat模型转diffusers结果差异巨大，应该是数值差异造成的。所以说这个sat的代码导致了很多开发人员的churn，一开始就不应该从swisstransformer的 repo开始开发，理解可能是为了照顾自家产品。现在转成diffusers是正确的方向

好的，明白了，十分感谢！
