### ISSUE TITLE
star完钱在哪里领

### ISSUE THREAD

**Issue by zhoujiawei2** [THUDM/CogVideo#624]
### System Info / 系統信息

无

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

![屏幕截图 2024-12-27 210213](https://github.com/user-attachments/assets/91ef6a05-982c-4528-996a-df8096712422)

**Comment by zRzRzRzRzRzRzR** [comment]
请问这是哪里的截图？我们从未允许这样的事情。这是一个严重的事件。
如果是智谱员工做的，请通过我们邮件 opensource@zhipuai.cn 举报。
感谢支持。
