### ISSUE TITLE
通过 DistributedDataParallel 分布式推理报错：  'CogVideoXPipeline' object has no attribute 'named_parameters'

### ISSUE THREAD

**Issue by sanweiw** [THUDM/CogVideo#66]
通过 DistributedDataParallel 分布式推理报错： 
![image](https://github.com/user-attachments/assets/3737f1fc-84a3-4d66-a01b-7dfd121f8e39)

**Comment by zRzRzRzRzRzRzR** [comment]
HF已经写了，不支持分布式，暂时没办法解决

**Comment by zRzRzRzRzRzRzR** [comment]
现在可以多GPU推理了，尝试按照最新的cli demo执行
