### ISSUE TITLE
Fail to find "sat.mpu", "sat.model" and "sat.training"

### ISSUE THREAD

**Issue by passerby233** [THUDM/CogVideo#70]
from sat.model.base_model import get_model
from sat.training.model_io import load_checkpoint
from sat import mpu

but not find corresponding files

**Comment by hhnqqq** [comment]
https://github.com/THUDM/SwissArmyTransformer，clone this repo and run `python install .`

**Comment by hhnqqq** [comment]
pip install .  (my bad)
