### ISSUE TITLE
对于目前开源代码的疑问

### ISSUE THREAD

**Issue by libaolu312** [THUDM/CogVideo#73]
非常感谢您的开源，这对科研工作者的帮助是巨大的！

1. 请问用diffusers和sat为何显存有差距，二者推理的效果差异大吗

2. 请问后续是否可以对sat文件夹下的代码进行注释补充，这对于新手上手代码是十分友好的。

3. CogVideo/sat/requirements.txt   该文件对应的SwissArmyTransformer 这个repo好像有些问题，以下为输出信息：
pip install -r requirements.txt

Cloning https://github.com/THUDM/SwissArmyTransformer.git to /tmp/pip-req-build-dhu_g5gf
  Running command git clone --filter=blob:none --quiet https://github.com/THUDM/SwissArmyTransformer.git /tmp/pip-req-build-dhu_g5gf
  Resolved https://github.com/THUDM/SwissArmyTransformer.git to commit ad1a8e7a77819a83e747ee793847fa307df9b11b
  Running command git submodule update --init --recursive -q
  git@github.com: Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
  fatal: clone of 'git@github.com:THUDM/CogView2.git' into submodule path '/tmp/pip-req-build-dhu_g5gf/examples/CogView2' failed
  Failed to clone 'examples/CogView2'. Retry scheduled
  git@github.com: Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
  fatal: clone of 'git@github.com:THUDM/CogView2.git' into submodule path '/tmp/pip-req-build-dhu_g5gf/examples/CogView2' failed
  Failed to clone 'examples/CogView2' a second time, aborting
  
  
  最后再次感觉您的开源，这是一项令人兴奋的工作！

**Comment by zRzRzRzRzRzRzR** [comment]
1. 不太明白你说的区别，算法我们是一个模块一个模块对应的，工程上的区别是正常的
2. sat直接从主分支进行安装或许更好，因为主分支才能正常的微调，如果你只是要推理，你直接装0.4.11就好啦

**Comment by libaolu312** [comment]
感谢您的回复

冒昧再问，不太懂您第二点的意思，您说的主分支是指？

我理解的意思可能是在/18235372684/CogVideo/sat文件夹下直接git clone https://github.com/THUDM/SwissArmyTransformer.git

**Comment by libaolu312** [comment]
感谢您的回复

冒昧再问，不太明白你第二点的意思，你说的主分支是指？

我理解的意思可能是在/18235372684/CogVideo/sat文件夹下直接git克隆https://github.com/THUDM/SwissArmyTransformer.git

**Comment by libaolu312** [comment]
感谢您的回复

冒昧再问，不太明白您第二点的意思，您说的主分支是指？

我理解的意思可能是在/18235372684/CogVideo/sat文件夹下直接git克隆https://github.com/THUDM/SwissArmyTransformer.git

**Comment by libaolu312** [comment]
> > 1. 不太明白你说的区别，算法我们是一个模块一个模块对应的，工程上的区别是正常的
> > 2. sat直接从主分支进行安装或许更好，因为主分支才能正常的微调，如果你只是要推理，你直接装0.4.11就好啦
> 
> 你好，感谢开源。想问下主分支里面sat的推理脚本看着少了几个文件，比如model、training、mpu，请问这几个文件是必要的么？后面会push上来么

这部分其实是在https://github.com/THUDM/SwissArmyTransformer/tree/main/sat

CogVideo/sat文件下的requirements.txt文件有标明，但是这个repo的安装有点问题，我对此也比较疑惑

**Comment by enjoybo** [comment]
这是来自QQ邮箱的自动回复邮件。邮件已收到，谢谢!

**Comment by enjoybo** [comment]
> > > 1. 不太明白你说的区别，算法我们是一个模块一个模块对应的，工程上的区别是正常的
> > > 2. sat直接从主分支进行安装或许更好，因为主分支才能正常的微调，如果你只是要推理，你直接装0.4.11就好啦
> > 
> > 
> > 你好，感谢开源。想问下主分支里面sat的推理脚本看着少了几个文件，比如model、training、mpu，请问这几个文件是必要的么？后面会push上来么
> 
> 这部分其实是在https://github.com/THUDM/SwissArmyTransformer/tree/main/sat
> 
> CogVideo/sat文件下的requirements.txt文件有标明，但是这个repo的安装有点问题，我对此也比较疑惑

在SAT下安装requirements.txt还是不行是吧？

**Comment by libaolu312** [comment]
> 1. 不太明白你说的区别，算法我们是一个模块一个模块对应的，工程上的区别是正常的
> 2. sat直接从主分支进行安装或许更好，因为主分支才能正常的微调，如果你只是要推理，你直接装0.4.11就好啦

通过看别的问题得到一个新的理解：

如果需要做微调：
git clone https://github.com/THUDM/SwissArmyTransformer.git
cd SwissArmyTransformer
pip install -e .

这样的话可以将sat装到python环境中，就可以正常调用mpu等

不知道这样是不是您提到的在主分支中进行安装

**Comment by libaolu312** [comment]
> > > > 1. 不太明白你说的区别，算法我们是一个模块一个模块对应的，工程上的区别是正常的
> > > > 2. sat直接从主分支进行安装或许更好，因为主分支才能正常的微调，如果你只是要推理，你直接装0.4.11就好啦
> > > 
> > > 
> > > 你好，感谢开源。想问下主分支里面sat的推理脚本看着少了几个文件，比如model、training、mpu，请问这几个文件是必要的么？后面会push上来么
> > 
> > 
> > 这部分其实是在https://github.com/THUDM/SwissArmyTransformer/tree/main/sat
> > CogVideo/sat文件下的requirements.txt文件有标明，但是这个repo的安装有点问题，我对此也比较疑惑
> 
> 在SAT下安装requirements.txt还是不行是吧？

是的，这样会遇到问题

**Comment by tengjiayan20** [comment]
对于sat环境的相关问题，我们已经更新了sat目录下的requirement.txt和readme，可以重新尝试，对之前造成的困惑我们感到抱歉

**Comment by libaolu312** [comment]
> 对于sat环境的相关问题，我们已经更新了sat目录下的requirement.txt和readme，可以重新尝试，对之前造成的困惑我们感到抱歉

非常感谢

请问如果我要做微调工作，sat的版本是否应该安装0.4.12

**Comment by tengjiayan20** [comment]
> > 对于sat环境的相关问题，我们已经更新了sat目录下的requirement.txt和readme，可以重新尝试，对之前造成的困惑我们感到抱歉
> 
> 非常感谢
> 
> 请问如果我要做微调工作，sat的版本是否应该安装0.4.12

是的，sat目录下的readme里finetune一节，已经更新了相关内容

Yes, the finetune section in the readme under the sat directory has been updated with relevant content
