### ISSUE TITLE
Longer video generation

### ISSUE THREAD

**Issue by SutirthaChakraborty** [THUDM/CogVideo#78]
Is there any way how can we make continuous long videos using the model?

**Comment by zRzRzRzRzRzRzR** [comment]
The model has not been trained for longer durations videos and can only generate videos up to 6 seconds long.

**Comment by SutirthaChakraborty** [comment]
Any way around to make them longer ? @zRzRzRzRzRzRzR

**Comment by XksA-me** [comment]
Maybe what you mean is whether there is any setting or prompt that can be used to make the two or more generated videos consistent in terms of pictures and characters. I look forward to the official answer and sharing.

**Comment by SutirthaChakraborty** [comment]
Yes @XksA-me  kind a story based.
