### ISSUE TITLE
Bug: Tensor not contiguous when boardcast tensor with deepspeed when finetuning

### ISSUE THREAD

**Issue by rlsu9** [THUDM/CogVideo#81]
### System Info / 系統信息

cuda 12.1
python 3.10.12
SwissArmyTransformer-0.4.12

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

when I use the official script to launch the finetune job, a tensor not contiguous err is report for deepspeed training, the config is not changed except the relative path, the following is the error info

[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/hao.zhang/rlsu/rlsu_code_folder/CogVideo/sat/train_video.py", line 225, in <module>
[rank0]:     training_main(
[rank0]:   File "/lustre/scratch/users/hao.zhang/dacheng/anaconda3/envs/cogvid/lib/python3.10/site-packages/sat/training/deepspeed_training.py", line 116, in training_main
[rank0]:     model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
[rank0]:   File "/lustre/scratch/users/hao.zhang/dacheng/anaconda3/envs/cogvid/lib/python3.10/site-packages/sat/training/deepspeed_training.py", line 225, in setup_model_untrainable_params_and_optimizer
[rank0]:     model, optimizer, _, _ = deepspeed.initialize(
[rank0]:   File "/lustre/scratch/users/hao.zhang/dacheng/anaconda3/envs/cogvid/lib/python3.10/site-packages/deepspeed/__init__.py", line 181, in initialize
[rank0]:     engine = DeepSpeedEngine(args=args,
[rank0]:   File "/lustre/scratch/users/hao.zhang/dacheng/anaconda3/envs/cogvid/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 262, in __init__
[rank0]:     self._configure_distributed_model(model)
[rank0]:   File "/lustre/scratch/users/hao.zhang/dacheng/anaconda3/envs/cogvid/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1148, in _configure_distributed_model
[rank0]:     self._broadcast_model()
[rank0]:   File "/lustre/scratch/users/hao.zhang/dacheng/anaconda3/envs/cogvid/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1068, in _broadcast_model
[rank0]:     dist.broadcast(p.data, groups._get_broadcast_src_rank(), group=self.seq_data_parallel_group)
[rank0]:   File "/lustre/scratch/users/hao.zhang/dacheng/anaconda3/envs/cogvid/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 117, in log_wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/lustre/scratch/users/hao.zhang/dacheng/anaconda3/envs/cogvid/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 224, in broadcast
[rank0]:     return cdb.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
[rank0]:   File "/lustre/scratch/users/hao.zhang/dacheng/anaconda3/envs/cogvid/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 600, in _fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/lustre/scratch/users/hao.zhang/dacheng/anaconda3/envs/cogvid/lib/python3.10/site-packages/deepspeed/comm/torch.py", line 199, in broadcast
[rank0]:     return torch.distributed.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
[rank0]:   File "/lustre/scratch/users/hao.zhang/dacheng/anaconda3/envs/cogvid/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/lustre/scratch/users/hao.zhang/dacheng/anaconda3/envs/cogvid/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2209, in broadcast
[rank0]:     work = group.broadcast([tensor], opts)
[rank0]: ValueError: Tensors must be contiguous

### Expected behavior / 期待表现

I didn't get the reason for the bug, do you have any idea about how to fix it?

**Comment by zRzRzRzRzRzRzR** [comment]
If you want to fine-tune, I suggest directly pulling the main branch from the SAT GitHub and installing it using pip install -e .. Additionally, I suspect that the T5 model is not in safetensor format. Could you use the T5 we provide in our HF repo? Merge the files from tokenizer and test_encoder into a single T5 file with a safetensor suffix to be compatible with the latest transformers library. Although these T5 models are identical, this approach might resolve the issue.

**Comment by rlsu9** [comment]
Thanks for your reply, sir.
Actually the SAT is install from source by clone and `pip install .`
and the T5 model is get by `git clone https://huggingface.co/google/t5-v1_1-xxl.git` with files `config.json  generation_config.json  pytorch_model.bin  README.md  special_tokens_map.json  spiece.model  tf_model.h5  tokenizer_config.json` as shown in the hugging face repo
however after redownloading the t5 and reinstall the SAT, the problem still exist. Am I downloaded the wrong repo? Your reply will be highly appreciated.

**Comment by XksA-me** [comment]
I don't know if there is an error in your t5 model clone. The default pytorch_model.bin and tf_model.h5 files of this model are 88g, which is too large. You can check whether the pytorch_model.bin file size or md5 value is normal. Generally, the download may fail. My method is:
```bash
git clone https://huggingface.co/google/t5-v1_1-xxl.git
cd t5-v1_1-xxl
wget https://huggingface.co/google/t5-v1_1-xxl/resolve/main/pytorch_model.bin
```

Hope it helps you.

**Comment by zhenbuxianggaimingzi** [comment]
I also encountered the same problem, I also checked the t5 model, the file size seems to be fine,
![image](https://github.com/user-attachments/assets/3f880cec-8a08-47e4-8948-0d56b773a96c)

sat is also install from github source and ```pip install .```, but I still get an error

**Comment by zRzRzRzRzRzRzR** [comment]
Try the new readme way? I rerun it now and worked not need for 90GB disk now

**Comment by zhenbuxianggaimingzi** [comment]
it worked for me after follow new readme way, thanks a lot~
```
git clone https://huggingface.co/THUDM/CogVideoX-2b.git
mkdir t5-v1_1-xxl
mv CogVideoX-2b/text_encoder/* CogVideoX-2b/tokenizer/* t5-v1_1-xxl
```
