### ISSUE TITLE
cannot import name 'CogVideoXPipeline' from 'diffusers'

### ISSUE THREAD

**Issue by Hit-ZhangTing** [THUDM/CogVideo#83]
### System Info / 系統信息

I user pip install git+https://github.com/huggingface/diffusers.git@878f609aa5ce4a78fea0f048726889debde1d7e8#egg=diffusers to install diffusers
but have wrong
Traceback (most recent call last):
  File "/home/zhangting/CogVideo/test.py", line 2, in <module>
    from diffusers import CogVideoXPipeline
ImportError: cannot import name 'CogVideoXPipeline' from 'diffusers' (/opt/anaconda/anaconda3/lib/python3.10/site-packages/diffusers/__init__.py)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

pip install git+https://github.com/huggingface/diffusers.git@878f609aa5ce4a78fea0f048726889debde1d7e8#egg=diffusers to install diffusers

### Expected behavior / 期待表现

how to solve this problem?

**Comment by zRzRzRzRzRzRzR** [comment]
try again if you using web demo. rerun the code. If you installed it normally, this issue should be quite rare.

**Comment by ruifengma** [comment]
same error

**Comment by zRzRzRzRzRzRzR** [comment]
install the diffusers >=0.30.0 will worked? release now
