### ISSUE TITLE
Is there a demo that supports generating videos from image?

### ISSUE THREAD

**Issue by chenxinhua** [THUDM/CogVideo#84]
Is there a demo that supports generating videos from image?

**Comment by XksA-me** [comment]
It seems that there is no such thing at the moment. Maybe you can use some method to convert the image into a prompt, add a video action prompt, and then provide it to CogVideo-2B for iterative video generation.

Looking forward to the official sharing of relevant information.

**Comment by zRzRzRzRzRzRzR** [comment]
Yes, that’s correct. In Qingying,our pruduct in readme. However, this is the commercial model currently used in our product.
We currently have no plans to open source it in the near future. Thank you for your understanding.
