### ISSUE TITLE
I hope you can share the method of GLM-4 Enhance Prompt

### ISSUE THREAD

**Issue by XksA-me** [THUDM/CogVideo#86]
Hello, can you reproduce the method or prompt words of using GLM-4 Enhance Prompt? I use sat and input prompt to generate directly. The effect is very different from the official case. I think it’s a problem with my prompt words.

- My prompts:
> Under the sprawling shade of an ancient oak tree, a spirited cow-patterned cat and a sleek white cat engaged in a lively game of chase. The dappled sunlight filtered through the leaves, casting playful shadows on the soft, grassy ground. As they darted and pounced with boundless energy, their eyes sparkled with mischief and joy. Suddenly, the white cat's attention was captured by the rustling of leaves, gently swayed by a whimsical breeze. Entranced, the white cat paused mid-chase, its gaze fixed on the dancing foliage above, momentarily forgetting the game as the cow cat skidded to a halt, curiously watching its friend.

- Generate Effects：
<img width="751" alt="image" src="https://github.com/user-attachments/assets/33416b3d-a42a-47a6-97aa-74ea01fe37cd">

**Comment by tengjiayan20** [comment]
https://github.com/THUDM/CogVideo/blob/main/inference/convert_demo.py
You can find it here.

**Comment by XksA-me** [comment]
So good, thanks for sharing.
