### ISSUE TITLE
Why the use of FP16 instead of BF16 precision?

### ISSUE THREAD

**Issue by TheTinyTeddy** [THUDM/CogVideo#87]
Hi, thank you for the great work!

I was wondering why the precision used for CogVideoX is FP16, whereas other T2V models such as Open-Sora and Open-Sora-Plan use BF16.

Also, I notice in pipeline_cogvideox.py a comment where # pipe = CogVideoXPipeline.from_pretrained("THUDM/CogVideoX-2b", torch_dtype=torch.bfloat16).to("cuda"), which is a different precision to the one used in the example (that is torch.float16).

**Comment by TheTinyTeddy** [comment]
Thank you for the swift reply! 

I was wondering if there is any ongoing plan for releasing a bf16 version?

**Comment by zRzRzRzRzRzRzR** [comment]
Pro will use BF16

**Comment by lith0613** [comment]
> Pro will use BF16

请问代码里面要想改成bf16做finetune要怎么修改配置呢
