### ISSUE TITLE
Please check that dataloader loads lables from txt failed

### ISSUE THREAD

**Issue by NickPan7779** [THUDM/CogVideo#99]
### System Info / 系統信息

py3.9

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

[CogVideo](https://github.com/THUDM/CogVideo/tree/main)/[sat](https://github.com/THUDM/CogVideo/tree/main/sat)
/data_video.py line 428
 `caption_path = os.path.join(root, filename.replace("videos", "labels").replace(".mp4", ".txt"))`
the bug here should be fixed as `caption_path = os.path.join(root, filename.replace(".mp4", ".txt")).replace("videos", "labels")`

the root path is video path
.
├── labels
│   ├── 1.txt
│   ├── 2.txt
│   ├── ...
└── videos
    ├── 1.mp4
    ├── 2.mp4
    ├── ...

### Expected behavior / 期待表现

load lables successfully

**Comment by tengjiayan20** [comment]
Thank you for your carefulness! We will correct the typo soon.
